"""
MANAS Intent Generator - Proactive Intent Creation.

OPUS-032: The Cognitive Kernel

"The mind is not a vessel to be filled, but a fire to be kindled."
    - Plutarch

This module generates intents by analyzing system state:
- Scans Prakriti (unified state) for opportunities
- Identifies issues before they become problems
- Suggests improvements based on patterns
- Respects rate limits and human-in-the-loop

Intent Types:
- HOUSEKEEPING: Cleanup, organization (low risk)
- OPTIMIZATION: Performance, refactoring (medium risk)
- REPAIR: Fix detected issues (medium risk)
- ENHANCEMENT: New capabilities (high risk)
"""

import logging
import subprocess
from dataclasses import dataclass, field
from datetime import datetime, timedelta
from enum import Enum
from pathlib import Path
from typing import Any, Dict, List, Optional

logger = logging.getLogger("MANAS.Intent")


class IntentPriority(Enum):
    """Priority levels for intents."""

    LOW = "low"  # Can wait, nice to have
    MEDIUM = "medium"  # Should do soon
    HIGH = "high"  # Important, do next
    CRITICAL = "critical"  # Do immediately (auto-execute if allowed)


class IntentRisk(Enum):
    """Risk levels for intents."""

    SAFE = "safe"  # Can auto-execute (e.g., cleanup logs)
    LOW = "low"  # Probably fine, but verify
    MEDIUM = "medium"  # Needs human approval
    HIGH = "high"  # Definitely needs human approval


@dataclass
class Intent:
    """A proactive intention generated by MANAS."""

    id: str  # Unique ID (e.g., "manas_001")
    intent_type: str  # Category (e.g., "cleanup_branches")
    title: str  # Short title for display
    description: str  # Detailed description
    reasoning: str  # Why MANAS thinks this is needed
    priority: IntentPriority = IntentPriority.MEDIUM
    risk: IntentRisk = IntentRisk.MEDIUM
    created_at: str = field(default_factory=lambda: datetime.utcnow().isoformat())
    circuit_to_execute: Optional[str] = None  # If we know which circuit to run
    params: Dict[str, Any] = field(default_factory=dict)  # Parameters for execution
    auto_executable: bool = False  # Can this run without approval?
    expires_at: Optional[str] = None  # When this intent becomes stale

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary for serialization."""
        return {
            "id": self.id,
            "intent_type": self.intent_type,
            "title": self.title,
            "description": self.description,
            "reasoning": self.reasoning,
            "priority": self.priority.value,
            "risk": self.risk.value,
            "created_at": self.created_at,
            "circuit_to_execute": self.circuit_to_execute,
            "params": self.params,
            "auto_executable": self.auto_executable,
            "expires_at": self.expires_at,
        }

    def is_expired(self) -> bool:
        """Check if intent has expired."""
        if not self.expires_at:
            return False
        return datetime.utcnow().isoformat() > self.expires_at


class IntentGenerator:
    """
    Generates proactive intents by analyzing system state.

    This is the "thinking" part of MANAS - it observes and suggests.

    Analyzers:
    - Git state (stale branches, uncommitted changes)
    - Code health (TODOs, complexity)
    - Documentation drift
    - Test coverage gaps
    - Resource usage patterns
    """

    def __init__(self, workspace: Optional[Path] = None, memory_store: Optional[Any] = None):
        """
        Initialize intent generator.

        Args:
            workspace: Workspace root
            memory_store: Optional MemoryStore for learning
        """
        self._workspace = workspace or Path.cwd()
        self._memory = memory_store
        self._intent_counter = 0
        self._analyzers = self._register_analyzers()

    def _register_analyzers(self) -> List[callable]:
        """Register all intent analyzers."""
        return [
            self._analyze_stale_branches,
            self._analyze_uncommitted_changes,
            self._analyze_stale_todos,
            self._analyze_test_health,
            self._analyze_documentation_drift,
            self._analyze_log_cleanup,
        ]

    def generate_intents(self, context: Optional[Dict[str, Any]] = None) -> List[Intent]:
        """
        Generate intents based on current system state.

        Args:
            context: Optional additional context (e.g., from Prakriti)

        Returns:
            List of generated intents
        """
        intents = []
        context = context or {}

        for analyzer in self._analyzers:
            try:
                intent = analyzer(context)
                if intent:
                    # Check memory - should we skip this?
                    if self._should_skip_intent(intent):
                        logger.debug(f"Skipping intent {intent.intent_type} (memory/cooldown)")
                        continue
                    intents.append(intent)
            except Exception as e:
                logger.debug(f"Analyzer {analyzer.__name__} failed: {e}")

        # Sort by priority
        priority_order = {
            IntentPriority.CRITICAL: 0,
            IntentPriority.HIGH: 1,
            IntentPriority.MEDIUM: 2,
            IntentPriority.LOW: 3,
        }
        intents.sort(key=lambda i: priority_order.get(i.priority, 99))

        logger.info(f"Generated {len(intents)} intents")
        return intents

    def _should_skip_intent(self, intent: Intent) -> bool:
        """Check if we should skip this intent based on memory."""
        if not self._memory:
            return False

        # Skip if in cooldown after failure
        if self._memory.is_in_cooldown(intent.intent_type):
            return True

        # Skip if recently rejected by user
        if self._memory.was_recently_rejected(intent.intent_type):
            return True

        return False

    def _next_intent_id(self) -> str:
        """Generate next intent ID."""
        self._intent_counter += 1
        return f"manas_{self._intent_counter:04d}"

    # =========================================================================
    # ANALYZERS - Each returns an Intent or None
    # =========================================================================

    def _analyze_stale_branches(self, context: Dict[str, Any]) -> Optional[Intent]:
        """
        Detect stale git branches (>30 days without commits).

        Risk: LOW (cleanup is safe)
        """
        try:
            # Get branches with last commit date
            result = subprocess.run(
                [
                    "git",
                    "for-each-ref",
                    "--sort=-committerdate",
                    "--format=%(refname:short) %(committerdate:relative)",
                    "refs/heads/",
                ],
                capture_output=True,
                text=True,
                timeout=10,
                cwd=str(self._workspace),
            )

            if result.returncode != 0:
                return None

            stale_branches = []
            for line in result.stdout.strip().split("\n"):
                if not line:
                    continue
                parts = line.split(" ", 1)
                if len(parts) < 2:
                    continue
                branch, age = parts
                # Check for "months" or "years" in age
                if any(x in age.lower() for x in ["month", "year"]):
                    # Skip main/master
                    if branch not in ("main", "master", "develop"):
                        stale_branches.append(branch)

            if len(stale_branches) >= 3:
                return Intent(
                    id=self._next_intent_id(),
                    intent_type="cleanup_stale_branches",
                    title=f"Clean up {len(stale_branches)} stale branches",
                    description=f"Found {len(stale_branches)} branches that haven't been updated in months: {', '.join(stale_branches[:5])}{'...' if len(stale_branches) > 5 else ''}",
                    reasoning="Stale branches clutter the repository and can cause confusion. Regular cleanup improves navigability.",
                    priority=IntentPriority.LOW,
                    risk=IntentRisk.LOW,
                    params={"branches": stale_branches},
                    auto_executable=False,  # Needs approval
                    expires_at=(datetime.utcnow() + timedelta(days=7)).isoformat(),
                )

        except Exception as e:
            logger.debug(f"Stale branch analysis failed: {e}")

        return None

    def _analyze_uncommitted_changes(self, context: Dict[str, Any]) -> Optional[Intent]:
        """
        Detect uncommitted changes that have been sitting for too long.

        Risk: MEDIUM (committing requires review)
        """
        try:
            # Check for uncommitted changes
            result = subprocess.run(
                ["git", "status", "--porcelain"],
                capture_output=True,
                text=True,
                timeout=10,
                cwd=str(self._workspace),
            )

            if result.returncode != 0:
                return None

            changes = [line for line in result.stdout.strip().split("\n") if line]

            if len(changes) > 10:
                return Intent(
                    id=self._next_intent_id(),
                    intent_type="commit_pending_changes",
                    title=f"Commit {len(changes)} pending changes",
                    description=f"There are {len(changes)} uncommitted changes in the working tree. Consider organizing them into commits.",
                    reasoning="Large numbers of uncommitted changes increase the risk of losing work and make it harder to review changes.",
                    priority=IntentPriority.MEDIUM,
                    risk=IntentRisk.MEDIUM,
                    params={"change_count": len(changes)},
                    auto_executable=False,  # Never auto-commit
                )

        except Exception as e:
            logger.debug(f"Uncommitted changes analysis failed: {e}")

        return None

    def _analyze_stale_todos(self, context: Dict[str, Any]) -> Optional[Intent]:
        """
        Detect TODOs that have been in the codebase for a long time.

        Risk: LOW (just awareness)
        """
        try:
            # Count TODOs in codebase
            result = subprocess.run(
                ["grep", "-r", "--include=*.py", "-c", "TODO"],
                capture_output=True,
                text=True,
                timeout=30,
                cwd=str(self._workspace / "vibe_core"),
            )

            # Parse output to count total TODOs
            total_todos = 0
            for line in result.stdout.strip().split("\n"):
                if ":" in line:
                    try:
                        count = int(line.split(":")[-1])
                        total_todos += count
                    except ValueError:
                        pass

            if total_todos > 20:
                return Intent(
                    id=self._next_intent_id(),
                    intent_type="review_todos",
                    title=f"Review {total_todos} TODOs in codebase",
                    description=f"Found {total_todos} TODO comments in the codebase. Some may be outdated or no longer relevant.",
                    reasoning="TODOs are technical debt markers. Regular review ensures they're still valid and prioritized appropriately.",
                    priority=IntentPriority.LOW,
                    risk=IntentRisk.SAFE,
                    params={"todo_count": total_todos},
                    auto_executable=False,  # Review only
                )

        except Exception as e:
            logger.debug(f"TODO analysis failed: {e}")

        return None

    def _analyze_test_health(self, context: Dict[str, Any]) -> Optional[Intent]:
        """
        Check test suite health from context.

        Risk: SAFE (just running tests)
        """
        # Look for test health in context (from Prakriti)
        test_health = context.get("test_health", {})
        archived_count = test_health.get("archived", 0)

        if archived_count > 0:
            return Intent(
                id=self._next_intent_id(),
                intent_type="revive_archived_tests",
                title=f"Revive {archived_count} archived test(s)",
                description=f"There are {archived_count} tests in the archive that may need attention.",
                reasoning="Archived tests represent known technical debt. Reviving them improves test coverage.",
                priority=IntentPriority.LOW,
                risk=IntentRisk.LOW,
                params={"archived_count": archived_count},
                auto_executable=False,
            )

        return None

    def _analyze_documentation_drift(self, context: Dict[str, Any]) -> Optional[Intent]:
        """
        Detect documentation that may be out of sync with code.

        Risk: LOW (just awareness)
        """
        # Check OPUS verification score from context
        verification = context.get("verification", {})
        trust_score = verification.get("trust_score", 100)

        if trust_score < 80:
            failures = verification.get("failures", [])
            return Intent(
                id=self._next_intent_id(),
                intent_type="fix_documentation_drift",
                title=f"Fix documentation drift (trust: {trust_score}%)",
                description=f"Documentation verification shows {trust_score}% trust score with {len(failures)} issues.",
                reasoning="Documentation drift means the code and docs are out of sync. This causes confusion and onboarding friction.",
                priority=IntentPriority.MEDIUM if trust_score < 70 else IntentPriority.LOW,
                risk=IntentRisk.LOW,
                circuit_to_execute="OPUS_AUTO_HEAL",
                params={"trust_score": trust_score, "failure_count": len(failures)},
                auto_executable=False,
            )

        return None

    def _analyze_log_cleanup(self, context: Dict[str, Any]) -> Optional[Intent]:
        """
        Check if log files need cleanup.

        Risk: SAFE (just deleting old logs)
        """
        try:
            log_dir = self._workspace / ".opus_state" / "logs"
            if not log_dir.exists():
                return None

            # Count log files older than 7 days
            cutoff = datetime.utcnow() - timedelta(days=7)
            old_logs = []

            for log_file in log_dir.glob("*.log"):
                mtime = datetime.fromtimestamp(log_file.stat().st_mtime)
                if mtime < cutoff:
                    old_logs.append(log_file.name)

            if len(old_logs) >= 5:
                return Intent(
                    id=self._next_intent_id(),
                    intent_type="cleanup_old_logs",
                    title=f"Clean up {len(old_logs)} old log files",
                    description=f"Found {len(old_logs)} log files older than 7 days in .opus_state/logs/",
                    reasoning="Old log files consume disk space and are rarely needed after a week.",
                    priority=IntentPriority.LOW,
                    risk=IntentRisk.SAFE,  # Safe to auto-execute
                    params={"log_files": old_logs},
                    auto_executable=True,  # Can run without approval!
                    expires_at=(datetime.utcnow() + timedelta(days=3)).isoformat(),
                )

        except Exception as e:
            logger.debug(f"Log cleanup analysis failed: {e}")

        return None
