"""
MANAS Intent Generator - Proactive Intent Creation.

OPUS-032: The Cognitive Kernel

"The mind is not a vessel to be filled, but a fire to be kindled."
    - Plutarch

This module generates intents by analyzing system state:
- Scans Prakriti (unified state) for opportunities
- Identifies issues before they become problems
- Suggests improvements based on patterns
- Respects rate limits and human-in-the-loop

Intent Types:
- HOUSEKEEPING: Cleanup, organization (low risk)
- OPTIMIZATION: Performance, refactoring (medium risk)
- REPAIR: Fix detected issues (medium risk)
- ENHANCEMENT: New capabilities (high risk)
"""

import logging
import subprocess
from dataclasses import dataclass, field
from datetime import datetime, timedelta
from enum import Enum
from pathlib import Path
from typing import Any, Dict, List, Optional

logger = logging.getLogger("MANAS.Intent")


class IntentPriority(Enum):
    """Priority levels for intents."""

    LOW = "low"  # Can wait, nice to have
    MEDIUM = "medium"  # Should do soon
    HIGH = "high"  # Important, do next
    CRITICAL = "critical"  # Do immediately (auto-execute if allowed)


class IntentRisk(Enum):
    """Risk levels for intents."""

    SAFE = "safe"  # Can auto-execute (e.g., cleanup logs)
    LOW = "low"  # Probably fine, but verify
    MEDIUM = "medium"  # Needs human approval
    HIGH = "high"  # Definitely needs human approval


@dataclass
class Intent:
    """A proactive intention generated by MANAS."""

    id: str  # Unique ID (e.g., "manas_001")
    intent_type: str  # Category (e.g., "cleanup_branches")
    title: str  # Short title for display
    description: str  # Detailed description
    reasoning: str  # Why MANAS thinks this is needed
    priority: IntentPriority = IntentPriority.MEDIUM
    risk: IntentRisk = IntentRisk.MEDIUM
    created_at: str = field(default_factory=lambda: datetime.utcnow().isoformat())
    circuit_to_execute: Optional[str] = None  # If we know which circuit to run
    params: Dict[str, Any] = field(default_factory=dict)  # Parameters for execution
    auto_executable: bool = False  # Can this run without approval?
    expires_at: Optional[str] = None  # When this intent becomes stale
    # WEAVING: Semantic links to related code/docs
    related_files: List[str] = field(default_factory=list)  # e.g., ["jnana.py:151"]
    related_docs: List[str] = field(default_factory=list)  # e.g., ["076-NO-PUSSY-MODE.md"]

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary for serialization."""
        return {
            "id": self.id,
            "intent_type": self.intent_type,
            "title": self.title,
            "description": self.description,
            "reasoning": self.reasoning,
            "priority": self.priority.value,
            "risk": self.risk.value,
            "created_at": self.created_at,
            "circuit_to_execute": self.circuit_to_execute,
            "params": self.params,
            "auto_executable": self.auto_executable,
            "expires_at": self.expires_at,
            "related_files": self.related_files,
            "related_docs": self.related_docs,
        }

    def is_expired(self) -> bool:
        """Check if intent has expired."""
        if not self.expires_at:
            return False
        return datetime.utcnow().isoformat() > self.expires_at


class IntentGenerator:
    """
    Generates proactive intents by analyzing system state.

    This is the "thinking" part of MANAS - it observes and suggests.

    Analyzers:
    - Git state (stale branches, uncommitted changes)
    - Code health (TODOs, complexity)
    - Documentation drift
    - Test coverage gaps
    - Resource usage patterns
    - Contract violations (OPUS-032: The Immune System)
    """

    def __init__(self, workspace: Optional[Path] = None, memory_store: Optional[Any] = None):
        """
        Initialize intent generator.

        Args:
            workspace: Workspace root
            memory_store: Optional MemoryStore for learning
        """
        self._workspace = workspace or Path.cwd()
        self._memory = memory_store
        self._intent_counter = 0
        self._analyzers = self._register_analyzers()

        # OPUS-032: Modular class-based analyzers (the new way)
        self._modular_analyzers = self._register_modular_analyzers()

        # 🧠 SEMANTIC ENGINE (Lazy Injection)
        self._semantic_engine = None

    def inject_semantic_engine(self, engine: Any) -> None:
        """Inject the Semantic Engine for Level 2 intelligence."""
        self._semantic_engine = engine
        logger.info("🧠 IntentGenerator: Semantic Engine injected")

    def _register_analyzers(self) -> List[callable]:
        """Register all intent analyzers (legacy method-based)."""
        return [
            self._analyze_stale_branches,
            self._analyze_uncommitted_changes,
            self._analyze_stale_todos,
            self._analyze_test_health,
            self._analyze_documentation_drift,
            self._analyze_log_cleanup,
            # OPUS-032: Self-Documentation Analyzers
            self._analyze_readme_staleness,
            self._analyze_self_documentation,
            # OPUS-032: The Ouroboros Protocol
            self._analyze_capability_gaps,
        ]

    def _register_modular_analyzers(self) -> List[Any]:
        """
        Register modular class-based analyzers (OPUS-032, OPUS-077).

        These are the new-style analyzers that inherit from BaseAnalyzer.
        They provide better separation of concerns and are easier to test.
        """
        from .analyzers import CIMonitorAnalyzer, ContractAnalyzer, PratyayaAnalyzer, SemanticAnalyzer

        return [
            ContractAnalyzer(workspace=self._workspace),
            SemanticAnalyzer(workspace=self._workspace),  # 51% - The Genesis Impulse
            CIMonitorAnalyzer(workspace=self._workspace),  # OPUS-041 - VAK (The Voice)
            PratyayaAnalyzer(workspace=self._workspace),  # OPUS-077 - Self-Falsification
        ]

    async def generate_intents(self, context: Optional[Dict[str, Any]] = None) -> List[Intent]:
        """
        Generate intents based on current system state. (Async for semantic analysis)

        Args:
            context: Optional additional context (e.g., from Prakriti)

        Returns:
            List of generated intents
        """
        intents = []
        context = context or {}

        # OPUS-032: Run modular class-based analyzers FIRST (the new way)
        # These handle structured data like verification_results
        for analyzer in self._modular_analyzers:
            try:
                if not analyzer.is_enabled:
                    continue
                new_intents = analyzer.analyze(context)
                for intent in new_intents:
                    if self._should_skip_intent(intent):
                        logger.debug(f"Skipping intent {intent.intent_type} (memory/cooldown)")
                        continue
                    intents.append(intent)
            except Exception as e:
                logger.debug(f"Modular analyzer {analyzer.name} failed: {e}")

        # Legacy method-based analyzers (still useful for git/file checks)
        for analyzer in self._analyzers:
            try:
                intent = analyzer(context)
                if intent:
                    # Check memory - should we skip this?
                    if self._should_skip_intent(intent):
                        logger.debug(f"Skipping intent {intent.intent_type} (memory/cooldown)")
                        continue
                    intents.append(intent)
            except Exception as e:
                logger.debug(f"Analyzer {analyzer.__name__} failed: {e}")

        # 🧠 SEMANTIC ANALYSIS (Level 2)
        if self._semantic_engine:
            try:
                semantic_intents = await self._analyze_semantic_opportunities(context)
                intents.extend(semantic_intents)
            except Exception as e:
                logger.warning(f"🧠 Semantic analysis failed: {e}")

        # BHAKTI ↔ MEMORY: Boost intents that have proven successful ("muscle memory")
        if self._memory:
            successful = self._memory.get_successful_patterns()
            for intent in intents:
                if intent.intent_type in successful and intent.priority != IntentPriority.CRITICAL:
                    # Boost by one level - the system learns what works
                    boosted = {
                        IntentPriority.LOW: IntentPriority.MEDIUM,
                        IntentPriority.MEDIUM: IntentPriority.HIGH,
                        IntentPriority.HIGH: IntentPriority.CRITICAL,
                    }
                    intent.priority = boosted.get(intent.priority, intent.priority)
                    logger.info(f"🧠 MUSCLE MEMORY: Boosted '{intent.intent_type}' (proven success)")

        # Sort by priority
        priority_order = {
            IntentPriority.CRITICAL: 0,
            IntentPriority.HIGH: 1,
            IntentPriority.MEDIUM: 2,
            IntentPriority.LOW: 3,
        }
        intents.sort(key=lambda i: priority_order.get(i.priority, 99))

        logger.info(f"Generated {len(intents)} intents")
        return intents

    def _should_skip_intent(self, intent: Intent) -> bool:
        """Check if we should skip this intent based on memory."""
        if not self._memory:
            return False

        # Skip if in cooldown after failure
        if self._memory.is_in_cooldown(intent.intent_type):
            return True

        # Skip if recently rejected by user
        if self._memory.was_recently_rejected(intent.intent_type):
            return True

        return False

    def _next_intent_id(self) -> str:
        """Generate next intent ID."""
        self._intent_counter += 1
        return f"manas_{self._intent_counter:04d}"

    # =========================================================================
    # ANALYZERS - Each returns an Intent or None
    # =========================================================================

    def _analyze_stale_branches(self, context: Dict[str, Any]) -> Optional[Intent]:
        """
        Detect stale git branches (>30 days without commits).

        Risk: LOW (cleanup is safe)
        """
        try:
            # Get branches with last commit date
            result = subprocess.run(
                [
                    "git",
                    "for-each-ref",
                    "--sort=-committerdate",
                    "--format=%(refname:short) %(committerdate:relative)",
                    "refs/heads/",
                ],
                capture_output=True,
                text=True,
                timeout=10,
                cwd=str(self._workspace),
            )

            if result.returncode != 0:
                return None

            stale_branches = []
            for line in result.stdout.strip().split("\n"):
                if not line:
                    continue
                parts = line.split(" ", 1)
                if len(parts) < 2:
                    continue
                branch, age = parts
                # Check for "months" or "years" in age
                if any(x in age.lower() for x in ["month", "year"]):
                    # Skip main/master
                    if branch not in ("main", "master", "develop"):
                        stale_branches.append(branch)

            if len(stale_branches) >= 3:
                return Intent(
                    id=self._next_intent_id(),
                    intent_type="cleanup_stale_branches",
                    title=f"Clean up {len(stale_branches)} stale branches",
                    description=f"Found {len(stale_branches)} branches that haven't been updated in months: {', '.join(stale_branches[:5])}{'...' if len(stale_branches) > 5 else ''}",
                    reasoning="Stale branches clutter the repository and can cause confusion. Regular cleanup improves navigability.",
                    priority=IntentPriority.LOW,
                    risk=IntentRisk.LOW,
                    params={"branches": stale_branches},
                    auto_executable=False,  # Needs approval
                    expires_at=(datetime.utcnow() + timedelta(days=7)).isoformat(),
                )

        except Exception as e:
            logger.debug(f"Stale branch analysis failed: {e}")

        return None

    def _analyze_uncommitted_changes(self, context: Dict[str, Any]) -> Optional[Intent]:
        """
        Detect uncommitted changes that have been sitting for too long.

        Risk: MEDIUM (committing requires review)
        """
        try:
            # Check for uncommitted changes
            result = subprocess.run(
                ["git", "status", "--porcelain"],
                capture_output=True,
                text=True,
                timeout=10,
                cwd=str(self._workspace),
            )

            if result.returncode != 0:
                return None

            changes = [line for line in result.stdout.strip().split("\n") if line]

            if len(changes) > 10:
                return Intent(
                    id=self._next_intent_id(),
                    intent_type="commit_pending_changes",
                    title=f"Commit {len(changes)} pending changes",
                    description=f"There are {len(changes)} uncommitted changes in the working tree. Consider organizing them into commits.",
                    reasoning="Large numbers of uncommitted changes increase the risk of losing work and make it harder to review changes.",
                    priority=IntentPriority.MEDIUM,
                    risk=IntentRisk.MEDIUM,
                    params={"change_count": len(changes)},
                    auto_executable=False,  # Never auto-commit
                )

        except Exception as e:
            logger.debug(f"Uncommitted changes analysis failed: {e}")

        return None

    def _analyze_stale_todos(self, context: Dict[str, Any]) -> Optional[Intent]:
        """
        Detect TODOs that have been in the codebase for a long time.

        Risk: LOW (just awareness)
        """
        try:
            # Count TODOs in codebase
            result = subprocess.run(
                ["grep", "-r", "--include=*.py", "-c", "TODO"],
                capture_output=True,
                text=True,
                timeout=30,
                cwd=str(self._workspace / "vibe_core"),
            )

            # Parse output to count total TODOs
            total_todos = 0
            for line in result.stdout.strip().split("\n"):
                if ":" in line:
                    try:
                        count = int(line.split(":")[-1])
                        total_todos += count
                    except ValueError:
                        pass

            if total_todos > 20:
                return Intent(
                    id=self._next_intent_id(),
                    intent_type="review_todos",
                    title=f"Review {total_todos} TODOs in codebase",
                    description=f"Found {total_todos} TODO comments in the codebase. Some may be outdated or no longer relevant.",
                    reasoning="TODOs are technical debt markers. Regular review ensures they're still valid and prioritized appropriately.",
                    priority=IntentPriority.LOW,
                    risk=IntentRisk.SAFE,
                    params={"todo_count": total_todos},
                    auto_executable=False,  # Review only
                )

        except Exception as e:
            logger.debug(f"TODO analysis failed: {e}")

        return None

    def _analyze_test_health(self, context: Dict[str, Any]) -> Optional[Intent]:
        """
        Check test suite health from context.

        Risk: SAFE (just running tests)
        """
        # Look for test health in context (from Prakriti)
        test_health = context.get("test_health", {})
        archived_count = test_health.get("archived", 0)

        if archived_count > 0:
            return Intent(
                id=self._next_intent_id(),
                intent_type="revive_archived_tests",
                title=f"Revive {archived_count} archived test(s)",
                description=f"There are {archived_count} tests in the archive that may need attention.",
                reasoning="Archived tests represent known technical debt. Reviving them improves test coverage.",
                priority=IntentPriority.LOW,
                risk=IntentRisk.LOW,
                params={"archived_count": archived_count},
                auto_executable=False,
            )

        return None

    def _analyze_documentation_drift(self, context: Dict[str, Any]) -> Optional[Intent]:
        """
        Detect documentation that may be out of sync with code.

        Risk: LOW (just awareness)
        """
        # Check OPUS verification score from context
        verification = context.get("verification", {})
        trust_score = verification.get("trust_score", 100)

        if trust_score < 80:
            failures = verification.get("failures", [])
            return Intent(
                id=self._next_intent_id(),
                intent_type="fix_documentation_drift",
                title=f"Fix documentation drift (trust: {trust_score}%)",
                description=f"Documentation verification shows {trust_score}% trust score with {len(failures)} issues.",
                reasoning="Documentation drift means the code and docs are out of sync. This causes confusion and onboarding friction.",
                priority=IntentPriority.MEDIUM if trust_score < 70 else IntentPriority.LOW,
                risk=IntentRisk.LOW,
                circuit_to_execute="OPUS_AUTO_HEAL",
                params={"trust_score": trust_score, "failure_count": len(failures)},
                auto_executable=False,
            )

        return None

    def _analyze_log_cleanup(self, context: Dict[str, Any]) -> Optional[Intent]:
        """
        Check if log files need cleanup.

        Risk: SAFE (just deleting old logs)
        """
        try:
            log_dir = self._workspace / ".opus_state" / "logs"
            if not log_dir.exists():
                return None

            # Count log files older than 7 days
            cutoff = datetime.utcnow() - timedelta(days=7)
            old_logs = []

            for log_file in log_dir.glob("*.log"):
                mtime = datetime.fromtimestamp(log_file.stat().st_mtime)
                if mtime < cutoff:
                    old_logs.append(log_file.name)

            if len(old_logs) >= 5:
                return Intent(
                    id=self._next_intent_id(),
                    intent_type="cleanup_old_logs",
                    title=f"Clean up {len(old_logs)} old log files",
                    description=f"Found {len(old_logs)} log files older than 7 days in .opus_state/logs/",
                    reasoning="Old log files consume disk space and are rarely needed after a week.",
                    priority=IntentPriority.LOW,
                    risk=IntentRisk.SAFE,  # Safe to auto-execute
                    params={"log_files": old_logs},
                    auto_executable=True,  # Can run without approval!
                    expires_at=(datetime.utcnow() + timedelta(days=3)).isoformat(),
                )

        except Exception as e:
            logger.debug(f"Log cleanup analysis failed: {e}")

        return None

    # =========================================================================
    # 🧠 SEMANTIC ANALYZER (Level 2)
    # =========================================================================

    async def _analyze_semantic_opportunities(self, context: Dict[str, Any]) -> List[Intent]:
        """
        Use Semantic Engine to find hidden connections (Weaving).
        """
        intents = []
        if not self._semantic_engine:
            return []

        # Example: Analyze recent errors for semantic concepts
        errors = context.get("recent_errors", [])
        for error in errors[:2]:  # Check top 2 errors
            msg = error.get("message", "")
            if len(msg) < 10:
                continue

            try:
                # 🧠 ASYNC SEMANTIC ANALYSIS
                concepts = await self._semantic_engine.analyze(msg)

                # Filter high confidence concepts (> 0.6)
                relevant = [c for c in concepts if c.confidence > 0.6]

                if relevant:
                    concept_names = ", ".join([c.name for c in relevant[:3]])

                    intents.append(
                        Intent(
                            id=self._next_intent_id(),
                            intent_type="semantic_weaving",
                            title=f"🧠 Weave: Connect error to {concept_names}",
                            description=f"Semantic Engine detected concepts {concept_names} in error: '{msg[:50]}...'. This suggests a conceptual gap.",
                            reasoning="Intelligent error analysis found underlying concepts that need attention.",
                            priority=IntentPriority.MEDIUM,
                            risk=IntentRisk.LOW,
                            params={"error": msg, "concepts": [c.name for c in relevant]},
                            auto_executable=False,
                        )
                    )
            except Exception as e:
                logger.warning(f"Semantic analyze failed for error: {e}")

        return intents

    # =========================================================================
    # OPUS-032: Self-Documentation Analyzers
    # =========================================================================

    def _analyze_readme_staleness(self, context: Dict[str, Any]) -> Optional[Intent]:
        """
        Check if README.md is stale (many commits since last update).

        Risk: MEDIUM (modifying docs requires review)

        The Auto-Biographer: Suggests updating README when it falls behind.
        """
        try:
            readme_path = self._workspace / "README.md"
            if not readme_path.exists():
                return None

            # Get commits since README was last modified
            result = subprocess.run(
                ["git", "log", "--oneline", "--", "README.md"],
                capture_output=True,
                text=True,
                timeout=10,
                cwd=str(self._workspace),
            )

            if result.returncode != 0:
                return None

            readme_commits = len([l for l in result.stdout.strip().split("\n") if l])

            # Get total recent commits
            result = subprocess.run(
                ["git", "rev-list", "--count", "HEAD"],
                capture_output=True,
                text=True,
                timeout=10,
                cwd=str(self._workspace),
            )

            if result.returncode != 0:
                return None

            total_commits = int(result.stdout.strip())

            # Get last README commit
            result = subprocess.run(
                ["git", "log", "-1", "--format=%H", "--", "README.md"],
                capture_output=True,
                text=True,
                timeout=10,
                cwd=str(self._workspace),
            )

            if result.returncode != 0 or not result.stdout.strip():
                return None

            last_readme_sha = result.stdout.strip()

            # Count commits since README was updated
            result = subprocess.run(
                ["git", "rev-list", "--count", f"{last_readme_sha}..HEAD"],
                capture_output=True,
                text=True,
                timeout=10,
                cwd=str(self._workspace),
            )

            if result.returncode != 0:
                return None

            commits_since_readme = int(result.stdout.strip())

            # If more than 30 commits since README update, suggest refresh
            if commits_since_readme >= 30:
                return Intent(
                    id=self._next_intent_id(),
                    intent_type="update_readme",
                    title=f"Update README.md ({commits_since_readme} commits behind)",
                    description=f"README.md hasn't been updated in {commits_since_readme} commits. It may be out of sync with the current codebase.",
                    reasoning="Documentation drift causes onboarding friction and confusion. Regular README updates keep the project accessible.",
                    priority=IntentPriority.MEDIUM,
                    risk=IntentRisk.MEDIUM,
                    params={
                        "commits_since_update": commits_since_readme,
                        "total_commits": total_commits,
                        "readme_commits": readme_commits,
                    },
                    auto_executable=False,  # Needs human review
                )

        except Exception as e:
            logger.debug(f"README staleness analysis failed: {e}")

        return None

    def _analyze_self_documentation(self, context: Dict[str, Any]) -> Optional[Intent]:
        """
        Check if opus_assistant's own documentation needs updating.

        Risk: LOW (self-documenting is safe)

        The Self-Aware System: Knows when its own docs are stale.
        """
        try:
            # Check OPUS.md age vs plugin changes
            opus_md = self._workspace / "OPUS.md"
            plugin_dir = self._workspace / "vibe_core" / "plugins" / "opus_assistant"

            if not opus_md.exists() or not plugin_dir.exists():
                return None

            # Get OPUS.md last modified time
            opus_mtime = opus_md.stat().st_mtime

            # Find most recent plugin file modification
            latest_plugin_mtime = 0
            changed_files = []

            for py_file in plugin_dir.glob("**/*.py"):
                if "__pycache__" in str(py_file):
                    continue
                mtime = py_file.stat().st_mtime
                if mtime > latest_plugin_mtime:
                    latest_plugin_mtime = mtime
                if mtime > opus_mtime:
                    changed_files.append(py_file.name)

            # If plugin files are newer than OPUS.md by more than 1 hour
            time_diff_hours = (latest_plugin_mtime - opus_mtime) / 3600

            if time_diff_hours > 1 and len(changed_files) >= 3:
                return Intent(
                    id=self._next_intent_id(),
                    intent_type="update_opus_documentation",
                    title=f"Update OPUS.md ({len(changed_files)} files changed)",
                    description=f"OPUS.md may be outdated. {len(changed_files)} plugin files have been modified since last OPUS.md update.",
                    reasoning="Self-documentation ensures the system's capabilities are accurately reflected in its dashboard.",
                    priority=IntentPriority.LOW,
                    risk=IntentRisk.SAFE,
                    params={
                        "changed_files": changed_files[:10],
                        "hours_behind": round(time_diff_hours, 1),
                    },
                    auto_executable=False,
                )

            # Check if MANAS itself has new capabilities not in OPUS.md
            manas_dir = plugin_dir / "manas"
            if manas_dir.exists():
                # Read OPUS.md content
                opus_content = opus_md.read_text()

                # Check if MANAS is mentioned
                if "MANAS" not in opus_content and "manas" not in opus_content.lower():
                    return Intent(
                        id=self._next_intent_id(),
                        intent_type="document_manas",
                        title="Document MANAS cognitive kernel in OPUS.md",
                        description="MANAS (the cognitive kernel) exists but is not documented in OPUS.md.",
                        reasoning="New capabilities should be documented so users know they exist.",
                        priority=IntentPriority.MEDIUM,
                        risk=IntentRisk.SAFE,
                        params={"feature": "MANAS", "location": "vibe_core/plugins/opus_assistant/manas/"},
                        auto_executable=False,
                    )

        except Exception as e:
            logger.debug(f"Self-documentation analysis failed: {e}")

        return None

    def _analyze_capability_gaps(self, context: Dict[str, Any]) -> Optional[Intent]:
        """
        🐍 OUROBOROS: Detect missing capabilities and propose generation.

        Risk: HIGH (code generation requires human approval)

        This is THE SINGULARITY - the system proposing to evolve itself.

        Triggers:
        - Context contains 'capability_missing' error
        - Error logs mention 'unknown syscall'
        - Recent failure patterns suggest missing tools
        """
        try:
            # Check context for capability missing signals
            errors = context.get("recent_errors", [])
            missing_cap = None
            missing_description = None

            for error in errors:
                error_msg = str(error.get("message", "")).lower()
                error_type = error.get("type", "")

                # Pattern 1: Unknown syscall
                if "unknown syscall" in error_msg:
                    import re

                    match = re.search(r"unknown syscall[:\s]+['\"]?(\w+)['\"]?", error_msg, re.I)
                    if match:
                        missing_cap = match.group(1).lower()
                        missing_description = f"Syscall '{missing_cap}' was requested but not found"
                        break

                # Pattern 2: Capability not found
                if "capability not found" in error_msg or "no handler for" in error_msg:
                    import re

                    match = re.search(r"(?:capability|handler)[:\s]+['\"]?(\w+)['\"]?", error_msg, re.I)
                    if match:
                        missing_cap = match.group(1).lower()
                        missing_description = f"Capability '{missing_cap}' was needed but unavailable"
                        break

                # Pattern 3: KeyError in syscall registry
                if error_type == "KeyError" and "syscall" in error_msg:
                    import re

                    match = re.search(r"['\"](\w+)['\"]", error_msg)
                    if match:
                        missing_cap = match.group(1).lower()
                        missing_description = f"Syscall '{missing_cap}' not in registry"
                        break

            if not missing_cap:
                # Also check context for explicit capability request
                missing_cap = context.get("requested_capability")
                missing_description = context.get("capability_description", "User requested new capability")

            if not missing_cap:
                return None

            # Check memory - have we recently been rejected for this?
            if self._memory:
                if self._memory.was_recently_rejected(f"genesis_{missing_cap}", hours=72):
                    logger.debug(f"Skipping genesis_{missing_cap} - recently rejected")
                    return None

            return Intent(
                id=self._next_intent_id(),
                intent_type=f"genesis_{missing_cap}",
                title=f"🐍 Generate capability: {missing_cap}",
                description=f"The Ouroboros Protocol can generate this missing capability. {missing_description}",
                reasoning="System evolution through capability synthesis. The serpent eats its tail to grow.",
                priority=IntentPriority.HIGH,
                risk=IntentRisk.HIGH,
                params={
                    "capability_name": missing_cap,
                    "capability_type": "syscall",
                    "description": missing_description,
                    "syscall_name": missing_cap.upper(),
                },
                auto_executable=False,  # NEVER auto-execute code generation
                circuit_to_execute="vibe_core/plugins/opus_assistant/circuits/capability_genesis.yaml",
            )

        except Exception as e:
            logger.debug(f"Capability gap analysis failed: {e}")

        return None
