"""
Operations Renderer.
Renders OPERATIONS.md (Dashboard) via kernel.io.
"""

import logging
from typing import TYPE_CHECKING

from vibe_core.io_service import DocumentType

from .base import BaseRenderer

if TYPE_CHECKING:
    from vibe_core.kernel_impl import RealVibeKernel

logger = logging.getLogger("RENDERER_OPERATIONS")


class OperationsRenderer(BaseRenderer):
    """Renders OPERATIONS.md dashboard."""

    def __init__(self, kernel: "RealVibeKernel"):
        super().__init__(kernel)

    @property
    def name(self) -> str:
        return "operations"

    def render(self) -> None:
        """Render OPERATIONS.md from live kernel state."""
        try:
            content = self._generate_content()
            self.kernel.io.write_document(
                name="OPERATIONS.md",
                content=content,
                doc_type=DocumentType.READONLY,
                writer_id="interface_plugin",
                add_header=True,
            )
        except Exception as e:
            logger.error(f"Error rendering OPERATIONS.md: {e}")

    def _generate_content(self) -> str:
        """Generate markdown content from live kernel state."""
        lines = ["# OPERATIONS DASHBOARD", ""]

        # Kernel Status
        status = self.kernel.status.value if hasattr(self.kernel, "status") else "UNKNOWN"
        agent_count = len(self.kernel.agent_registry)
        queue_size = self.kernel.scheduler.queue_size() if hasattr(self.kernel, "scheduler") else 0

        lines.extend(
            [
                "## Kernel Status",
                "",
                f"- **Status:** `{status}`",
                f"- **Agents Registered:** {agent_count}",
                f"- **Queue Length:** {queue_size}",
                "",
            ]
        )

        # Agent Status
        lines.extend(["## Agent Status", ""])

        if not self.kernel.agent_registry:
            lines.append("_No agents registered_")
        else:
            lines.append("| Agent ID | Name | Domain | Status |")
            lines.append("| :--- | :--- | :--- | :--- |")
            for agent_id, agent in sorted(self.kernel.agent_registry.items()):
                name = getattr(agent, "name", agent_id)
                domain = getattr(agent, "domain", "UNKNOWN")
                lines.append(f"| `{agent_id}` | {name} | {domain} | ACTIVE |")

        lines.extend(["", "---", "*Auto-generated by InterfacePlugin*"])

        return "\n".join(lines)
