"""
Proof Renderer.
Placeholder for verification proofs.
"""

from .base import BaseRenderer


class ProofRenderer(BaseRenderer):
    @property
    def name(self) -> str:
        return "proof"

    def render(self) -> None:
        # PROOF.md is usually generated by verification scripts.
        # We don't auto-generate it here to avoid overwriting valid proofs.
        pass
