"""
OPUS-158: InfrastructureGenerator

Generate GAD-000 compliant infrastructure files.

The Stadtamt - creates mailboxes for every house:
- __init__.py for discoverability
- manifest.json for capabilities
- Base class stubs for composability

Sanskrit: उत्पत्ति (Utpatti) = Genesis/Origin
"""

import json
import logging
from dataclasses import dataclass, field
from datetime import datetime
from pathlib import Path
from string import Template
from typing import Dict, List, Optional

from .classifier import ModuleType

logger = logging.getLogger("MANAS.GENESIS.GENERATOR")


@dataclass
class GenerationResult:
    """Result of infrastructure generation."""

    path: Path
    module_type: ModuleType
    created_files: Dict[str, Path] = field(default_factory=dict)
    skipped_files: List[str] = field(default_factory=list)
    errors: List[str] = field(default_factory=list)

    @property
    def success(self) -> bool:
        """True if no errors occurred."""
        return len(self.errors) == 0

    @property
    def files_created_count(self) -> int:
        """Number of files created."""
        return len(self.created_files)


class InfrastructureGenerator:
    """
    Generate GAD-000 compliant infrastructure files.

    The second step in the Agent Virus loop:
        DETECT -> CLASSIFY -> GENERATE -> WIRE -> REPLICATE
                              ^^^^^^^^

    Creates:
    - __init__.py with proper exports
    - manifest.json with GAD-000 structure
    - Base class stubs with required methods
    """

    def __init__(
        self,
        workspace: Path,
        templates_dir: Optional[Path] = None,
        dry_run: bool = False,
    ):
        """
        Initialize generator.

        Args:
            workspace: Workspace root path
            templates_dir: Custom templates directory (optional)
            dry_run: If True, don't write files (for testing)
        """
        self._workspace = workspace
        self._templates_dir = templates_dir or self._get_default_templates()
        self._dry_run = dry_run

    def generate(self, path: Path, module_type: ModuleType) -> GenerationResult:
        """
        Generate infrastructure files for a module.

        Args:
            path: Path to the new module directory
            module_type: Type of module (from classifier)

        Returns:
            GenerationResult with details of what was created
        """
        result = GenerationResult(path=path, module_type=module_type)

        if module_type == ModuleType.UNKNOWN:
            result.errors.append("Cannot generate infrastructure for UNKNOWN type")
            return result

        generators = {
            ModuleType.PLUGIN: self._generate_plugin,
            ModuleType.ANALYZER: self._generate_analyzer,
            ModuleType.SENSE: self._generate_sense,
            ModuleType.ACTION: self._generate_action,
            ModuleType.SECTION: self._generate_section,
            ModuleType.KNOWLEDGE: self._generate_knowledge,
        }

        generator = generators.get(module_type)
        if generator:
            try:
                generator(path, result)
            except Exception as e:
                result.errors.append(f"Generation failed: {e}")
                logger.error(f"Infrastructure generation failed for {path}: {e}")
        else:
            result.skipped_files.append("No generator for this type")

        return result

    def _generate_plugin(self, path: Path, result: GenerationResult) -> None:
        """Generate plugin infrastructure."""
        name = path.name

        # __init__.py
        init_content = f'''"""
{name.replace("_", " ").title()} Plugin

Auto-generated by InfrastructureGenesis (OPUS-158).
"""

from .plugin_main import {self._to_class_name(name)}Plugin

__all__ = ["{self._to_class_name(name)}Plugin"]
'''
        self._write_if_missing(path / "__init__.py", init_content, result)

        # manifest.json
        manifest = {
            "type": "plugin",
            "id": name,
            "name": name.replace("_", " ").title(),
            "version": "0.1.0",
            "description": f"Plugin: {name}",
            "entry_point": "plugin_main.py",
            "entry_class": f"{self._to_class_name(name)}Plugin",
            "priority": 50,
            "enabled": True,
            "hooks": [],
            "capabilities": [],
            "dependencies": [],
            "author": "InfrastructureGenesis",
            "generated_at": datetime.now().isoformat(),
        }
        self._write_json_if_missing(path / "manifest.json", manifest, result)

        # plugin_main.py
        plugin_content = f'''"""
{name.replace("_", " ").title()} Plugin Main

Auto-generated by InfrastructureGenesis (OPUS-158).
"""

import logging
from pathlib import Path
from typing import Any, Dict, Optional

logger = logging.getLogger("PLUGIN.{name.upper()}")


class {self._to_class_name(name)}Plugin:
    """
    {name.replace("_", " ").title()} Plugin.

    TODO: Add plugin description.
    """

    def __init__(self, kernel: Any = None, config: Optional[Dict] = None):
        """Initialize plugin."""
        self._kernel = kernel
        self._config = config or {{}}
        self._workspace = Path.cwd()
        logger.info(f"{{self.__class__.__name__}} initialized")

    async def on_boot(self) -> None:
        """Called when plugin boots."""
        pass

    async def on_shutdown(self) -> None:
        """Called when plugin shuts down."""
        pass
'''
        self._write_if_missing(path / "plugin_main.py", plugin_content, result)

    def _generate_analyzer(self, path: Path, result: GenerationResult) -> None:
        """Generate analyzer stub inheriting BaseAnalyzer."""
        # Only for directories - create a stub analyzer
        if path.is_dir():
            name = path.name
            analyzer_name = f"{name}_analyzer"
            file_path = path / f"{analyzer_name}.py"

            content = f'''"""
{name.replace("_", " ").title()} Analyzer

Auto-generated by InfrastructureGenesis (OPUS-158).
"""

from typing import Any, Dict, List, Optional

from .base import BaseAnalyzer


class {self._to_class_name(name)}Analyzer(BaseAnalyzer):
    """
    {name.replace("_", " ").title()} Analyzer.

    TODO: Add description.
    """

    name = "{analyzer_name}"

    def analyze(self, context: Optional[Dict[str, Any]] = None) -> List[Any]:
        """
        Analyze and generate intents.

        Args:
            context: Analysis context

        Returns:
            List of intents generated
        """
        # TODO: Implement analysis logic
        return []
'''
            self._write_if_missing(file_path, content, result)

    def _generate_sense(self, path: Path, result: GenerationResult) -> None:
        """Generate sense stub inheriting BaseSense."""
        if path.is_dir():
            name = path.name
            sense_name = f"{name}_sense"
            file_path = path / f"{sense_name}.py"

            content = f'''"""
{name.replace("_", " ").title()} Sense

Auto-generated by InfrastructureGenesis (OPUS-158).

Sanskrit: इन्द्रिय (Indriya) = Sense organ
"""

from pathlib import Path
from typing import Any, Dict, Optional

from .base import BaseSense


class {self._to_class_name(name)}Sense(BaseSense):
    """
    {name.replace("_", " ").title()} Sense - A Jnanendriya.

    TODO: Add description of what this sense perceives.
    """

    name = "{sense_name}"

    def perceive(self, context: Optional[Dict[str, Any]] = None) -> Dict[str, Any]:
        """
        Perceive the environment.

        Args:
            context: Perception context

        Returns:
            Dict with perception results
        """
        # TODO: Implement perception logic
        return {{
            "sense": self.name,
            "perceived": True,
        }}
'''
            self._write_if_missing(file_path, content, result)

    def _generate_action(self, path: Path, result: GenerationResult) -> None:
        """Generate action stub inheriting BaseAction."""
        if path.is_dir():
            name = path.name
            action_name = f"{name}_action"
            file_path = path / f"{action_name}.py"

            content = f'''"""
{name.replace("_", " ").title()} Action

Auto-generated by InfrastructureGenesis (OPUS-158).

Sanskrit: कर्मेन्द्रिय (Karmendriya) = Action organ
"""

from pathlib import Path
from typing import Any, Dict, Optional, Set

from .base_action import ActionResult, BaseAction


class {self._to_class_name(name)}Action(BaseAction):
    """
    {name.replace("_", " ").title()} Action - A Karmendriya.

    TODO: Add description of what this action does.
    """

    name = "{action_name}"

    # Intent types this action can handle
    handled_intent_types: Set[str] = {{
        # TODO: Add intent types this action handles
        # e.g., "do_something", "do_other_thing"
    }}

    def act(self, intent: Any) -> ActionResult:
        """
        Execute an intent.

        Args:
            intent: The intent to execute

        Returns:
            ActionResult with execution details
        """
        # TODO: Implement action logic
        return ActionResult(
            success=False,
            action_name=self.name,
            intent_type=getattr(intent, "intent_type", "unknown"),
            error="Not implemented",
        )
'''
            self._write_if_missing(file_path, content, result)

    def _generate_section(self, path: Path, result: GenerationResult) -> None:
        """Generate phoenix section manifest."""
        name = path.name

        manifest = {
            "type": "phoenix_section",
            "id": name,
            "name": name.replace("_", " ").title(),
            "version": "0.1.0",
            "description": f"Phoenix config section: {name}",
            "schema_file": "schema.json",
            "default_file": "defaults.yaml",
            "generated_at": datetime.now().isoformat(),
        }
        self._write_json_if_missing(path / "manifest.json", manifest, result)

    def _generate_knowledge(self, path: Path, result: GenerationResult) -> None:
        """Generate knowledge base manifest."""
        name = path.name

        manifest = {
            "type": "knowledge",
            "id": name,
            "name": name.replace("_", " ").title(),
            "version": "0.1.0",
            "description": f"Knowledge base: {name}",
            "format": "yaml",
            "generated_at": datetime.now().isoformat(),
        }
        self._write_json_if_missing(path / "manifest.json", manifest, result)

    def _write_if_missing(self, path: Path, content: str, result: GenerationResult) -> bool:
        """Write file if it doesn't exist."""
        if path.exists():
            result.skipped_files.append(str(path.name))
            return False

        if not self._dry_run:
            # Ensure parent directory exists
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content)
            logger.info(f"Created: {path}")

        result.created_files[path.name] = path
        return True

    def _write_json_if_missing(self, path: Path, data: Dict, result: GenerationResult) -> bool:
        """Write JSON file if it doesn't exist."""
        content = json.dumps(data, indent=2)
        return self._write_if_missing(path, content, result)

    def _to_class_name(self, name: str) -> str:
        """Convert snake_case to PascalCase."""
        return "".join(word.title() for word in name.split("_"))

    def _get_default_templates(self) -> Path:
        """Get default templates directory."""
        return Path(__file__).parent / "templates"

    def _load_template(self, template_path: str, context: Dict) -> str:
        """Load and render a template."""
        full_path = self._templates_dir / template_path
        if full_path.exists():
            template = Template(full_path.read_text())
            return template.safe_substitute(context)
        return ""
