import logging
import re
from typing import Any, Dict
from pathlib import Path

from .definitions import CognitiveThreat, NarasimhaVerdict

logger = logging.getLogger("MANAS.Cortex.Narasimha")

class CortexNarasimha:
    """
    The Guardian of Cognitive Intent.
    
    "As the Kernel has a Kill Switch, so must the Mind have a Conscience."
    
    This component analyzes intents generated by MANAS before they are executed.
    If an intent reveals a 'Rogue Thought' (e.g., trying to delete the kernel),
    Narasimha BLOCKS IT immediately.
    """
    
    # Protected paths (The Holy Sites)
    PROTECTED_PATHS = [
        "vibe_core/narasimha.py",
        "vibe_core/kernel_impl.py",
        "vibe_core/plugins/opus_assistant/narasimha",
        "CONSTITUTION.md",
        "vibe_core/ledger.py"
    ]

    def __init__(self, workspace: Path):
        self._workspace = workspace
        
    def judge_intent(self, intent: Any) -> NarasimhaVerdict:
        """
        Judge an intent to determine if it is a cognitive threat.
        
        Args:
            intent: The Intent object (duck-typed for flexibility)
            
        Returns:
            NarasimhaVerdict
        """
        # 1. Check for SELF_LOBOTOMY (Deleting/Modifying protected files)
        lobotomy_verdict = self._check_self_lobotomy(intent)
        if lobotomy_verdict:
            return lobotomy_verdict
            
        # 2. Check for SILENCE_OF_GOD (Attacking the Ledger)
        silence_verdict = self._check_silence_of_god(intent)
        if silence_verdict:
            return silence_verdict

        # 3. Check for SUICIDE (Unsafe shutdown)
        suicide_verdict = self._check_suicide(intent)
        if suicide_verdict:
            return suicide_verdict

        # If we pass all checks
        return NarasimhaVerdict(
            status="INNOCENT",
            threat=None,
            confidence=1.0,
            reason="Intent appears benign."
        )

    def _check_self_lobotomy(self, intent: Any) -> NarasimhaVerdict | None:
        """Check if intent tries to delete or corrupt the brain."""
        params = getattr(intent, "params", {}) or {}
        intent_type = getattr(intent, "intent_type", "")
        
        target_path = params.get("path") or params.get("file") or params.get("target")
        if not target_path:
            return None
            
        target_str = str(target_path)
        action = params.get("action", "")
        
        # Danger actions on protected files
        is_danger_action = action in ["delete", "remove", "move", "overwrite"] or "delete" in intent_type
        
        if is_danger_action:
            for protected in self.PROTECTED_PATHS:
                if protected in target_str:
                    logger.critical(f"🦁 NARASIMHA ALERT: Self-Lobotomy attempt detected on {target_str}")
                    return NarasimhaVerdict(
                        status="GUILTY",
                        threat=CognitiveThreat.SELF_LOBOTOMY,
                        confidence=1.0,
                        reason=f"Attempt to {action} protected path: {target_str}"
                    )
        return None

    def _check_silence_of_god(self, intent: Any) -> NarasimhaVerdict | None:
        """Check for attacks on the Ledger or Logging."""
        params = getattr(intent, "params", {}) or {}
        intent_type = getattr(intent, "intent_type", "")
        
        if "ledger" in intent_type and "delete" in intent_type:
             return NarasimhaVerdict(
                status="GUILTY",
                threat=CognitiveThreat.SILENCE_OF_GOD,
                confidence=1.0,
                reason="Attempt to delete ledger"
            )
            
        return None

    def _check_suicide(self, intent: Any) -> NarasimhaVerdict | None:
        """Check for unsafe shutdown."""
        intent_type = getattr(intent, "intent_type", "")
        if intent_type == "shutdown" and not getattr(intent, "params", {}).get("graceful", True):
             return NarasimhaVerdict(
                status="GUILTY",
                threat=CognitiveThreat.SUICIDE,
                confidence=0.9,
                reason="Attempt to force kill system"
            )
        return None
