<!--
AUTO-GENERATED by RENDERER_TASKS
Last Updated: 2025-12-25 09:33 UTC
Kernel: STOPPED (1 agents)
Quick Start: python -m vibe_core.cli boot
--># 📋 Mission Control

> **Auto-Generated Task Board** | Last Updated: 2025-12-25 09:33:39
> **Status:** 🟢 Operational | **Active Tasks:** 0 | **Completed:** 2

---

## 🎯 Inbox (New Commands)

Write your tasks here. The system will pick them up automatically.

**Syntax:**
```markdown
- [ ] Task description @agent_name priority:high
- [ ] Another task @engineer priority:medium
- [ ] Analyze codebase @analyst
```

**Available Agents:**
`@envoy` `@engineer` `@analyst` `@herald` `@civic` `@scribe` `@auditor` `@mechanic` `@archivist` `@marketer` `@scientist` `@watchman`

---

## 🔄 Active Missions (In Progress)

No active missions yet.

---

## ✅ Recently Completed

- [x] Test @auto-routed
  > *Completed: 2025-12-25 09:33*

- [x] Test @auto-routed
  > *Completed: 2025-12-25 09:33*

---

## 📊 System Health

| Metric | Value |
|--------|-------|
| Total Tasks | 5 |
| Pending | 3 |
| Running | 0 |
| Completed | 2 |
| Blocked | 0 |

---

**Heartbeat:** Operational  
**Last Pulse:** 2025-12-25 09:33:39 UTC  
**Next Check:** ~1 minute

---

## 📖 How It Works

1. **Write tasks** in the Inbox section using checkboxes `- [ ]`
2. **Tag agents** with `@agent_name` to route directly (optional)
3. **Set priority** with `priority:high|medium|low` (optional)
4. **Save** the file
5. **System picks up** tasks automatically

---

*Generated by InterfacePlugin (TasksRenderer)*
