"""
ENGINEER Builder Tool - Scaffolding and Code Generation.

Capabilities:
- Scaffold new agent directory structure
- Generate cartridge code via LLM
"""

import os
import logging
from pathlib import Path
from typing import Dict, Any, Optional

# Reuse Herald's ContentTool for LLM access if available, 
# otherwise we might need a direct client.
# For simplicity and consistency, we'll use the same pattern as ContentTool
# but tailored for code generation.
try:
    from openai import OpenAI
except ImportError:
    OpenAI = None

logger = logging.getLogger("ENGINEER_BUILDER")

class BuilderTool:
    """
    The Engineer's toolbox for creating new agents.
    """

    def __init__(self):
        """Initialize builder tool."""
        self.client = None
        
        # Try to initialize OpenAI client (using OpenRouter/Tavily keys from env)
        api_key = os.environ.get("OPENROUTER_API_KEY")
        base_url = "https://openrouter.ai/api/v1"
        
        if api_key and OpenAI:
            self.client = OpenAI(api_key=api_key, base_url=base_url)
            logger.info("✅ Builder Tool initialized with LLM access")
        else:
            logger.warning("⚠️  Builder Tool: No API key or OpenAI lib found. Code generation disabled.")

    def scaffold_agent(self, name: str) -> bool:
        """
        Create directory structure for a new agent.
        
        Args:
            name: Agent name (e.g., 'weather')
            
        Returns:
            bool: True if successful
        """
        try:
            base_path = Path(name)
            tools_path = base_path / "tools"
            
            if base_path.exists():
                logger.warning(f"⚠️  Agent directory '{name}' already exists.")
                return False
                
            base_path.mkdir(parents=True)
            tools_path.mkdir(parents=True)
            
            # Create __init__.py files
            (base_path / "__init__.py").touch()
            (tools_path / "__init__.py").touch()
            
            logger.info(f"🏗️  Scaffolded agent structure for '{name}'")
            return True
            
        except Exception as e:
            logger.error(f"❌ Scaffold failed: {e}")
            return False

    def generate_agent_code(self, name: str, mission: str) -> Optional[str]:
        """
        Generate the cartridge code for a new agent.
        
        Args:
            name: Agent name
            mission: Description of what the agent does
            
        Returns:
            str: Generated Python code or None
        """
        if not self.client:
            return self._fallback_template(name, mission)

        prompt = (
            f"You are THE ENGINEER, a meta-agent that builds other autonomous agents.\n"
            f"TASK: Write the Python code for a new agent named '{name}'.\n"
            f"MISSION: {mission}\n\n"
            f"REQUIREMENTS:\n"
            f"1. Class name: {name.capitalize()}Cartridge\n"
            f"2. Must have a 'run()' method.\n"
            f"3. Must use standard logging.\n"
            f"4. Return ONLY the Python code, no markdown formatting.\n"
            f"5. Include a docstring explaining the agent's role.\n"
        )

        try:
            logger.info(f"🧠 Generating code for '{name}'...")
            response = self.client.chat.completions.create(
                model="anthropic/claude-3-haiku", # Fast & Good for code
                messages=[{"role": "user", "content": prompt}],
                max_tokens=1000,
                temperature=0.2
            )
            
            code = response.choices[0].message.content.strip()
            
            # Strip markdown code blocks if present
            if code.startswith("```python"):
                code = code.replace("```python", "").replace("```", "")
            elif code.startswith("```"):
                code = code.replace("```", "")
                
            return code.strip()

        except Exception as e:
            logger.error(f"❌ Code generation failed: {e}")
            return self._fallback_template(name, mission)

    def _fallback_template(self, name: str, mission: str) -> str:
        """Return a basic template if LLM fails."""
        class_name = f"{name.capitalize()}Cartridge"
        return f"""
import logging

logger = logging.getLogger("{name.upper()}_AGENT")

class {class_name}:
    \"\"\"
    Agent: {name}
    Mission: {mission}
    Generated by: The Engineer (Fallback Mode)
    \"\"\"

    def __init__(self):
        logger.info("{name} is online.")

    def run(self):
        logger.info("{name} is running its mission: {mission}")
        return {{"status": "success", "message": "{name} executed successfully"}}
"""
