"""
OPUS-096: RuntimeStateDefinition - Single Source of Truth for Runtime State

This module defines what constitutes "runtime state" (machine-generated files)
vs "source code" (human-written files) in the steward-protocol.

Runtime state:
- Should be COMMITTED (not .gitignore'd) per OPUS-061 lobotomy prevention
- Should be IGNORED by stop-hook (no exit-blocking)
- Should be committed with no_verify (skip pre-commit hooks)

Source code:
- Must be committed before session exit
- Pre-commit hooks apply
- Human authored content

This replaces fragmented definitions in:
- manifest.json generated_outputs
- git_state._get_runtime_state_patterns()
- heartbeat.runtime_files
- sync_holon conventions
"""

from dataclasses import dataclass, field
from fnmatch import fnmatch
from pathlib import Path
from typing import ClassVar, Dict, List, Set


@dataclass
class RuntimeStateDefinition:
    """
    Canonical definition of what constitutes "runtime state".

    ONE SOURCE OF TRUTH for all runtime state classification.

    Usage:
        definition = RuntimeStateDefinition.with_plugin_patterns(plugin_patterns)
        if definition.is_runtime_state("OPUS.md"):
            # This is machine-generated, ignore in stop-hook
    """

    # =========================================================================
    # CORE PATTERNS - Always runtime state (Mutterschiff-level)
    # =========================================================================

    # These are ALWAYS considered runtime state, regardless of plugin manifests
    CORE_PATTERNS: ClassVar[List[str]] = [
        # Prakriti state directory (session tracking, snapshots)
        ".prakriti/*",
        ".prakriti/**/*",
        # OPUS assistant cognitive state
        ".opus_state/*",
        ".opus_state/**/*",
        # VIBE snapshot files
        "*.vibe",
        "vibe_snapshot.json",
        # Dashboard files (generated by interface plugin)
        "OPUS.md",
        "ENVOY.md",
        "AGENTS.md",
        # Session lock files
        "*.lock",
        # Temporary/working files
        "*.tmp",
        "*.bak",
    ]

    # =========================================================================
    # PLUGIN PATTERNS - Discovered from manifests
    # =========================================================================

    # Patterns declared by plugins via manifest.json generated_outputs
    plugin_patterns: Dict[str, List[str]] = field(default_factory=dict)

    # =========================================================================
    # CACHED PATTERNS (computed once for performance)
    # =========================================================================

    _all_patterns: List[str] = field(default_factory=list, repr=False)

    def __post_init__(self):
        """Compute cached patterns after initialization."""
        self._rebuild_pattern_cache()

    def _rebuild_pattern_cache(self) -> None:
        """Rebuild the combined pattern cache."""
        patterns = set(self.CORE_PATTERNS)

        # Add all plugin patterns
        for plugin_name, plugin_pats in self.plugin_patterns.items():
            patterns.update(plugin_pats)

        self._all_patterns = list(patterns)

    # =========================================================================
    # PUBLIC API
    # =========================================================================

    def is_runtime_state(self, path: str | Path) -> bool:
        """
        Is this path runtime state (not source code)?

        Args:
            path: File path (relative or absolute)

        Returns:
            True if this is runtime state (machine-generated)
            False if this is source code (human-written)
        """
        path_str = str(path)

        for pattern in self._all_patterns:
            if fnmatch(path_str, pattern):
                return True
            # Also check basename for simple patterns like "OPUS.md"
            if fnmatch(Path(path_str).name, pattern):
                return True

        return False

    def is_source_code(self, path: str | Path) -> bool:
        """Inverse of is_runtime_state for readability."""
        return not self.is_runtime_state(path)

    def filter_runtime_files(self, paths: List[str]) -> List[str]:
        """Filter a list of paths to only runtime state files."""
        return [p for p in paths if self.is_runtime_state(p)]

    def filter_source_files(self, paths: List[str]) -> List[str]:
        """Filter a list of paths to only source code files."""
        return [p for p in paths if self.is_source_code(p)]

    def get_all_patterns(self) -> List[str]:
        """Get all runtime state patterns (core + plugin)."""
        return list(self._all_patterns)

    def add_plugin_patterns(self, plugin_name: str, patterns: List[str]) -> None:
        """Add patterns for a plugin dynamically."""
        self.plugin_patterns[plugin_name] = patterns
        self._rebuild_pattern_cache()

    # =========================================================================
    # FACTORY METHODS
    # =========================================================================

    @classmethod
    def core_only(cls) -> "RuntimeStateDefinition":
        """Create definition with only core patterns (no plugins)."""
        return cls()

    @classmethod
    def with_plugin_patterns(cls, plugin_patterns: Dict[str, List[str]]) -> "RuntimeStateDefinition":
        """Create definition with plugin patterns included."""
        return cls(plugin_patterns=plugin_patterns)

    @classmethod
    def from_manifests(cls, workspace: Path) -> "RuntimeStateDefinition":
        """
        Discover runtime state patterns from all plugin manifests.

        Args:
            workspace: Repository root path

        Returns:
            RuntimeStateDefinition with discovered patterns
        """
        import glob
        import json

        plugin_patterns: Dict[str, List[str]] = {}

        # Scan Plugin Manifests: vibe_core/plugins/*/manifest.json
        manifest_glob = workspace / "vibe_core" / "plugins" / "*" / "manifest.json"

        for manifest_path in glob.glob(str(manifest_glob)):
            try:
                with open(manifest_path) as f:
                    manifest = json.load(f)

                if "generated_outputs" in manifest:
                    outputs = manifest["generated_outputs"]
                    patterns: List[str] = []

                    # Collect all pattern lists from generated_outputs
                    for key, value in outputs.items():
                        if isinstance(value, list):
                            patterns.extend(value)

                    if patterns:
                        plugin_name = Path(manifest_path).parent.name
                        plugin_patterns[plugin_name] = patterns

            except (json.JSONDecodeError, OSError):
                continue

        return cls(plugin_patterns=plugin_patterns)


# =========================================================================
# SINGLETON ACCESS (for performance)
# =========================================================================

_global_definition: RuntimeStateDefinition | None = None


def get_runtime_state_definition(workspace: Path | None = None) -> RuntimeStateDefinition:
    """
    Get the global RuntimeStateDefinition singleton.

    Lazily initializes from manifests if workspace is provided.
    """
    global _global_definition

    if _global_definition is None:
        if workspace:
            _global_definition = RuntimeStateDefinition.from_manifests(workspace)
        else:
            _global_definition = RuntimeStateDefinition.core_only()

    return _global_definition


def reset_runtime_state_definition() -> None:
    """Reset the global singleton (mainly for testing)."""
    global _global_definition
    _global_definition = None
