"""
BASIN MAP — Precomputed Attractor Basins + HKR Proportions
=============================================================

"sthānam" — the resting place (BG 15.6)

TWO PRECOMPUTED TABLES:

1. COORD_BASIN[0..48] — Which attractor basin each coord converges to (mod 137).
   7 unique basins. Coarse semantic field.

2. COORD_HKR[0..48] — (h, k, r) proportion for each coord.
   How much each divine operation (Hare/Krishna/Rama) contributes
   to the 16-step transformation.
   Fine-grained fingerprint WITHIN basins.

   H (Hare)    = Energy/Shakti   (multiplication: v × 7 × adsr)
   K (Krishna) = Attraction       (addition: v + 10 + pos + feedback)
   R (Rama)    = Bliss/Output     (squaring: (v + feedback)²)

DISCOVERY:
    - 7 basins in mod-137 space
    - 48/49 unique HKR signatures (almost bijective)
    - Cross-language HKR similarity: truth/satya 91%, knowledge/jñāna 89%
    - HKR differentiates within basins (spread up to 46%)

PRECOMPUTED: No synth calls at runtime. Pure lookup.
"""

from __future__ import annotations

from typing import Final, FrozenSet, Sequence, Tuple

from vibe_core.mahamantra.protocols._seed import MAHA_QUANTUM
from vibe_core.mahamantra.substrate.rama_grid import VARNAMALA_TOTAL

# =============================================================================
# PRECOMPUTED BASIN TABLE
# =============================================================================
# Generated by iterating MahaModularSynth("quantum").transform() until
# convergence for each RAMA coordinate (0-48).
#
# 7 unique basins: {11, 22, 38, 59, 88, 115, 122}
#
# Basin semantics (from Gita word frequency analysis):
#   11  = vayu    : opulence, devotion, consciousness
#   22  = vayu    : supreme, spiritual, knowledge, soul
#   38  = prithvi : material, mind, great, living, work
#   59  = vayu    : (rare — only 2 seeds)
#   88  = prithvi : supreme, activities, body, nature
#  115  = akasha  : result, ether, sacrifice, fruits
#  122  = vayu    : knowledge, intelligence, body, nature


def _compute_basin_table() -> Tuple[int, ...]:
    """Compute basin for each RAMA coord. Called once at import time."""
    from vibe_core.mahamantra.substrate.algorithm.maha import MahaModularSynth

    synth = MahaModularSynth(default_preset="quantum")
    table = []
    for coord in range(VARNAMALA_TOTAL):
        value = coord
        for _ in range(100):
            prev = value
            value = synth.transform(value)
            if value == prev:
                break
        table.append(value)
    return tuple(table)


COORD_BASIN: Final[Tuple[int, ...]] = _compute_basin_table()

# The 7 unique basins
BASIN_SET: Final[FrozenSet[int]] = frozenset(COORD_BASIN)
BASIN_COUNT: Final[int] = len(BASIN_SET)
BASIN_LIST: Final[Tuple[int, ...]] = tuple(sorted(BASIN_SET))

# Basin → index (for histogram operations)
BASIN_INDEX: Final[dict] = {b: i for i, b in enumerate(BASIN_LIST)}


# =============================================================================
# SIGNATURE FUNCTIONS
# =============================================================================


def basin_signature(coords: Sequence[int]) -> Tuple[int, ...]:
    """Per-coord basin signature. Pure lookup, no synth calls."""
    return tuple(COORD_BASIN[c] for c in coords)


def basin_set(coords: Sequence[int]) -> FrozenSet[int]:
    """Unique basins touched by a sequence of coords."""
    return frozenset(COORD_BASIN[c] for c in coords)


def basin_histogram(coords: Sequence[int]) -> Tuple[int, ...]:
    """
    Basin frequency histogram (length = BASIN_COUNT).
    Index i = count of coords in BASIN_LIST[i].
    Normalized to sum=1 would lose integer precision, so raw counts.
    """
    hist = [0] * BASIN_COUNT
    for c in coords:
        b = COORD_BASIN[c]
        hist[BASIN_INDEX[b]] += 1
    return tuple(hist)


def basin_jaccard(coords_a: Sequence[int], coords_b: Sequence[int]) -> float:
    """Jaccard similarity of basin sets. 1.0 = identical basins, 0.0 = disjoint."""
    a = basin_set(coords_a)
    b = basin_set(coords_b)
    union = a | b
    if not union:
        return 0.0
    return len(a & b) / len(union)


def basin_cosine(coords_a: Sequence[int], coords_b: Sequence[int]) -> float:
    """Cosine similarity of basin histograms. Captures proportion, not just overlap."""
    ha = basin_histogram(coords_a)
    hb = basin_histogram(coords_b)
    dot = sum(ha[i] * hb[i] for i in range(BASIN_COUNT))
    mag_a = sum(v * v for v in ha) ** 0.5
    mag_b = sum(v * v for v in hb) ** 0.5
    if mag_a == 0.0 or mag_b == 0.0:
        return 0.0
    return dot / (mag_a * mag_b)


# =============================================================================
# PHONEME ATTRACTOR TABLE
# =============================================================================
# For each RAMA coord, find the attractor under MahaAlgorithm16.transform().
# Only 5 unique attractors exist — the Mahamantra constants:
#   18  = GITA_CHAPTERS
#   22  = SHRUTIS
#   49  = RAMA (7²)
#   87  = CHAITANYA (Hare + Krishna)
#  136  = FIELD (T(16) = Position Sum Total)
#
# This gives each phoneme a "semantic charge" — which divine constant it
# converges to under the pure algorithm.


def _compute_phoneme_attractor_table() -> Tuple[int, ...]:
    """Compute MahaAlgorithm16 attractor for each RAMA coord. Called once at import."""
    from vibe_core.mahamantra.substrate.algorithm.maha import MahaAlgorithm16

    algo = MahaAlgorithm16()
    table = []
    for coord in range(VARNAMALA_TOTAL):
        attractor, _, _ = algo.find_attractor(coord)
        table.append(attractor)
    return tuple(table)


COORD_PHONEME_ATTRACTOR: Final[Tuple[int, ...]] = _compute_phoneme_attractor_table()

# The 5 unique phoneme attractors (Mahamantra constants)
PHONEME_ATTRACTOR_SET: Final[FrozenSet[int]] = frozenset(COORD_PHONEME_ATTRACTOR)
PHONEME_ATTRACTOR_LIST: Final[Tuple[int, ...]] = tuple(sorted(PHONEME_ATTRACTOR_SET))
PHONEME_ATTRACTOR_COUNT: Final[int] = len(PHONEME_ATTRACTOR_LIST)
PHONEME_ATTRACTOR_INDEX: Final[dict] = {a: i for i, a in enumerate(PHONEME_ATTRACTOR_LIST)}


def phoneme_attractor_histogram(coords: Sequence[int]) -> Tuple[int, ...]:
    """Histogram of phoneme attractors for a coord sequence (length = PHONEME_ATTRACTOR_COUNT)."""
    hist = [0] * PHONEME_ATTRACTOR_COUNT
    for c in coords:
        a = COORD_PHONEME_ATTRACTOR[c]
        hist[PHONEME_ATTRACTOR_INDEX[a]] += 1
    return tuple(hist)


def phoneme_attractor_similarity(coords_a: Sequence[int], coords_b: Sequence[int]) -> float:
    """Cosine similarity of phoneme attractor histograms. 1.0 = identical charge distribution."""
    ha = phoneme_attractor_histogram(coords_a)
    hb = phoneme_attractor_histogram(coords_b)
    dot = sum(ha[i] * hb[i] for i in range(PHONEME_ATTRACTOR_COUNT))
    mag_a = sum(v * v for v in ha) ** 0.5
    mag_b = sum(v * v for v in hb) ** 0.5
    if mag_a == 0.0 or mag_b == 0.0:
        return 0.0
    return dot / (mag_a * mag_b)


# =============================================================================
# HKR PROPORTION TABLE
# =============================================================================
# For each RAMA coord, trace through all 16 Maha Algorithm steps.
# Record how much each operation (H/K/R) changes the value.
# Normalize to (h, k, r) where h + k + r ≈ 1.0.


def _compute_hkr_table() -> Tuple[Tuple[float, float, float], ...]:
    """Compute HKR proportion for each RAMA coord. Called once at import."""
    from vibe_core.mahamantra.substrate.algorithm.maha import (
        BINARY_PATTERN,
        MAHA_16_STEPS,
        MahaSynthParams,
    )
    from vibe_core.mahamantra.protocols._seed import (
        KSETRAJNA,
        MAHA_OP_MAP,
        MAHA_SQ,
        MAHAMANTRA_NAME_HARE,
        MAHAMANTRA_NAME_KRISHNA,
        SEVEN,
        TEN,
        WORDS,
    )

    _name_to_key = {
        MAHAMANTRA_NAME_HARE: "H",
        MAHAMANTRA_NAME_KRISHNA: "K",
    }  # everything else is R

    p = MahaSynthParams(mod_space=MAHA_QUANTUM, feedback=KSETRAJNA)
    table = []

    for coord in range(VARNAMALA_TOTAL):
        value = coord % MAHA_QUANTUM
        feedback_acc = 0
        deltas = {"H": 0, "K": 0, "R": 0}

        for step in MAHA_16_STEPS:
            effective_pos = ((step.position - KSETRAJNA + p.phase_offset) % WORDS) + KSETRAJNA

            lfo = 0
            if p.lfo_enabled:
                binary_val = BINARY_PATTERN[(step.position - KSETRAJNA) % WORDS]
                phase_in_lfo = (step.position - KSETRAJNA) % p.lfo_rate
                lfo = binary_val * phase_in_lfo

            adsr_table = (p.adsr_attack, p.adsr_decay, p.adsr_sustain, p.adsr_release)
            adsr = adsr_table[step.phase.value - KSETRAJNA]

            op_key = _name_to_key.get(step.name, "R")
            op = MAHA_OP_MAP[op_key]
            mod = MAHA_QUANTUM

            mult_coeff = (SEVEN * adsr, KSETRAJNA, KSETRAJNA)[op]
            add_coeff = (lfo, TEN + effective_pos + feedback_acc, feedback_acc)[op]

            v = (value * mult_coeff + add_coeff) % mod
            squared = (v * v) % mod
            new_value = MAHA_SQ[op] * squared + (KSETRAJNA - MAHA_SQ[op]) * v

            deltas[op_key] += abs(new_value - value)
            value = new_value
            feedback_acc = (feedback_acc + value * p.feedback) % MAHA_QUANTUM

        total = deltas["H"] + deltas["K"] + deltas["R"]
        if total == 0:
            table.append((0.333, 0.333, 0.334))
        else:
            table.append(
                (
                    deltas["H"] / total,
                    deltas["K"] / total,
                    deltas["R"] / total,
                )
            )

    return tuple(table)


COORD_HKR: Final[Tuple[Tuple[float, float, float], ...]] = _compute_hkr_table()


# =============================================================================
# HKR SIMILARITY FUNCTIONS
# =============================================================================


def hkr_color(coords: Sequence[int]) -> Tuple[float, float, float]:
    """Average HKR color for a sequence of coords."""
    if not coords:
        return (0.333, 0.333, 0.334)
    n = len(coords)
    h = sum(COORD_HKR[c][0] for c in coords) / n
    k = sum(COORD_HKR[c][1] for c in coords) / n
    r = sum(COORD_HKR[c][2] for c in coords) / n
    return (h, k, r)


def hkr_distance(coords_a: Sequence[int], coords_b: Sequence[int]) -> float:
    """Euclidean distance between HKR colors. 0.0 = identical."""
    a = hkr_color(coords_a)
    b = hkr_color(coords_b)
    return ((a[0] - b[0]) ** 2 + (a[1] - b[1]) ** 2 + (a[2] - b[2]) ** 2) ** 0.5


def hkr_similarity(coords_a: Sequence[int], coords_b: Sequence[int]) -> float:
    """HKR similarity. 1.0 = identical, 0.0 = maximally different."""
    d = hkr_distance(coords_a, coords_b)
    return max(0.0, 1.0 - d * 2.0)


# =============================================================================
# EXPORTS
# =============================================================================

__all__ = [
    "COORD_BASIN",
    "BASIN_SET",
    "BASIN_COUNT",
    "BASIN_LIST",
    "BASIN_INDEX",
    "COORD_HKR",
    "COORD_PHONEME_ATTRACTOR",
    "PHONEME_ATTRACTOR_SET",
    "PHONEME_ATTRACTOR_LIST",
    "PHONEME_ATTRACTOR_COUNT",
    "PHONEME_ATTRACTOR_INDEX",
    "basin_signature",
    "basin_set",
    "basin_histogram",
    "basin_jaccard",
    "basin_cosine",
    "hkr_color",
    "hkr_distance",
    "hkr_similarity",
    "phoneme_attractor_histogram",
    "phoneme_attractor_similarity",
]
