"""
OPUS Renderer - AI Master Crate

FOCUSED on:
1. Philosophy from config/opus.yaml
2. @HARNESS verification of docs/architecture/OPUS/
3. Code health (TODOs)
4. Current work tracking

NO HARDCODED GARBAGE. Config-driven.
"""

import logging
from datetime import datetime
from pathlib import Path
from typing import TYPE_CHECKING, Any, Dict, List

import yaml

from vibe_core.plugins.interface.renderers.base import BaseRenderer

if TYPE_CHECKING:
    from vibe_core.kernel_impl import RealVibeKernel

logger = logging.getLogger("OPUS_RENDERER")


class OpusRenderer(BaseRenderer):
    """Master AI Dashboard - Verification-focused."""

    def __init__(self, kernel: "RealVibeKernel"):
        super().__init__(kernel)
        self.kernel = kernel
        self._root = Path(".")  # Keep _root as it's used by _load_config and _render_work_sections
        self._panels: List[Any] = []
        self._panels_loaded = False
        self._config: Dict[str, Any] = {}  # Initialize _config here

        # NOTE: Do NOT call _discover_panels() here.
        # Context (root path) is injected AFTER instantiation by InterfacePlugin.
        # We must load panels lazily.

    def _load_config(self) -> Dict[str, Any]:
        """Load configuration from config/opus.yaml."""
        config_path = self._root / "config" / "opus.yaml"
        try:
            if config_path.exists():
                return yaml.safe_load(config_path.read_text())
        except Exception as e:
            logger.warning(f"[OPUS] Failed to load config: {e}")
        return {}

    @property
    def name(self) -> str:
        return "opus"

    @property
    def output_file(self) -> str:
        return "OPUS.md"

    @property
    def doc_type(self):
        from vibe_core.io_service import DocumentType

        return DocumentType.BIDIRECTIONAL

    def _discover_panels(self) -> None:
        """
        Discover panels using PanelLoader - VEDA-4 compliant.

        Uses injected _root_path to find panels even in containers (Fractal).
        """
        from vibe_core.plugins.interface.panel_loader import PanelLoader

        # Use injected root path if available, else fallback
        # This fixes the "Relative Path Trap" for containers
        base_dir = getattr(self, "_root_path", Path(__file__).parent)
        panels_dir = base_dir / "panels"

        logger.info(f"Discovering panels in {panels_dir} (exists: {panels_dir.exists()})")

        panels, metadata = PanelLoader.discover_and_load(scan_paths=[panels_dir], kernel=self.kernel)

        self._panels = []
        for name, panel in panels.items():
            meta = metadata.get(name)
            if meta and meta.loaded_successfully:
                self._panels.append(panel)
            else:
                # ERROR BOUNDARY: Log but don't crash the renderer
                logger.error(f"Panel {name} failed to load: {meta.error if meta else 'unknown'}")
                # We could add a broken panel placeholder here if desired
                # Error placeholder?
                pass

        logger.info(f"[OPUS] Loaded {len(self._panels)} panels")

    def render(self) -> None:
        """Render OPUS.md with dirty tracking."""
        self.render_with_dirty_tracking()

    def generate_content(self) -> str:
        """Generate OPUS.md content - CLEAN and FOCUSED."""
        if not self._panels_loaded:
            # Lazy load: Ensure we have the injected root path
            self._discover_panels()
            self._panels_loaded = True
            # Also reload config now that root might be set/changed
            self._config = self._load_config()

        lines = []

        # 1. Header with philosophy + harness task
        lines.append(self._render_header())

        # 2. Dynamic panels (verification, code_health)
        for panel in self._panels:
            try:
                panel_content = panel.render()
                if panel_content:
                    lines.append(f"<!-- @LIVE:{panel.panel_id} -->")
                    lines.append(panel_content)
                    lines.append("<!-- /@LIVE -->")
            except Exception as e:
                logger.warning(f"[OPUS] Panel {panel.panel_id} failed: {e}")

        # 3. AI work tracking (minimal)
        lines.append(self._render_work_sections())

        # 4. Footer
        lines.append(self._render_footer())

        return "\n".join(lines)

    def _render_header(self) -> str:
        """Render header with philosophy from config."""
        timestamp = datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S")

        philosophy = self._config.get("philosophy", "")
        harness_task = self._config.get("harness_task", "")

        return f"""<!--
AUTO-GENERATED by OpusRenderer
Last Updated: {timestamp} UTC
Quick Start: python boot.py boot
-->

# OPUS - AI Master Crate

> **Navigation:** [README](README.md) · [INDEX](INDEX.md) · [CONSTITUTION](CONSTITUTION.md) · [docs/architecture/OPUS/](docs/architecture/OPUS/)

---

## Guardian Philosophy

```
{philosophy.strip() if philosophy else "See config/opus.yaml"}
```

<details>
<summary>📋 @HARNESS Task Instructions</summary>

```
{harness_task.strip() if harness_task else "See config/opus.yaml"}
```

</details>

---
"""

    def _render_work_sections(self) -> str:
        """Render minimal AI work tracking sections."""
        # Preserve existing content from OPUS.md
        opus_path = self._root / "OPUS.md"
        existing = ""
        if opus_path.exists():
            try:
                existing = opus_path.read_text()
            except Exception:
                pass

        current_work = self._extract_section(existing, "current_work") or "_Define current task_"
        blockers = self._extract_section(existing, "blockers") or "_None_"

        return f"""---

<!-- @AI:current_work -->
## Current Work

<!-- AI: Update this with what you're working on -->
{current_work}
<!-- /@AI -->

<!-- @AI:blockers -->
## Blockers

<!-- AI: List any blockers -->
{blockers}
<!-- /@AI -->

<!-- @HUMAN:notes -->
## Notes

<!-- Human can write here -->
_Add notes here_
<!-- /@HUMAN -->
"""

    def _extract_section(self, content: str, section_name: str) -> str:
        """Extract preserved section content."""
        import re

        pattern = (
            rf"<!-- @(?:AI|HUMAN):{section_name} -->\s*\n## [^\n]+\n\n<!-- [^>]* -->\n(.*?)<!-- /@(?:AI|HUMAN) -->"
        )
        match = re.search(pattern, content, re.DOTALL)
        if match:
            return match.group(1).strip()
        return None

    def _render_footer(self) -> str:
        timestamp = datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S")
        return f"\n---\n*Generated by OpusRenderer | {timestamp} UTC*"


def create_renderer(kernel: "RealVibeKernel", config: Dict[str, Any]) -> OpusRenderer:
    """Factory function."""
    return OpusRenderer(kernel)
