"""
OPUS Renderer - AI Master Crate

ARCHITECTURE (CLEAN SEPARATION):
- This renderer is the FRONTEND - it writes OPUS.md through kernel.io
- opus_assistant plugin is the BACKEND - provides DATA only
- All file writes go through InterfacePlugin -> kernel.io

This renderer delegates content generation to opus_assistant's
OpusDashboardRenderer, which has richer features:
- StateManager (persistent state)
- Control Plane (metamorphic UI)
- Karma system (trust tracking)
- Dependency Graph (codebase navigation)

NO DIRECT FILE WRITES. All writes go through kernel.io.
"""

import logging
from pathlib import Path
from typing import TYPE_CHECKING, Any, Dict

from vibe_core.plugins.interface.renderers.base import BaseRenderer

if TYPE_CHECKING:
    from vibe_core.kernel_impl import RealVibeKernel

logger = logging.getLogger("OPUS_RENDERER")


class OpusRenderer(BaseRenderer):
    """
    Master AI Dashboard - Delegates to opus_assistant for content.

    ARCHITECTURE:
    - generate_content() -> calls opus_assistant.OpusDashboardRenderer.render()
    - render() -> calls render_with_dirty_tracking() -> InterfacePlugin writes via kernel.io

    This ensures:
    1. Single source of truth (opus_assistant for data)
    2. Single writer (InterfacePlugin via kernel.io)
    3. Clean separation of concerns
    """

    def __init__(self, kernel: "RealVibeKernel"):
        super().__init__(kernel)
        self.kernel = kernel
        self._root = Path(".")
        self._register_data_sources()

    def _register_data_sources(self) -> None:
        """Register data sources for section-based rendering."""
        self.register_data_source("opus.status", self._get_opus_status)
        self.register_data_source("opus.metrics", self._get_opus_metrics)

    def _get_opus_status(self) -> Dict[str, Any]:
        """Get OPUS status for section rendering."""
        return {"status": "active", "mode": "autonomous"}

    def _get_opus_metrics(self) -> Dict[str, Any]:
        """Get OPUS metrics for section rendering."""
        return {"tasks_completed": 0, "karma": 0}

    @property
    def name(self) -> str:
        return "opus"

    @property
    def output_file(self) -> str:
        return "OPUS.md"

    @property
    def doc_type(self):
        from vibe_core.io_service import DocumentType

        return DocumentType.BIDIRECTIONAL

    def render(self) -> None:
        """Render OPUS.md using config-driven sections."""
        config = self.get_config()
        if config and config.sections:
            content = self.render_sections()
            self.merge_and_write(content)
        else:
            # Fallback to opus_assistant delegation
            self.render_with_dirty_tracking()

    def generate_content(self) -> str:
        """
        Generate OPUS.md content by delegating to opus_assistant.
        """
        try:
            import asyncio
            import concurrent.futures

            from vibe_core.plugins.opus_assistant.render.opus_dashboard_renderer import (
                OpusDashboardRenderer,
            )

            # Use the rich opus_assistant renderer for content
            renderer = OpusDashboardRenderer(self._root, kernel=self.kernel)

            def run_async():
                new_loop = asyncio.new_event_loop()
                try:
                    asyncio.set_event_loop(new_loop)
                    return new_loop.run_until_complete(renderer.render(quick=False))
                finally:
                    new_loop.close()

            # Run the async code in a separate thread to avoid loop conflicts
            with concurrent.futures.ThreadPoolExecutor() as executor:
                future = executor.submit(run_async)
                return future.result(timeout=30)

        except Exception as e:
            logger.error(f"[OPUS] Failed to get content from opus_assistant: {e}")
            return self._fallback_content(str(e))

    def _fallback_content(self, error: str) -> str:
        """Minimal fallback content if opus_assistant fails."""
        from datetime import datetime

        timestamp = datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S")
        return f"""# OPUS - System State

> ⚠️ **NOTICE** - opus_assistant unavailable

**Error:** {error[:200]}

---

<!-- @AI:current_work -->
## Current Work

<!-- AI: Update this with what you're working on -->
_Define current task_
<!-- /@AI -->

<!-- @AI:blockers -->
## Blockers

<!-- AI: List any blockers -->
_None_
<!-- /@AI -->

<!-- @HUMAN:notes -->
## Notes

<!-- Human can write here -->
_Add notes here_
<!-- /@HUMAN -->

---
*Generated by OpusRenderer (fallback) | {timestamp} UTC*
"""


def create_renderer(kernel: "RealVibeKernel", config: Dict[str, Any]) -> OpusRenderer:
    """Factory function."""
    return OpusRenderer(kernel)
