"""
OPUS Renderer - Master AI Dashboard with modular panels.

Uses the panel system - to add new panels, just add files to panels/ directory.
No need to edit this file!
"""

import logging
from datetime import datetime
from pathlib import Path
from typing import TYPE_CHECKING, Any, Dict, List

from ..base import BaseRenderer

if TYPE_CHECKING:
    from vibe_core.kernel_impl import RealVibeKernel

logger = logging.getLogger("OPUS_RENDERER")


class OpusRenderer(BaseRenderer):
    """Master AI Dashboard with auto-discovered panels."""

    def __init__(self, kernel: "RealVibeKernel"):
        super().__init__(kernel)
        self._root = Path(".")
        self._docs_path = Path("docs/architecture/OPUS")
        self._panels = []
        self._discover_panels()

    @property
    def name(self) -> str:
        return "opus"

    @property
    def output_file(self) -> str:
        return "OPUS.md"

    @property
    def doc_type(self):
        """Document type for IO service."""
        from vibe_core.io_service import DocumentType

        return DocumentType.BIDIRECTIONAL

    def _discover_panels(self) -> None:
        """Auto-discover panels from panels/ directory."""
        try:
            from .panels import discover_panels

            self._panels = discover_panels(self.kernel)
            logger.info(f"[OPUS] Discovered {len(self._panels)} panels")
        except Exception as e:
            logger.warning(f"[OPUS] Panel discovery failed: {e}")
            self._panels = []

    def render(self) -> None:
        """
        Render OPUS.md with all panels.

        Uses render_with_dirty_tracking() to:
        - Law 3: Skip writes if content hasn't changed (hash-based)
        - Law 1: Create backups before writing
        - Preserve AI/HUMAN sections via merge_and_write()
        """
        # Use helper that includes hash-based dirty tracking
        self.render_with_dirty_tracking()
        logger.debug("[OPUS] Rendered with dirty tracking and section preservation")

    def generate_content(self) -> str:
        """Generate full OPUS.md content."""
        lines = []

        # Header
        lines.append(self._render_header())

        # Status section (built-in)
        lines.append(self._render_status())

        # Metrics section (built-in)
        lines.append(self._render_metrics())

        # Dynamic panels from panels/ directory
        for panel in self._panels:
            try:
                panel_content = panel.render()
                if panel_content:
                    lines.append(f"<!-- @LIVE:{panel.panel_id} -->")
                    lines.append(panel_content)
                    lines.append("<!-- /@LIVE -->")
            except Exception as e:
                logger.warning(f"[OPUS] Panel {panel.panel_id} failed: {e}")
                lines.append(f"<!-- @LIVE:{panel.panel_id} -->")
                lines.append(f"## {panel.title}")
                lines.append("")
                lines.append(f"_Panel error: {e}_")
                lines.append("<!-- /@LIVE -->")

        # Architecture diagram (built-in)
        lines.append(self._render_architecture())

        # Component sizes (built-in)
        lines.append(self._render_components())

        # Plugin status (built-in)
        lines.append(self._render_plugins())

        # AI sections (preserved)
        lines.append(self._render_ai_sections())

        # Footer
        lines.append(self._render_footer())

        return "\n".join(lines)

    def _render_header(self) -> str:
        """Render document header."""
        timestamp = datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S")
        status = getattr(self.kernel, "status", "UNKNOWN")

        return f"""<!--
AUTO-GENERATED by InterfacePlugin
Last Updated: {timestamp} UTC
Kernel: {status}
-->
> **Docs:** [README](README.md) · [INDEX](INDEX.md) · [AGENTS](AGENTS.md) · [CITYMAP](CITYMAP.md) · [HELP](HELP.md) · [TASKS](TASKS.md) · [SETTINGS](SETTINGS.md) · [ENVOY](ENVOY.md)
"""

    def _render_status(self) -> str:
        """Render kernel status."""
        status = getattr(self.kernel, "status", "UNKNOWN")
        if hasattr(status, "value"):
            status = status.value

        agent_count = 0
        if hasattr(self.kernel, "agent_registry"):
            try:
                agent_count = len(self.kernel.agent_registry.list_agents())
            except Exception:
                pass

        loc = self._count_loc("vibe_core/kernel_impl.py")

        return f"""<!-- @LIVE:status -->
## Status

**Kernel**: {status} | **Agents**: {agent_count} | **LOC**: {loc}
<!-- /@LIVE -->"""

    def _render_metrics(self) -> str:
        """Render metrics table."""
        loc = self._count_loc("vibe_core/kernel_impl.py")
        target = 1008
        delta = loc - target
        status_icon = "✅" if loc <= target else ("🟡" if loc <= target + 100 else "🔴")

        plugin_count = len(self.kernel._plugins) if hasattr(self.kernel, "_plugins") else 0
        plugin_status = "✅" if plugin_count >= 8 else "🟡"

        return f"""<!-- @LIVE:metrics -->
## Metrics

| Metric | Current | Target | Delta | Status |
| --- | --- | --- | --- | --- |
| kernel_impl.py LOC | {loc} | {target} | {delta} | {status_icon} |
| Plugins Loaded | {plugin_count} | 8+ | - | {plugin_status} |
<!-- /@LIVE -->"""

    def _render_architecture(self) -> str:
        """Render Mermaid architecture diagram."""
        plugins = self._discover_plugins()
        loc = self._count_loc("vibe_core/kernel_impl.py")

        mermaid_lines = ["```mermaid", "graph TB"]
        mermaid_lines.append(f'    K["🧠 Kernel ({loc} LOC)"]')
        mermaid_lines.append('    subgraph Plugins["📦 Plugins"]')

        for name in plugins:
            mermaid_lines.append(f'        P_{name}["{name}"]')

        mermaid_lines.append("    end")
        mermaid_lines.append("    K --> Plugins")
        mermaid_lines.append('    subgraph Config["🔥 Phoenix Config"]')
        mermaid_lines.append("        PC[PhoenixConfig]")
        mermaid_lines.append("    end")
        mermaid_lines.append("    K --> Config")
        mermaid_lines.append("```")

        return f"""<!-- @LIVE:architecture -->
## Architecture

{chr(10).join(mermaid_lines)}
<!-- /@LIVE -->"""

    def _render_components(self) -> str:
        """Render component sizes table."""
        components = [
            ("vibe_core/kernel_impl.py", "Kernel"),
            ("vibe_core/phoenix/sections/interface/section_main.py", "InterfaceConfig"),
            ("vibe_core/phoenix/config.py", "PhoenixConfig"),
            ("vibe_core/plugins/interface/renderers/base.py", "BaseRenderer"),
            ("vibe_core/kernel_ops.py", "Kernel Ops"),
            ("vibe_core/plugins/interface/plugin_main.py", "InterfacePlugin"),
            ("vibe_core/event_bus.py", "EventBus"),
        ]

        rows = []
        for path, name in components:
            loc = self._count_loc(path)
            if loc > 0:
                rows.append((name, path.split("/")[-1], loc))

        rows.sort(key=lambda x: x[2], reverse=True)

        table_lines = ["| Component | File | LOC |", "| --- | --- | --- |"]
        for name, file, loc in rows:
            table_lines.append(f"| {name} | {file} | {loc} |")

        return f"""<!-- @LIVE:component_sizes -->
## Component Sizes

{chr(10).join(table_lines)}
<!-- /@LIVE -->"""

    def _render_plugins(self) -> str:
        """Render plugin status table."""
        rows = []
        if hasattr(self.kernel, "_plugins"):
            for plugin in self.kernel._plugins:
                plugin_id = getattr(plugin, "plugin_id", type(plugin).__name__)
                rows.append((plugin_id, "✅ Active", type(plugin).__name__))

        if not rows:
            rows = [("None loaded", "⚪", "-")]

        table_lines = ["| Plugin | Status | Type |", "| --- | --- | --- |"]
        for plugin, status, ptype in rows:
            table_lines.append(f"| {plugin} | {status} | {ptype} |")

        return f"""<!-- @LIVE:plugin_status -->
## Plugin Status

{chr(10).join(table_lines)}
<!-- /@LIVE -->"""

    def _extract_preserved_section(self, content: str, section_name: str, tag_prefix: str = "@AI") -> str:
        """Extract content from a preserved section (AI or HUMAN) in existing file.

        Returns the content between <!-- @AI:section_name --> and <!-- /@AI -->,
        or None if not found.
        """
        import re

        pattern = rf"<!-- {tag_prefix}:{section_name} -->\s*\n## [^\n]+\n\n<!-- [^>]+ -->\n(.*?)<!-- /{tag_prefix} -->"
        match = re.search(pattern, content, re.DOTALL)
        if match:
            return match.group(1).strip()
        return None

    def _render_ai_sections(self) -> str:
        """Render AI-writable sections, PRESERVING existing content."""
        # Read existing OPUS.md to preserve AI sections
        opus_path = self._root / "OPUS.md"
        existing_content = ""
        if opus_path.exists():
            try:
                existing_content = opus_path.read_text()
            except Exception:
                pass

        # Extract preserved content or use defaults
        current_goal = self._extract_preserved_section(existing_content, "current_goal") or "_No entries_"
        phase_status = self._extract_preserved_section(existing_content, "phase_status") or "_No entries_"
        extraction_log = self._extract_preserved_section(existing_content, "extraction_log") or "_No entries_"
        blockers = self._extract_preserved_section(existing_content, "blockers") or "_No entries_"
        next_actions = self._extract_preserved_section(existing_content, "next_actions", "@HUMAN") or "_No entries_"

        return f"""<!-- @AI:current_goal -->
## Current Goal

<!-- AI can write here -->
{current_goal}
<!-- /@AI -->
<!-- @AI:phase_status -->
## Phase Status

<!-- AI can write here -->
{phase_status}
<!-- /@AI -->
<!-- @AI:extraction_log -->
## Extraction Log

<!-- AI can write here -->
{extraction_log}
<!-- /@AI -->
<!-- @AI:blockers -->
## Blockers

<!-- AI can write here -->
{blockers}
<!-- /@AI -->
<!-- @HUMAN:next_actions -->
## Next Actions

<!-- User section -->
{next_actions}
<!-- /@HUMAN -->"""

    def _render_footer(self) -> str:
        """Render footer."""
        timestamp = datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S")
        return f"*Generated by InterfacePlugin | {timestamp} UTC*"

    def _discover_plugins(self) -> List[str]:
        """Discover plugin names."""
        plugins_dir = self._root / "vibe_core" / "plugins"
        result = []
        if plugins_dir.exists():
            for item in plugins_dir.iterdir():
                if item.is_dir() and not item.name.startswith("_"):
                    if (item / "plugin_main.py").exists():
                        result.append(item.name)
        return result

    def _count_loc(self, path: str) -> int:
        """Count lines of code."""
        try:
            full_path = self._root / path
            if full_path.exists():
                return len(full_path.read_text().splitlines())
        except Exception:
            pass
        return 0


def create_renderer(kernel: "RealVibeKernel", config: Dict[str, Any]) -> OpusRenderer:
    """Factory function."""
    return OpusRenderer(kernel)
