"""
OPUS-159: Template Registry

Central registry for all module type templates.
Templates are versioned and validated.
"""

import logging
from dataclasses import dataclass
from pathlib import Path
from string import Template
from typing import Callable, Dict, List, Optional

from .types import ModuleType

logger = logging.getLogger("GENESIS.TEMPLATES")


@dataclass
class ModuleTemplate:
    """A template for a specific file in a module."""

    filename: str
    content: str
    required: bool = True
    processor: Optional[Callable[[str, Dict], str]] = None

    def render(self, context: Dict) -> str:
        """Render template with context."""
        if self.processor:
            return self.processor(self.content, context)
        return Template(self.content).safe_substitute(context)


class TemplateRegistry:
    """
    Central registry for all module type templates.

    Provides default templates for each module type.
    Allows custom template registration.
    """

    _instance: Optional["TemplateRegistry"] = None

    def __init__(self, templates_dir: Optional[Path] = None):
        """Initialize template registry."""
        self._templates_dir = templates_dir or self._get_default_templates_dir()
        self._templates: Dict[ModuleType, Dict[str, ModuleTemplate]] = {}
        self._load_default_templates()

    @classmethod
    def get_instance(cls) -> "TemplateRegistry":
        """Get singleton instance."""
        if cls._instance is None:
            cls._instance = cls()
        return cls._instance

    def get_templates(self, module_type: ModuleType) -> Dict[str, ModuleTemplate]:
        """Get all templates for a module type."""
        return self._templates.get(module_type, {})

    def get_template(self, module_type: ModuleType, filename: str) -> Optional[ModuleTemplate]:
        """Get a specific template."""
        templates = self._templates.get(module_type, {})
        return templates.get(filename)

    def register_template(
        self,
        module_type: ModuleType,
        filename: str,
        content: str,
        required: bool = True,
    ) -> None:
        """Register a custom template."""
        if module_type not in self._templates:
            self._templates[module_type] = {}

        self._templates[module_type][filename] = ModuleTemplate(
            filename=filename,
            content=content,
            required=required,
        )

    def get_required_files(self, module_type: ModuleType) -> List[str]:
        """Get list of required files for a module type."""
        templates = self._templates.get(module_type, {})
        return [t.filename for t in templates.values() if t.required]

    def _get_default_templates_dir(self) -> Path:
        """Get default templates directory."""
        return Path(__file__).parent / "templates"

    def _load_default_templates(self) -> None:
        """Load default templates for all module types."""
        # Plugin templates
        self._templates[ModuleType.PLUGIN] = {
            "__init__.py": ModuleTemplate(
                filename="__init__.py",
                content='''"""
$name Plugin

Auto-generated by Genesis Service (OPUS-159).
"""

from .plugin_main import ${class_name}Plugin

__all__ = ["${class_name}Plugin"]
''',
            ),
            "manifest.json": ModuleTemplate(
                filename="manifest.json",
                content="""{
  "type": "plugin",
  "id": "$id",
  "name": "$name",
  "version": "0.1.0",
  "description": "$description",
  "entry_point": "plugin_main.py",
  "entry_class": "${class_name}Plugin",
  "priority": 50,
  "enabled": true,
  "hooks": [],
  "capabilities": [],
  "dependencies": [],
  "author": "Genesis Service",
  "generated_at": "$timestamp"
}
""",
            ),
            "plugin_main.py": ModuleTemplate(
                filename="plugin_main.py",
                content='''"""
$name Plugin Main

Auto-generated by Genesis Service (OPUS-159).
"""

import logging
from pathlib import Path
from typing import Any, Dict, Optional

logger = logging.getLogger("PLUGIN.$id_upper")


class ${class_name}Plugin:
    """
    $name Plugin.

    TODO: Add plugin description.
    """

    def __init__(self, kernel: Any = None, config: Optional[Dict] = None):
        """Initialize plugin."""
        self._kernel = kernel
        self._config = config or {}
        self._workspace = Path.cwd()
        logger.info(f"{self.__class__.__name__} initialized")

    async def on_boot(self) -> None:
        """Called when plugin boots."""
        pass

    async def on_shutdown(self) -> None:
        """Called when plugin shuts down."""
        pass
''',
            ),
        }

        # Cartridge templates
        self._templates[ModuleType.CARTRIDGE] = {
            "__init__.py": ModuleTemplate(
                filename="__init__.py",
                content='''"""
$name Cartridge

Auto-generated by Genesis Service (OPUS-159).
"""

from .cartridge_main import ${class_name}Cartridge

__all__ = ["${class_name}Cartridge"]
''',
            ),
            "cartridge_main.py": ModuleTemplate(
                filename="cartridge_main.py",
                content='''"""
$name Cartridge

Auto-generated by Genesis Service (OPUS-159).
"""

import logging
from typing import Any, Dict

from vibe_core import Task, VibeAgent
from vibe_core.steward import OathMixin

logger = logging.getLogger("AGENT.$id_upper")


class ${class_name}Cartridge(VibeAgent, OathMixin):
    """
    $name Agent.

    TODO: Add agent description.
    """

    def __init__(self, config: Optional[Dict] = None):
        """Initialize agent."""
        self.config = config or {}
        super().__init__(
            agent_id="$id",
            name="$name",
            version="0.1.0",
            domain="$domain",
            capabilities=[],
        )
        # Constitutional Oath binding
        self.oath_mixin_init(self.agent_id)
        self.oath_sworn = True

    async def process(self, task: Task) -> Dict[str, Any]:
        """Process a task."""
        # TODO: Implement task processing
        return {"status": "not_implemented"}

    def report_status(self) -> Dict[str, Any]:
        """Report agent status."""
        return {
            "agent_id": self.agent_id,
            "status": "operational",
        }
''',
            ),
            "cartridge.yaml": ModuleTemplate(
                filename="cartridge.yaml",
                content="""# $name Cartridge Configuration
# Auto-generated by Genesis Service (OPUS-159)

id: $id
name: $name
version: 0.1.0
domain: $domain
description: $description

capabilities: []
dependencies: []

config:
  enabled: true
""",
            ),
            "steward.json": ModuleTemplate(
                filename="steward.json",
                content="""{
  "agent_id": "$id",
  "name": "$name",
  "version": "0.1.0",
  "domain": "$domain",
  "constitution_hash": null,
  "oath_sworn": false,
  "generated_at": "$timestamp",
  "genesis": "OPUS-159"
}
""",
            ),
        }

        # Section templates
        self._templates[ModuleType.SECTION] = {
            "manifest.json": ModuleTemplate(
                filename="manifest.json",
                content="""{
  "type": "phoenix_section",
  "id": "$id",
  "name": "$name",
  "version": "0.1.0",
  "description": "$description",
  "schema_file": "schema.json",
  "default_file": "defaults.yaml",
  "generated_at": "$timestamp"
}
""",
            ),
        }

        # Analyzer templates
        self._templates[ModuleType.ANALYZER] = {
            "analyzer.py": ModuleTemplate(
                filename="${id}_analyzer.py",
                content='''"""
$name Analyzer

Auto-generated by Genesis Service (OPUS-159).
"""

from typing import Any, Dict, List, Optional

from .base import BaseAnalyzer


class ${class_name}Analyzer(BaseAnalyzer):
    """
    $name Analyzer.

    TODO: Add description.
    """

    name = "$id"

    def analyze(self, context: Optional[Dict[str, Any]] = None) -> List[Any]:
        """Analyze and generate intents."""
        # TODO: Implement analysis logic
        return []
''',
            ),
        }

        # Sense templates
        self._templates[ModuleType.SENSE] = {
            "sense.py": ModuleTemplate(
                filename="${id}_sense.py",
                content='''"""
$name Sense

Auto-generated by Genesis Service (OPUS-159).

Sanskrit: Indriya = Sense organ
"""

from pathlib import Path
from typing import Any, Dict, Optional

from .base import BaseSense


class ${class_name}Sense(BaseSense):
    """
    $name Sense - A Jnanendriya.

    TODO: Add description of what this sense perceives.
    """

    name = "$id"

    def perceive(self, context: Optional[Dict[str, Any]] = None) -> Dict[str, Any]:
        """Perceive the environment."""
        # TODO: Implement perception logic
        return {
            "sense": self.name,
            "perceived": True,
        }
''',
            ),
        }

        # Action templates
        self._templates[ModuleType.ACTION] = {
            "action.py": ModuleTemplate(
                filename="${id}_action.py",
                content='''"""
$name Action

Auto-generated by Genesis Service (OPUS-159).

Sanskrit: Karmendriya = Action organ
"""

from typing import Any, Set

from .base_action import ActionResult, BaseAction


class ${class_name}Action(BaseAction):
    """
    $name Action - A Karmendriya.

    TODO: Add description of what this action does.
    """

    name = "$id"

    handled_intent_types: Set[str] = {
        # TODO: Add intent types this action handles
    }

    def act(self, intent: Any) -> ActionResult:
        """Execute an intent."""
        # TODO: Implement action logic
        return ActionResult(
            success=False,
            action_name=self.name,
            intent_type=getattr(intent, "intent_type", "unknown"),
            error="Not implemented",
        )
''',
            ),
        }

        # Knowledge templates
        self._templates[ModuleType.KNOWLEDGE] = {
            "manifest.json": ModuleTemplate(
                filename="manifest.json",
                content="""{
  "type": "knowledge",
  "id": "$id",
  "name": "$name",
  "version": "0.1.0",
  "description": "$description",
  "format": "yaml",
  "generated_at": "$timestamp"
}
""",
            ),
        }
