"""
NAGA Commit Watcher - Observes all commit outcomes.

"Der Wächter-Pattern" - NAGAs notice when things go wrong.
"Oh es werden keine state files committet" - We see everything.

This module provides:
1. CommitWatcher - Observer for commit results
2. Pattern detection for repeated failures
3. Alert generation for systemic issues
4. Audit trail via Sesha/Ledger

Integration:
- Register with ServiceRegistry as CommitWatcherProtocol
- Call observe() after every commit_if_dirty()
- Automatic pattern detection and alerting

The Wächter notices:
- Repeated PANIC_DUMPED outcomes (data loss risk)
- "No commits happening" (system stagnation)
- Unusual deferral patterns (decision paralysis)
- High healed conflict rates (merge drift)
"""

import logging
import time
from collections import deque
from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import TYPE_CHECKING, Any, Callable, Deque, Dict, List, Optional

if TYPE_CHECKING:
    from vibe_core.naga.cortex.signals import CommitSignal
    from vibe_core.naga.services.sesha import SeshaService
    from vibe_core.naga.services.takshaka import TakshakaService
    from vibe_core.phoenix.sections.naga.section_main import CommitWatcherConfig
    from vibe_core.state.commit_authority import CommitOutcome, CommitResult

# Type aliases for callbacks (GAD-000 Typing Discipline)
CortexCommitCallback = Callable[["CommitSignal"], None]
AlertHandler = Callable[["CommitAlert"], None]

logger = logging.getLogger("NAGA.COMMIT_WATCHER")


# =============================================================================
# GAD-000 PARSEABILITY: ALERT CODES
# =============================================================================


class AlertCode(Enum):
    """
    Machine-parseable alert codes (GAD-000 Parseability).

    Format: AXXX where X is a 3-digit code.
    """

    A001_PANIC_PATTERN = "A001"
    A002_STAGNATION = "A002"
    A003_DEFERRAL_LOOP = "A003"
    A004_CONFLICT_DRIFT = "A004"


# =============================================================================
# DEFAULTS (used when no config provided - backwards compatibility)
# =============================================================================

DEFAULT_PANIC_THRESHOLD = 3  # Panic dumps in window
DEFAULT_PANIC_WINDOW_SECONDS = 300  # 5 minutes
DEFAULT_STAGNATION_SECONDS = 600  # 10 minutes without commit
DEFAULT_DEFERRAL_THRESHOLD = 5  # Consecutive deferrals
DEFAULT_CONFLICT_RATE_THRESHOLD = 0.5  # 50% healed
DEFAULT_ROLLING_WINDOW_SIZE = 100


# =============================================================================
# ALERT TYPES
# =============================================================================


@dataclass
class CommitAlert:
    """Alert generated by the commit watcher."""

    alert_type: str  # PANIC_PATTERN, STAGNATION, DEFERRAL_LOOP, CONFLICT_DRIFT
    severity: str  # WARNING, ERROR, CRITICAL
    message: str
    details: Dict[str, Any] = field(default_factory=dict)
    timestamp: datetime = field(default_factory=datetime.now)
    # GAD-000 Parseability: Machine-readable alert code
    alert_code: AlertCode = AlertCode.A001_PANIC_PATTERN

    def to_dict(self) -> Dict[str, Any]:
        return {
            "alert_type": self.alert_type,
            "alert_code": self.alert_code.value,  # Machine-parseable
            "severity": self.severity,
            "message": self.message,
            "details": self.details,
            "timestamp": self.timestamp.isoformat(),
        }


@dataclass
class CommitStats:
    """Statistics for commit watching."""

    total_observed: int = 0
    success_count: int = 0
    skipped_count: int = 0
    deferred_count: int = 0
    healed_count: int = 0
    panic_count: int = 0
    alerts_generated: int = 0
    last_success_at: Optional[float] = None
    started_at: float = field(default_factory=time.time)

    def to_dict(self) -> Dict[str, Any]:
        uptime = time.time() - self.started_at
        return {
            "total_observed": self.total_observed,
            "success_count": self.success_count,
            "skipped_count": self.skipped_count,
            "deferred_count": self.deferred_count,
            "healed_count": self.healed_count,
            "panic_count": self.panic_count,
            "alerts_generated": self.alerts_generated,
            "success_rate": self.success_count / max(self.total_observed, 1),
            "last_success_ago": (time.time() - self.last_success_at if self.last_success_at else None),
            "uptime_seconds": uptime,
        }


# =============================================================================
# COMMIT WATCHER
# =============================================================================


class NagaCommitWatcher:
    """
    The Wächter - Observes all commit outcomes.

    Pattern Detection:
    - PANIC_PATTERN: 3+ panic dumps in 5 minutes
    - STAGNATION: No successful commits in 10 minutes
    - DEFERRAL_LOOP: 5+ deferrals without a commit
    - CONFLICT_DRIFT: 50%+ commits require healing

    Usage:
        watcher = NagaCommitWatcher(sesha=sesha, takshaka=takshaka)
        result = commit_authority.commit(...)
        watcher.observe(result)  # <- The hook
    """

    def __init__(
        self,
        sesha: Optional["SeshaService"] = None,
        takshaka: Optional["TakshakaService"] = None,
        enabled: bool = True,
        config: Optional["CommitWatcherConfig"] = None,
    ):
        self._sesha = sesha
        self._takshaka = takshaka
        self._enabled = enabled
        self._stats = CommitStats()

        # Load config values (fall back to defaults for backwards compatibility)
        self._panic_threshold = config.panic_threshold if config else DEFAULT_PANIC_THRESHOLD
        self._panic_window_seconds = config.panic_window_seconds if config else DEFAULT_PANIC_WINDOW_SECONDS
        self._stagnation_seconds = config.stagnation_seconds if config else DEFAULT_STAGNATION_SECONDS
        self._deferral_threshold = config.deferral_threshold if config else DEFAULT_DEFERRAL_THRESHOLD
        self._conflict_rate_threshold = config.conflict_rate_threshold if config else DEFAULT_CONFLICT_RATE_THRESHOLD
        rolling_window_size = config.rolling_window_size if config else DEFAULT_ROLLING_WINDOW_SIZE

        # Rolling window for pattern detection
        self._recent_outcomes: Deque[tuple] = deque(maxlen=rolling_window_size)
        self._consecutive_deferrals = 0
        self._alert_handlers: List[AlertHandler] = []

        # Cortex integration (optional, non-invasive)
        self._cortex_callback: Optional[CortexCommitCallback] = None

        logger.info(
            f"[COMMIT_WATCHER] Initialized (panic_threshold={self._panic_threshold}, stagnation={self._stagnation_seconds}s)"
        )

    def set_cortex_callback(self, callback: CortexCommitCallback) -> None:
        """Set callback for sending signals to Cortex. Non-invasive integration."""
        self._cortex_callback = callback
        logger.debug("[COMMIT_WATCHER] Cortex callback registered")

    # =========================================================================
    # MAIN API
    # =========================================================================

    def observe(self, result: "CommitResult") -> Optional[CommitAlert]:
        """
        Observe a commit result and detect patterns.

        This is the main hook - call after every commit.

        Args:
            result: The CommitResult from CommitAuthority

        Returns:
            CommitAlert if a pattern was detected, None otherwise
        """
        if not self._enabled:
            return None

        self._stats.total_observed += 1
        now = time.time()

        # Import locally to avoid circular deps
        from vibe_core.state.commit_authority import CommitOutcome

        # Handle outcome mapping (result.outcome is CommitOutcome enum)
        outcome = result.outcome

        # Track stats
        if outcome == CommitOutcome.SUCCESS:
            self._stats.success_count += 1
            self._stats.last_success_at = now
            self._consecutive_deferrals = 0

        elif outcome == CommitOutcome.SKIPPED:
            self._stats.skipped_count += 1
            # Skipped is not a problem per se

        elif outcome == CommitOutcome.DEFERRED:
            self._stats.deferred_count += 1
            self._consecutive_deferrals += 1

        elif outcome == CommitOutcome.HEALED:
            self._stats.healed_count += 1
            self._stats.last_success_at = now
            self._consecutive_deferrals = 0

        elif outcome == CommitOutcome.PANIC_DUMPED:
            self._stats.panic_count += 1
            self._audit("COMMIT_PANIC", result)

        # Add to rolling window
        self._recent_outcomes.append((now, outcome))

        # Detect patterns
        alert = self._detect_patterns(outcome)

        if alert:
            self._stats.alerts_generated += 1
            self._dispatch_alert(alert)

        # --- CORTEX SIGNAL (non-invasive) ---
        # Send observation to Cortex for correlation
        if self._cortex_callback:
            try:
                from vibe_core.naga.cortex.signals import CommitSignal

                # Map outcome to pattern name
                pattern_map = {
                    CommitOutcome.SUCCESS: "SUCCESS",
                    CommitOutcome.SKIPPED: "SKIPPED",
                    CommitOutcome.DEFERRED: "DEFERRAL",
                    CommitOutcome.HEALED: "HEALED",
                    CommitOutcome.PANIC_DUMPED: "PANIC",
                }
                pattern = pattern_map.get(outcome, "UNKNOWN")

                signal = CommitSignal(
                    source_id="commit_watcher",
                    pattern=pattern,
                    commit_sha=getattr(result, "sha", "") or "",
                    files_changed=tuple(getattr(result, "files_changed", []) or []),
                    severity=alert.severity if alert else "INFO",
                )
                self._cortex_callback(signal)
            except Exception as e:
                # Observer must not crash, but errors should be tracked (GAD-000 Parseability)
                logger.warning(f"[COMMIT_WATCHER] Cortex callback failed: {type(e).__name__}: {e}")

        return alert

    # =========================================================================
    # PATTERN DETECTION
    # =========================================================================

    def _detect_patterns(self, current_outcome: "CommitOutcome") -> Optional[CommitAlert]:
        """
        Detect problematic patterns.

        Returns alert if pattern detected.
        """
        from vibe_core.state.commit_authority import CommitOutcome

        now = time.time()

        # Check PANIC_PATTERN
        if current_outcome == CommitOutcome.PANIC_DUMPED:
            panic_count = self._count_recent_outcomes(
                CommitOutcome.PANIC_DUMPED,
                window_seconds=self._panic_window_seconds,
            )
            if panic_count >= self._panic_threshold:
                return CommitAlert(
                    alert_type="PANIC_PATTERN",
                    alert_code=AlertCode.A001_PANIC_PATTERN,
                    severity="CRITICAL",
                    message=f"Panic dump pattern detected: {panic_count} panics in {self._panic_window_seconds}s",
                    details={
                        "panic_count": panic_count,
                        "window_seconds": self._panic_window_seconds,
                    },
                )

        # Check STAGNATION
        if self._stats.last_success_at:
            time_since_success = now - self._stats.last_success_at
            if time_since_success > self._stagnation_seconds:
                # Only alert once per stagnation period
                if self._stats.total_observed % 10 == 0:  # Throttle
                    return CommitAlert(
                        alert_type="STAGNATION",
                        alert_code=AlertCode.A002_STAGNATION,
                        severity="WARNING",
                        message=f"No successful commits in {int(time_since_success)}s",
                        details={
                            "seconds_since_success": time_since_success,
                            "threshold_seconds": self._stagnation_seconds,
                        },
                    )

        # Check DEFERRAL_LOOP
        if self._consecutive_deferrals >= self._deferral_threshold:
            return CommitAlert(
                alert_type="DEFERRAL_LOOP",
                alert_code=AlertCode.A003_DEFERRAL_LOOP,
                severity="WARNING",
                message=f"Decision paralysis: {self._consecutive_deferrals} consecutive deferrals",
                details={
                    "consecutive_deferrals": self._consecutive_deferrals,
                    "threshold": self._deferral_threshold,
                },
            )

        # Check CONFLICT_DRIFT
        if self._stats.total_observed >= 10:  # Need minimum sample
            healed_rate = self._stats.healed_count / self._stats.total_observed
            if healed_rate > self._conflict_rate_threshold:
                # Only alert periodically
                if self._stats.total_observed % 20 == 0:  # Throttle
                    return CommitAlert(
                        alert_type="CONFLICT_DRIFT",
                        alert_code=AlertCode.A004_CONFLICT_DRIFT,
                        severity="WARNING",
                        message=f"High conflict rate: {healed_rate:.1%} commits require healing",
                        details={
                            "healed_count": self._stats.healed_count,
                            "total_count": self._stats.total_observed,
                            "rate": healed_rate,
                        },
                    )

        return None

    def _count_recent_outcomes(
        self,
        outcome: "CommitOutcome",
        window_seconds: float,
    ) -> int:
        """Count occurrences of outcome in recent window."""
        now = time.time()
        cutoff = now - window_seconds

        count = 0
        for ts, o in self._recent_outcomes:
            if ts >= cutoff and o == outcome:
                count += 1

        return count

    # =========================================================================
    # ALERT DISPATCH
    # =========================================================================

    def add_alert_handler(self, handler: AlertHandler) -> None:
        """Add a handler to be called when alerts are generated."""
        self._alert_handlers.append(handler)

    def _dispatch_alert(self, alert: CommitAlert) -> None:
        """Dispatch alert to handlers and log to Ledger."""
        # Log it
        if alert.severity == "CRITICAL":
            logger.error(f"[COMMIT_WATCHER] {alert.alert_type}: {alert.message}")
        else:
            logger.warning(f"[COMMIT_WATCHER] {alert.alert_type}: {alert.message}")

        # Record to Ledger via Sesha
        self._audit(f"COMMIT_ALERT_{alert.alert_type}", alert.to_dict())

        # Call handlers
        for handler in self._alert_handlers:
            try:
                handler(alert)
            except Exception as e:
                logger.debug(f"[COMMIT_WATCHER] Handler error: {e}")

        # Bite via Takshaka for critical alerts
        if alert.severity == "CRITICAL" and self._takshaka:
            try:
                from vibe_core.protocols.naga import VajraViolation

                violation = VajraViolation(
                    violation_type=f"COMMIT_{alert.alert_type}",
                    source="commit_watcher",
                    details=alert.to_dict(),
                )
                self._takshaka.bite(violation)
            except Exception:
                pass  # Silent fail

    # =========================================================================
    # AUDIT HELPER
    # =========================================================================

    def _audit(self, event_type: str, data: Any) -> None:
        """Record to Ledger via Sesha."""
        if not self._sesha:
            return

        try:
            if hasattr(self._sesha, "_ledger") and self._sesha._ledger:
                details = data if isinstance(data, dict) else {"result": str(data)}
                self._sesha._ledger.record_event(
                    event_type=f"NAGA_{event_type}",
                    agent_id="commit_watcher",
                    details=details,
                )
        except Exception:
            pass  # Silent fail

    # =========================================================================
    # STATUS
    # =========================================================================

    def get_stats(self) -> Dict[str, Any]:
        """Get commit watching statistics."""
        return {
            "enabled": self._enabled,
            "consecutive_deferrals": self._consecutive_deferrals,
            "recent_window_size": len(self._recent_outcomes),
            **self._stats.to_dict(),
        }

    def reset_stats(self) -> None:
        """Reset statistics (for testing)."""
        self._stats = CommitStats()
        self._recent_outcomes.clear()
        self._consecutive_deferrals = 0


# =============================================================================
# INTEGRATION HELPER
# =============================================================================


def wrap_commit_with_watcher(
    commit_func: Callable[..., "CommitResult"],
    watcher: NagaCommitWatcher,
) -> Callable[..., "CommitResult"]:
    """
    Wrap a commit function to automatically observe results.

    Usage:
        authority.commit = wrap_commit_with_watcher(authority.commit, watcher)
    """

    def wrapped(*args: Any, **kwargs: Any) -> "CommitResult":
        result = commit_func(*args, **kwargs)
        watcher.observe(result)
        return result

    return wrapped
