"""
NAGA Commit Watcher - Observes all commit outcomes.

"Der Wächter-Pattern" - NAGAs notice when things go wrong.
"Oh es werden keine state files committet" - We see everything.

This module provides:
1. CommitWatcher - Observer for commit results
2. Pattern detection for repeated failures
3. Alert generation for systemic issues
4. Audit trail via Sesha/Ledger

Integration:
- Register with ServiceRegistry as CommitWatcherProtocol
- Call observe() after every commit_if_dirty()
- Automatic pattern detection and alerting

The Wächter notices:
- Repeated PANIC_DUMPED outcomes (data loss risk)
- "No commits happening" (system stagnation)
- Unusual deferral patterns (decision paralysis)
- High healed conflict rates (merge drift)
"""

import logging
import time
from collections import deque
from dataclasses import dataclass, field
from datetime import datetime
from typing import TYPE_CHECKING, Any, Callable, Deque, Dict, List, Optional

if TYPE_CHECKING:
    from vibe_core.naga.cortex.signals import CommitSignal
    from vibe_core.naga.services.sesha import SeshaService
    from vibe_core.naga.services.takshaka import TakshakaService
    from vibe_core.state.commit_authority import CommitOutcome, CommitResult

# Type alias for cortex signal callback
CortexCommitCallback = Callable[["CommitSignal"], None]

logger = logging.getLogger("NAGA.COMMIT_WATCHER")


# =============================================================================
# ALERT TYPES
# =============================================================================


@dataclass
class CommitAlert:
    """Alert generated by the commit watcher."""

    alert_type: str  # PANIC_PATTERN, STAGNATION, DEFERRAL_LOOP, CONFLICT_DRIFT
    severity: str  # WARNING, ERROR, CRITICAL
    message: str
    details: Dict[str, Any] = field(default_factory=dict)
    timestamp: datetime = field(default_factory=datetime.now)

    def to_dict(self) -> Dict[str, Any]:
        return {
            "alert_type": self.alert_type,
            "severity": self.severity,
            "message": self.message,
            "details": self.details,
            "timestamp": self.timestamp.isoformat(),
        }


@dataclass
class CommitStats:
    """Statistics for commit watching."""

    total_observed: int = 0
    success_count: int = 0
    skipped_count: int = 0
    deferred_count: int = 0
    healed_count: int = 0
    panic_count: int = 0
    alerts_generated: int = 0
    last_success_at: Optional[float] = None
    started_at: float = field(default_factory=time.time)

    def to_dict(self) -> Dict[str, Any]:
        uptime = time.time() - self.started_at
        return {
            "total_observed": self.total_observed,
            "success_count": self.success_count,
            "skipped_count": self.skipped_count,
            "deferred_count": self.deferred_count,
            "healed_count": self.healed_count,
            "panic_count": self.panic_count,
            "alerts_generated": self.alerts_generated,
            "success_rate": self.success_count / max(self.total_observed, 1),
            "last_success_ago": (time.time() - self.last_success_at if self.last_success_at else None),
            "uptime_seconds": uptime,
        }


# =============================================================================
# COMMIT WATCHER
# =============================================================================


class NagaCommitWatcher:
    """
    The Wächter - Observes all commit outcomes.

    Pattern Detection:
    - PANIC_PATTERN: 3+ panic dumps in 5 minutes
    - STAGNATION: No successful commits in 10 minutes
    - DEFERRAL_LOOP: 5+ deferrals without a commit
    - CONFLICT_DRIFT: 50%+ commits require healing

    Usage:
        watcher = NagaCommitWatcher(sesha=sesha, takshaka=takshaka)
        result = commit_authority.commit(...)
        watcher.observe(result)  # <- The hook
    """

    # Alert thresholds
    PANIC_THRESHOLD = 3  # Panic dumps in window
    PANIC_WINDOW_SECONDS = 300  # 5 minutes
    STAGNATION_SECONDS = 600  # 10 minutes without commit
    DEFERRAL_THRESHOLD = 5  # Consecutive deferrals
    CONFLICT_RATE_THRESHOLD = 0.5  # 50% healed

    def __init__(
        self,
        sesha: Optional["SeshaService"] = None,
        takshaka: Optional["TakshakaService"] = None,
        enabled: bool = True,
    ):
        self._sesha = sesha
        self._takshaka = takshaka
        self._enabled = enabled
        self._stats = CommitStats()

        # Rolling window for pattern detection
        self._recent_outcomes: Deque[tuple] = deque(maxlen=100)  # (timestamp, outcome)
        self._consecutive_deferrals = 0
        self._alert_handlers: List[callable] = []

        # Cortex integration (optional, non-invasive)
        self._cortex_callback: Optional[CortexCommitCallback] = None

        logger.info("[COMMIT_WATCHER] Initialized")

    def set_cortex_callback(self, callback: CortexCommitCallback) -> None:
        """Set callback for sending signals to Cortex. Non-invasive integration."""
        self._cortex_callback = callback
        logger.debug("[COMMIT_WATCHER] Cortex callback registered")

    # =========================================================================
    # MAIN API
    # =========================================================================

    def observe(self, result: "CommitResult") -> Optional[CommitAlert]:
        """
        Observe a commit result and detect patterns.

        This is the main hook - call after every commit.

        Args:
            result: The CommitResult from CommitAuthority

        Returns:
            CommitAlert if a pattern was detected, None otherwise
        """
        if not self._enabled:
            return None

        self._stats.total_observed += 1
        now = time.time()

        # Import locally to avoid circular deps
        from vibe_core.state.commit_authority import CommitOutcome

        # Handle outcome mapping (result.outcome is CommitOutcome enum)
        outcome = result.outcome

        # Track stats
        if outcome == CommitOutcome.SUCCESS:
            self._stats.success_count += 1
            self._stats.last_success_at = now
            self._consecutive_deferrals = 0

        elif outcome == CommitOutcome.SKIPPED:
            self._stats.skipped_count += 1
            # Skipped is not a problem per se

        elif outcome == CommitOutcome.DEFERRED:
            self._stats.deferred_count += 1
            self._consecutive_deferrals += 1

        elif outcome == CommitOutcome.HEALED:
            self._stats.healed_count += 1
            self._stats.last_success_at = now
            self._consecutive_deferrals = 0

        elif outcome == CommitOutcome.PANIC_DUMPED:
            self._stats.panic_count += 1
            self._audit("COMMIT_PANIC", result)

        # Add to rolling window
        self._recent_outcomes.append((now, outcome))

        # Detect patterns
        alert = self._detect_patterns(outcome)

        if alert:
            self._stats.alerts_generated += 1
            self._dispatch_alert(alert)

        # --- CORTEX SIGNAL (non-invasive) ---
        # Send observation to Cortex for correlation
        if self._cortex_callback:
            try:
                from vibe_core.naga.cortex.signals import CommitSignal

                # Map outcome to pattern name
                pattern_map = {
                    CommitOutcome.SUCCESS: "SUCCESS",
                    CommitOutcome.SKIPPED: "SKIPPED",
                    CommitOutcome.DEFERRED: "DEFERRAL",
                    CommitOutcome.HEALED: "HEALED",
                    CommitOutcome.PANIC_DUMPED: "PANIC",
                }
                pattern = pattern_map.get(outcome, "UNKNOWN")

                signal = CommitSignal(
                    source_id="commit_watcher",
                    pattern=pattern,
                    commit_sha=getattr(result, "sha", "") or "",
                    files_changed=tuple(getattr(result, "files_changed", []) or []),
                    severity=alert.severity if alert else "INFO",
                )
                self._cortex_callback(signal)
            except Exception:
                pass  # Silent fail - observer must not crash

        return alert

    # =========================================================================
    # PATTERN DETECTION
    # =========================================================================

    def _detect_patterns(self, current_outcome: "CommitOutcome") -> Optional[CommitAlert]:
        """
        Detect problematic patterns.

        Returns alert if pattern detected.
        """
        from vibe_core.state.commit_authority import CommitOutcome

        now = time.time()

        # Check PANIC_PATTERN
        if current_outcome == CommitOutcome.PANIC_DUMPED:
            panic_count = self._count_recent_outcomes(
                CommitOutcome.PANIC_DUMPED,
                window_seconds=self.PANIC_WINDOW_SECONDS,
            )
            if panic_count >= self.PANIC_THRESHOLD:
                return CommitAlert(
                    alert_type="PANIC_PATTERN",
                    severity="CRITICAL",
                    message=f"Panic dump pattern detected: {panic_count} panics in {self.PANIC_WINDOW_SECONDS}s",
                    details={
                        "panic_count": panic_count,
                        "window_seconds": self.PANIC_WINDOW_SECONDS,
                    },
                )

        # Check STAGNATION
        if self._stats.last_success_at:
            time_since_success = now - self._stats.last_success_at
            if time_since_success > self.STAGNATION_SECONDS:
                # Only alert once per stagnation period
                if self._stats.total_observed % 10 == 0:  # Throttle
                    return CommitAlert(
                        alert_type="STAGNATION",
                        severity="WARNING",
                        message=f"No successful commits in {int(time_since_success)}s",
                        details={
                            "seconds_since_success": time_since_success,
                            "threshold_seconds": self.STAGNATION_SECONDS,
                        },
                    )

        # Check DEFERRAL_LOOP
        if self._consecutive_deferrals >= self.DEFERRAL_THRESHOLD:
            return CommitAlert(
                alert_type="DEFERRAL_LOOP",
                severity="WARNING",
                message=f"Decision paralysis: {self._consecutive_deferrals} consecutive deferrals",
                details={
                    "consecutive_deferrals": self._consecutive_deferrals,
                    "threshold": self.DEFERRAL_THRESHOLD,
                },
            )

        # Check CONFLICT_DRIFT
        if self._stats.total_observed >= 10:  # Need minimum sample
            healed_rate = self._stats.healed_count / self._stats.total_observed
            if healed_rate > self.CONFLICT_RATE_THRESHOLD:
                # Only alert periodically
                if self._stats.total_observed % 20 == 0:  # Throttle
                    return CommitAlert(
                        alert_type="CONFLICT_DRIFT",
                        severity="WARNING",
                        message=f"High conflict rate: {healed_rate:.1%} commits require healing",
                        details={
                            "healed_count": self._stats.healed_count,
                            "total_count": self._stats.total_observed,
                            "rate": healed_rate,
                        },
                    )

        return None

    def _count_recent_outcomes(
        self,
        outcome: "CommitOutcome",
        window_seconds: float,
    ) -> int:
        """Count occurrences of outcome in recent window."""
        now = time.time()
        cutoff = now - window_seconds

        count = 0
        for ts, o in self._recent_outcomes:
            if ts >= cutoff and o == outcome:
                count += 1

        return count

    # =========================================================================
    # ALERT DISPATCH
    # =========================================================================

    def add_alert_handler(self, handler: callable) -> None:
        """Add a handler to be called when alerts are generated."""
        self._alert_handlers.append(handler)

    def _dispatch_alert(self, alert: CommitAlert) -> None:
        """Dispatch alert to handlers and log to Ledger."""
        # Log it
        if alert.severity == "CRITICAL":
            logger.error(f"[COMMIT_WATCHER] {alert.alert_type}: {alert.message}")
        else:
            logger.warning(f"[COMMIT_WATCHER] {alert.alert_type}: {alert.message}")

        # Record to Ledger via Sesha
        self._audit(f"COMMIT_ALERT_{alert.alert_type}", alert.to_dict())

        # Call handlers
        for handler in self._alert_handlers:
            try:
                handler(alert)
            except Exception as e:
                logger.debug(f"[COMMIT_WATCHER] Handler error: {e}")

        # Bite via Takshaka for critical alerts
        if alert.severity == "CRITICAL" and self._takshaka:
            try:
                from vibe_core.protocols.naga import VajraViolation

                violation = VajraViolation(
                    violation_type=f"COMMIT_{alert.alert_type}",
                    source="commit_watcher",
                    details=alert.to_dict(),
                )
                self._takshaka.bite(violation)
            except Exception:
                pass  # Silent fail

    # =========================================================================
    # AUDIT HELPER
    # =========================================================================

    def _audit(self, event_type: str, data: Any) -> None:
        """Record to Ledger via Sesha."""
        if not self._sesha:
            return

        try:
            if hasattr(self._sesha, "_ledger") and self._sesha._ledger:
                details = data if isinstance(data, dict) else {"result": str(data)}
                self._sesha._ledger.record_event(
                    event_type=f"NAGA_{event_type}",
                    agent_id="commit_watcher",
                    details=details,
                )
        except Exception:
            pass  # Silent fail

    # =========================================================================
    # STATUS
    # =========================================================================

    def get_stats(self) -> Dict[str, Any]:
        """Get commit watching statistics."""
        return {
            "enabled": self._enabled,
            "consecutive_deferrals": self._consecutive_deferrals,
            "recent_window_size": len(self._recent_outcomes),
            **self._stats.to_dict(),
        }

    def reset_stats(self) -> None:
        """Reset statistics (for testing)."""
        self._stats = CommitStats()
        self._recent_outcomes.clear()
        self._consecutive_deferrals = 0


# =============================================================================
# INTEGRATION HELPER
# =============================================================================


def wrap_commit_with_watcher(
    commit_func: callable,
    watcher: NagaCommitWatcher,
) -> callable:
    """
    Wrap a commit function to automatically observe results.

    Usage:
        authority.commit = wrap_commit_with_watcher(authority.commit, watcher)
    """

    def wrapped(*args, **kwargs):
        result = commit_func(*args, **kwargs)
        watcher.observe(result)
        return result

    return wrapped
