"""
THE ARTISAN - Media & Tech Ops Agent.
Part of the Steward Protocol Federation.

Role: Handyman / Blacksmith
Mission: Polish, Format, and Brand assets generated by HERALD.

REFACTORED: Tool Protocol Compliant
- NO tool instances owned by agent
- ALL tools accessed via kernel (self.system.execute_tool)
"""

import logging
from typing import Any, Dict

# VibeOS Integration
from vibe_core import Task, VibeAgent
from vibe_core.state.schema import ExecutionResult

# Constitutional Oath Mixin (Golden Template Pattern)
from vibe_core.steward import OathMixin

# Setup logging
logging.basicConfig(level=logging.INFO, format="%(asctime)s - %(name)s - %(levelname)s - %(message)s")
logger = logging.getLogger("ARTISAN_AGENT")


class ArtisanCartridge(VibeAgent, OathMixin):
    """
    The Artisan Agent Cartridge.
    Specialized in media processing and technical operations.

    Tool Protocol Compliant:
    - NO tool instances in __init__
    - Tools accessed via self.system.execute_tool()
    """

    def __init__(self):
        """Initialize the Artisan as a VibeAgent."""
        # Initialize VibeAgent base class
        super().__init__(
            agent_id="artisan",
            name="ARTISAN",
            version="2.0.0",  # Bumped for Tool Protocol refactor
            author="Steward Protocol",
            description="Media and technical operations agent",
            domain="MEDIA",
            capabilities=["media_processing", "image_optimization", "asset_branding"],
        )

        logger.info("🔨 THE ARTISAN is online (Tool Protocol v2.0).")

        # Golden Template Pattern: Initialize Constitutional Oath
        self.oath_mixin_init(self.agent_id)
        self.oath_sworn = True
        logger.info("✅ ARTISAN has sworn the Constitutional Oath")

        # ALL TOOLS: Accessed via kernel (self.system.execute_tool)
        # - artisan.media (MediaTool)

        logger.info("✅ ARTISAN: Ready for operation (NO tool instances owned)")

    def process_media(self, file_path: str, output_path: str = None) -> str:
        """
        Process a media file (Crop, Brand, Optimize).

        NEW: Uses kernel-managed tools via self.system.execute_tool()

        Args:
            file_path: Path to raw media file
            output_path: Optional output path

        Returns:
            str: Path to processed file (or original if failed)
        """
        logger.info(f"🔨 Artisan received job: Process {file_path}")

        # CRITICAL: Tool call goes through kernel
        result = self.system.execute_tool(
            "artisan.media",
            {"action": "process_image", "image_path": file_path, "output_path": output_path},
        )

        if result.success:
            processed_path = result.output.get("processed_path")
            logger.info(f"✅ Artisan finished job: {processed_path}")
            return processed_path
        else:
            logger.warning(f"⚠️  Artisan processing failed: {result.error}")
            return file_path

    # ==================== VIBEOS AGENT INTERFACE ====================

    def process(self, task: Task) -> ExecutionResult:
        """
        Process a task from the VibeKernel scheduler.

        ARTISAN responds to media processing tasks:
        - "process_media": Process a media file
        """
        try:
            action = task.payload.get("action") or task.payload.get("command")
            logger.info(f"🔨 ARTISAN processing task: {action}")

            if action == "process_media":
                file_path = task.payload.get("file_path")
                output_path = task.payload.get("output_path")
                if not file_path:
                    return ExecutionResult(success=False, error="file_path required")
                result = self.process_media(file_path, output_path)
                return ExecutionResult(success=True, result={"result": result})
            else:
                return ExecutionResult(success=False, error=f"Unknown action: {action}")
        except Exception as e:
            logger.error(f"❌ ARTISAN processing error: {e}")
            import traceback

            logger.error(traceback.format_exc())
            return ExecutionResult(success=False, error=str(e))

    def get_manifest(self):
        """Return agent manifest for kernel registry."""
        from vibe_core.agent_protocol import AgentManifest

        return AgentManifest(
            agent_id="artisan",
            name="ARTISAN",
            version=self.version if hasattr(self, "version") else "2.0.0",
            author="Steward Protocol",
            description="Media and technical operations agent",
            domain="MEDIA",
            capabilities=["media_operations", "content_creation"],
        )

    def report_status(self) -> Dict[str, Any]:
        """Report ARTISAN status (VibeAgent interface)."""
        return {
            "agent_id": "artisan",
            "name": "ARTISAN",
            "status": "RUNNING",
            "domain": "MEDIA_OPS",
            "capabilities": self.capabilities,
            "description": "Media and technical operations agent (Tool Protocol v2.0)",
        }
