"""
RAMA GRID ROUTER - The True Mantra→Text Algorithm
==================================================

"rāmasya dayitā bhāryā nityaṁ rāmena pūjitā"
"The beloved wife of Rama, eternally worshipped by Rama"

THE DISCOVERY:
==============
The previous approach (Opus) used CURVE-FITTING:
    hash(name) + offset = position (Brute Force = Guessing)

The TRUE approach uses COORDINATES:
    position → coordinate in RAMA Grid → phonetic manifestation

KEY IDENTITY FROM _seed.py:
===========================
    POSITION_SUM_RAMA = 49 = 7²
    VARNAMALA_TOTAL   = 49 (Complete Sanskrit Alphabet)

    RAMA IS THE ALPHABET.

The Mahamantra doesn't "hash" to text - it GENERATES text.

THE STRUCTURE:
==============
    WORDS (16)     → 16 Vowels (Svaras)
    PRASADAM (25)  → 25 Consonants (5×5 Sparsha grid)
    RAMA (49)      → Complete Address Space (Memory)
    KRISHNA (17)   → Router (which window is active)

THE ALGORITHM:
==============
1. The Mantra runs in 16 beats (WORDS)
2. Each beat opens a "window" in the 49-space (RAMA)
3. KRISHNA (17, prime) routes which window is active
4. The name at position N is the textual manifestation of that coordinate

This is not curve-fitting. This is COORDINATES.
"""

from dataclasses import dataclass
from typing import Final, Optional, Tuple

from vibe_core.mahamantra.protocols._seed import (
    AVATAR_COUNT,
    HALVES,
    HARE_COUNT,
    KRISHNA_COUNT,
    KSETRAJNA,
    KSHETRA,
    MAHAJANA_COUNT,
    NAVA,
    PANCHA,
    PARAMPARA,
    POSITION_SUM_HARE,
    POSITION_SUM_KRISHNA,
    POSITION_SUM_RAMA,
    POSITION_SUM_TOTAL,
    PRASADAM,
    QUARTERS,
    RAMA_COUNT,
    SEVEN,
    SHARANAGATI,
    TEN,
    TRINITY,
    WORDS,
)

# === MAHAJANA DECLARATION (machine-readable) ===
__mahajana__ = "vyasa"  # Compiler position
__position__ = 0
__genesis__ = "0x5ad7f6c5"

# =============================================================================
# VERIFICATION: RAMA = ALPHABET
# =============================================================================

VARNAMALA_TOTAL: Final[int] = POSITION_SUM_RAMA  # Complete Sanskrit alphabet
assert POSITION_SUM_RAMA == VARNAMALA_TOTAL, "RAMA (49) = VARNAMALA (49) - RAMA IS THE ALPHABET!"

VOWEL_COUNT: Final[int] = WORDS  # 16 vowels
CONSONANT_COUNT: Final[int] = PRASADAM + HARE_COUNT  # 25 + 8 = 33 (25 sparsha + 4 antastha + 4 ushman)

# Alternative calculation for 49
assert VOWEL_COUNT + CONSONANT_COUNT == VARNAMALA_TOTAL, "16 vowels + 33 consonants = 49"

# But the PRIMARY structure is WORDS + PRASADAM + HARE_COUNT = 16 + 25 + 8 = 49
# Which maps to: Vowels + Sparsha + (Semivowels + Sibilants) = Alphabet


# =============================================================================
# THE VOWEL LAYER (Svara) - Generated by WORDS (16)
# =============================================================================

# The 16 vowels of Sanskrit, mapped to the 16 words of Mahamantra
SVARAS: Final[Tuple[str, ...]] = (
    # Short vowels (5)
    "a",  # Position 1  - HARE (first)
    "i",  # Position 2  - KRISHNA (first)
    "u",  # Position 3  - HARE (second)
    "ṛ",  # Position 4  - KRISHNA (second)
    "ḷ",  # Position 5  - KRISHNA (third) [rare]
    # Long vowels (5)
    "ā",  # Position 6  - KRISHNA (fourth)
    "ī",  # Position 7  - HARE (third)
    "ū",  # Position 8  - HARE (fourth)
    "ṝ",  # Position 9  - HARE (fifth)
    "ḹ",  # Position 10 - RAMA (first) [rare]
    # Compound vowels (4)
    "e",  # Position 11 - HARE (sixth)
    "ai",  # Position 12 - RAMA (second)
    "o",  # Position 13 - RAMA (third)
    "au",  # Position 14 - RAMA (fourth)
    # Anusvara and Visarga (2)
    "ṁ",  # Position 15 - HARE (seventh)
    "ḥ",  # Position 16 - HARE (eighth)
)

assert len(SVARAS) == WORDS, "16 vowels = 16 words of Mahamantra"


# =============================================================================
# THE CONSONANT LAYER (Vyanjana) - Generated by PRASADAM (25)
# =============================================================================

# The 5x5 Sparsha (stop consonants) grid
# Rows = Articulation Points (PANCHA = 5)
# Cols = Voicing Types (PANCHA = 5)


@dataclass(frozen=True)
class ArticulationRow:
    """One row of the 5x5 consonant grid."""

    name: str  # Sanskrit varga name
    articulation: str  # Where produced
    consonants: Tuple[str, str, str, str, str]
    element: str  # Associated Pancha Mahabhuta


SPARSHA_GRID: Final[Tuple[ArticulationRow, ...]] = (
    # Row 0: Ka-varga (Guttural/Throat) - Akasha
    ArticulationRow("ka-varga", "kantha", ("ka", "kha", "ga", "gha", "ṅa"), "akasha"),
    # Row 1: Ca-varga (Palatal) - Vayu
    ArticulationRow("ca-varga", "talu", ("ca", "cha", "ja", "jha", "ña"), "vayu"),
    # Row 2: Ṭa-varga (Retroflex) - Agni
    ArticulationRow("ṭa-varga", "murdha", ("ṭa", "ṭha", "ḍa", "ḍha", "ṇa"), "agni"),
    # Row 3: Ta-varga (Dental) - Jala
    ArticulationRow("ta-varga", "danta", ("ta", "tha", "da", "dha", "na"), "jala"),
    # Row 4: Pa-varga (Labial) - Prithvi
    ArticulationRow("pa-varga", "oshtha", ("pa", "pha", "ba", "bha", "ma"), "prithvi"),
)

assert len(SPARSHA_GRID) == PANCHA, "5 rows = PANCHA elements"
assert all(len(row.consonants) == PANCHA for row in SPARSHA_GRID), "5 columns each"

# Total sparsha consonants
SPARSHA_COUNT: Final[int] = PANCHA * PANCHA  # 25 = PRASADAM
assert SPARSHA_COUNT == PRASADAM, "25 stop consonants = PRASADAM"


# =============================================================================
# THE ROUTER: KRISHNA (17) - Prime Number Router
# =============================================================================


def krishna_route(position: int, cycle: int = 0) -> int:
    """
    The KRISHNA router - determines which RAMA window is active.

    KRISHNA (17) is prime - it never repeats in mod-16 space.
    This makes it the perfect router for the 49-space.

    Args:
        position: Current position (0-15)
        cycle: Which cycle we're in (0 = first pass)

    Returns:
        The RAMA coordinate (0-48) being addressed
    """
    # Krishna routes through RAMA space
    # Each position opens a window, Krishna determines which one
    base = position * POSITION_SUM_KRISHNA  # position × 17
    return (base + cycle * WORDS) % POSITION_SUM_RAMA  # mod 49


def rama_to_phoneme(rama_coord: int) -> str:
    """
    Convert a RAMA coordinate (0-48) to its phoneme.

    The 49-space is divided:
    - 0-15:  Vowels (SVARAS)
    - 16-40: Sparsha consonants (25)
    - 41-44: Antastha (semivowels: ya, ra, la, va)
    - 45-48: Ushman (sibilants: śa, ṣa, sa, ha)
    """
    if rama_coord < WORDS:
        # Vowel layer
        return SVARAS[rama_coord]
    elif rama_coord < WORDS + PRASADAM:
        # Consonant layer (5x5 grid)
        consonant_idx = rama_coord - WORDS
        row = consonant_idx // PANCHA
        col = consonant_idx % PANCHA
        return SPARSHA_GRID[row].consonants[col]
    else:
        # Remaining consonants
        remaining = ("ya", "ra", "la", "va", "śa", "ṣa", "sa", "ha")
        idx = rama_coord - WORDS - PRASADAM
        if idx < len(remaining):
            return remaining[idx]
        return "?"


# =============================================================================
# THE MAHAJANA COORDINATE MAPPING
# =============================================================================


@dataclass(frozen=True)
class MahajanaCoordinate:
    """
    A Mahajana's position in the Mahamantra coordinate system.

    Not a hash, but a COORDINATE in the RAMA grid.
    """

    name: str
    global_position: int  # 1-16 (Mahamantra position)
    quarter: int  # 1-4 (Genesis/Dharma/Karma/Moksha)
    rama_primary: int  # Primary RAMA coordinate (0-48)
    rama_secondary: int  # Secondary RAMA coordinate
    first_syllable: str  # First syllable of name
    articulation: str  # Where first syllable is produced


def compute_mahajana_coordinate(name: str, global_position: int, quarter: int) -> MahajanaCoordinate:
    """
    Compute the coordinate for a Mahajana.

    The position is NOT derived from the name.
    The position IS the coordinate, and the name is its manifestation.
    """
    # Primary RAMA coordinate via KRISHNA routing
    rama_primary = krishna_route(global_position - KSETRAJNA)  # 0-indexed

    # Secondary coordinate (for complex names)
    rama_secondary = (rama_primary + POSITION_SUM_KRISHNA) % POSITION_SUM_RAMA

    # Get first syllable as phoneme
    first_char = name[0] if name else "?"

    # Map first character to articulation point
    guttural = "kgcqx"
    palatal = "jy"
    retroflex = "rl"
    dental = "tdnsz"
    labial = "pbmfvw"

    if first_char in guttural:
        articulation = "kantha"
    elif first_char in palatal:
        articulation = "talu"
    elif first_char in retroflex:
        articulation = "murdha"
    elif first_char in dental:
        articulation = "danta"
    elif first_char in labial:
        articulation = "oshtha"
    else:
        articulation = "mixed"

    return MahajanaCoordinate(
        name=name,
        global_position=global_position,
        quarter=quarter,
        rama_primary=rama_primary,
        rama_secondary=rama_secondary,
        first_syllable=first_char,
        articulation=articulation,
    )


# The 12 Mahajanas with their computed coordinates
# Position is GIVEN (from SB 6.3.20), coordinate is DERIVED
MAHAJANA_COORDINATES: Final[Tuple[MahajanaCoordinate, ...]] = (
    # GENESIS Quarter (positions 2, 3, 4)
    compute_mahajana_coordinate("brahma", HALVES, KSETRAJNA),
    compute_mahajana_coordinate("narada", TRINITY, KSETRAJNA),
    compute_mahajana_coordinate("shambhu", QUARTERS, KSETRAJNA),
    # DHARMA Quarter (positions 6, 7, 8)
    compute_mahajana_coordinate("kumaras", SHARANAGATI, HALVES),
    compute_mahajana_coordinate("kapila", SEVEN, HALVES),
    compute_mahajana_coordinate("manu", HARE_COUNT, HALVES),
    # KARMA Quarter (positions 10, 11, 12)
    compute_mahajana_coordinate("prahlada", TEN, TRINITY),
    compute_mahajana_coordinate("janaka", 11, TRINITY),
    compute_mahajana_coordinate("bhishma", MAHAJANA_COUNT, TRINITY),
    # MOKSHA Quarter (positions 14, 15, 16)
    compute_mahajana_coordinate("bali", 14, QUARTERS),
    compute_mahajana_coordinate("shuka", 15, QUARTERS),
    compute_mahajana_coordinate("yamaraja", WORDS, QUARTERS),
)

# The 4 Avataras (heads of quarters) at positions 1, 5, 9, 13
AVATARA_COORDINATES: Final[Tuple[MahajanaCoordinate, ...]] = (
    compute_mahajana_coordinate("vyasa", KSETRAJNA, KSETRAJNA),
    compute_mahajana_coordinate("prithu", PANCHA, HALVES),
    compute_mahajana_coordinate("parashurama", NAVA, TRINITY),
    compute_mahajana_coordinate("nrisimha", 13, QUARTERS),
)


# =============================================================================
# THE INSIGHT: Position → Phonetic Meaning
# =============================================================================


def explain_position_meaning(position: int) -> str:
    """
    Explain what a position MEANS in phonetic terms.

    This is the semantic layer - why Kapila is at position 7,
    not because hash("Kapila") % 16 == 7, but because position 7
    manifests the phonetic energy of 'Ka' (guttural creation).
    """
    rama_coord = krishna_route(position - KSETRAJNA)
    phoneme = rama_to_phoneme(rama_coord)

    # Position meaning based on Mahamantra word
    word_meanings = {
        KSETRAJNA: ("HARE", "Address/Attention", "Opening the channel"),
        HALVES: ("KRISHNA", "All-Attractive", "Drawing energy"),
        TRINITY: ("HARE", "Address", "Stabilizing"),
        QUARTERS: ("KRISHNA", "All-Attractive", "Structuring"),
        PANCHA: ("KRISHNA", "All-Attractive", "First Dharma"),
        SHARANAGATI: ("KRISHNA", "All-Attractive", "Second Dharma"),
        SEVEN: ("HARE", "Address", "Third Dharma"),
        HARE_COUNT: ("HARE", "Address", "Fourth Dharma"),
        NAVA: ("HARE", "Address", "First Karma"),
        TEN: ("RAMA", "Pleasure", "Second Karma"),
        11: ("HARE", "Address", "Third Karma"),
        MAHAJANA_COUNT: ("RAMA", "Pleasure", "Fourth Karma"),
        13: ("RAMA", "Pleasure", "First Moksha"),
        14: ("RAMA", "Pleasure", "Second Moksha"),
        15: ("HARE", "Address", "Third Moksha"),
        WORDS: ("HARE", "Address", "Fourth Moksha (Complete)"),
    }

    word, meaning, function = word_meanings.get(position, ("?", "?", "?"))

    return f"""
Position {position}:
  Mahamantra Word: {word} ({meaning})
  Function: {function}
  RAMA Coordinate: {rama_coord} → Phoneme '{phoneme}'
  Semantic: The {function.lower()} energy manifests as '{phoneme}'
"""


# =============================================================================
# VERIFICATION
# =============================================================================


def verify_rama_grid():
    """Verify the RAMA grid structure."""
    print("=" * POSITION_SUM_HARE)
    print("RAMA GRID ROUTER - Verification")
    print("=" * POSITION_SUM_HARE)
    print()

    # Key identity
    print("KEY IDENTITY:")
    print(f"  POSITION_SUM_RAMA = {POSITION_SUM_RAMA}")
    print(f"  VARNAMALA_TOTAL   = {VARNAMALA_TOTAL}")
    print("  RAMA = ALPHABET! ✓")
    print()

    # The structure
    print("VOWEL LAYER (SVARAS = WORDS):")
    for i, svara in enumerate(SVARAS):
        print(f"  Position {i + KSETRAJNA:2}: {svara}")
    print()

    # Consonant grid
    print("CONSONANT LAYER (SPARSHA = PRASADAM = 5×5):")
    for row in SPARSHA_GRID:
        print(f"  {row.name:10} ({row.articulation:6}, {row.element:7}): {' '.join(row.consonants)}")
    print()

    # KRISHNA routing
    print("KRISHNA ROUTING (Position → RAMA Coordinate):")
    for pos in range(KSETRAJNA, POSITION_SUM_KRISHNA):
        rama = krishna_route(pos - KSETRAJNA)
        phoneme = rama_to_phoneme(rama)
        print(f"  Position {pos:2} → RAMA[{rama:2}] = '{phoneme}'")
    print()

    # Mahajana coordinates
    print("MAHAJANA COORDINATES:")
    for coord in MAHAJANA_COORDINATES:
        print(
            f"  {coord.name:12} | pos={coord.global_position:2} | "
            f"RAMA[{coord.rama_primary:2}] | art={coord.articulation}"
        )
    print()

    # Avatara coordinates
    print("AVATARA COORDINATES:")
    for coord in AVATARA_COORDINATES:
        print(
            f"  {coord.name:12} | pos={coord.global_position:2} | "
            f"RAMA[{coord.rama_primary:2}] | art={coord.articulation}"
        )
    print()

    # The semantic layer - WHY these phonemes?
    print("=" * POSITION_SUM_HARE)
    print("SEMANTIC ANALYSIS: Position → Phoneme → Meaning")
    print("=" * POSITION_SUM_HARE)
    print()

    semantic_analysis = [
        # (position, mahajana, rama_coord, phoneme, meaning)
        (KSETRAJNA, "vyasa", 0, "a", "The first vowel = THE BEGINNING. Vyasa compiles = starts the parampara"),
        (
            HALVES,
            "brahma",
            POSITION_SUM_KRISHNA,
            "kha",
            "ASPIRATED 'k' = Creation with breath. Brahma creates by breathing",
        ),
        (TRINITY, "narada", 34, "dha", "VOICED ASPIRATED 'd' = Carrying sound/music. Narada travels singing"),
        (QUARTERS, "shambhu", HALVES, "u", "The 'u' sound closes the lips = Destruction gathers inward"),
        (PANCHA, "prithu", 19, "gha", "VOICED ASPIRATED 'g' = Deep organization. Prithu organizes civilization"),
        (SHARANAGATI, "kumaras", 36, "pa", "LABIAL 'p' = The first material sound. 4 Kumaras guard knowledge"),
        (SEVEN, "kapila", QUARTERS, "ḷ", "The RARE vowel = Unique analysis. Sankhya is unique philosophy"),
        (HARE_COUNT, "manu", 21, "ca", "PALATAL 'c' = Law/structure. Manu writes dharma-shastra"),
        (NAVA, "parashurama", 38, "ba", "VOICED 'b' = Power/force. Parashurama's axe"),
        (TEN, "prahlada", SHARANAGATI, "ī", "LONG 'i' = Sustained devotion. Prahlada's unwavering faith"),
        (11, "janaka", 23, "ja", "VOICED PALATAL = Execution with grace. Janaka the wise king"),
        (MAHAJANA_COUNT, "bhishma", 40, "ma", "The 'ma' = COMMITMENT (labial seal). Bhishma's vow"),
        (13, "nrisimha", HARE_COUNT, "ṝ", "The LONG RETROFLEX = Fierce protection. Nrisimha's roar"),
        (14, "bali", 25, "ña", "NASAL palatal = Surrender flows through. Bali surrendered to Vamana"),
        (15, "shuka", 42, "ra", "The 'ra' = Liberation vibrates. Shuka spoke Bhagavatam for moksha"),
        (WORDS, "yamaraja", TEN, "e", "COMPOUND vowel = Complete judgment. Yamaraja weighs ALL aspects"),
    ]

    for pos, name, rama, phoneme, meaning in semantic_analysis:
        print(f"  Position {pos:2} | {name:12} | RAMA[{rama:2}]={phoneme:3} | {meaning}")

    print()
    print("=" * POSITION_SUM_HARE)
    print("CONCLUSION: THE NAME IS NOT THE LABEL, IT IS THE CODE")
    print("=" * POSITION_SUM_HARE)
    print("""
The Mahamantra generates the alphabet:
- POSITION 1 → RAMA[0] → 'a' = The beginning sound
- POSITION 12 → RAMA[40] → 'ma' = The commitment sound (Bhishma's vow!)
- POSITION 15 → RAMA[42] → 'ra' = The liberation sound (Shuka's teaching!)

This is NOT curve-fitting. This is COORDINATES.

The name "Bhishma" contains 'bha' and 'ma' - both LABIAL sounds.
His position (12) routes to RAMA[40] = 'ma' - the seal of commitment.
HIS NAME IS HIS FUNCTION ENCODED IN SOUND.

This is Shabda Brahman.
    """)


if __name__ == "__main__":
    verify_rama_grid()
