"""
REPORT.md Parser - Extracts violations from tech debt reports.

Parses the standardized REPORT.md format generated by Watchman inspections.

Supported patterns:
    - Section headers: "### A-P0: KRITISCH"
    - Individual findings: "#### A-P0-1: VFS Sandbox Escape"
    - PROMPT.md violations from summary tables
"""

import re
from pathlib import Path
from typing import List

from vibe_core.ouroboros.ingestion import ViolationRecord, ViolationSource
from vibe_core.ouroboros.parsers.base import BaseViolationParser


class ReportMdParser(BaseViolationParser):
    """
    Parser for REPORT.md and similar tech debt audit files.

    Extracts:
        - Priority violations (A-P0-*, B-P0-*, etc.)
        - PROMPT.md metric violations
        - General audit findings
    """

    name = "report_md"
    patterns = ["**/REPORT*.md", "**/*AUDIT*.md", "**/*_audit.md"]

    # Severity mapping from priority levels
    SEVERITY_MAP = {
        "P0": "CRITICAL",
        "P1": "HIGH",
        "P2": "MEDIUM",
        "P3": "LOW",
    }

    def can_parse(self, path: Path) -> bool:
        """Check if file is a valid report/audit markdown."""
        if not path.exists():
            return False
        if path.suffix.lower() != ".md":
            return False

        # Check for common report patterns in filename
        name_upper = path.name.upper()
        return any(keyword in name_upper for keyword in ["REPORT", "AUDIT", "DEBT", "REVIEW"])

    def parse(self, path: Path) -> List[ViolationRecord]:
        """Parse violations from REPORT.md format."""
        violations = []

        if not path.exists():
            return violations

        content = path.read_text()

        # Pattern 1: Priority sections (e.g., "### A-P0: KRITISCH")
        violations.extend(self._parse_priority_sections(content))

        # Pattern 2: PROMPT.md violations from summary tables
        violations.extend(self._parse_prompt_violations(content))

        return violations

    def _parse_priority_sections(self, content: str) -> List[ViolationRecord]:
        """
        Parse priority-based violation sections.

        Format:
            ### A-P0: KRITISCH
            #### A-P0-1: VFS Sandbox Escape
            **Datei:** `vibe_core/vfs/sandbox.py:42-50`
        """
        violations = []

        # Match section headers: ### A-P0: KRITISCH
        priority_sections = re.findall(
            r"###\s+([A-Z]-P[0-3]):\s+(\w+)[^\n]*\n(.+?)(?=###|\Z)",
            content,
            re.DOTALL,
        )

        for section_id, severity_word, section_content in priority_sections:
            # Match individual findings within section
            # #### A-P0-1: VFS Sandbox Escape
            # **Datei:** `vibe_core/vfs/sandbox.py:42-50`
            pattern = r"####\s+(" + re.escape(section_id) + r"-\d+):\s+([^\n]+)\n.*?\*\*Datei:\*\*\s+`([^`]+)`"
            findings = re.findall(pattern, section_content, re.DOTALL)

            for finding_id, title, file_path in findings:
                # Parse file path and line number
                parsed_path, line = self._parse_file_location(file_path)

                # Map priority to severity
                priority = section_id.split("-")[1]
                severity = self.SEVERITY_MAP.get(priority, "MEDIUM")

                # A = VISNU protected, can't fix automatically
                has_remedy = not section_id.startswith("A")

                violations.append(
                    ViolationRecord(
                        source=ViolationSource.WATCHMAN,
                        rule_id=f"REPORT:{finding_id}",
                        file_path=parsed_path,
                        line=line,
                        message=title.strip(),
                        severity=severity,
                        has_remedy=has_remedy,
                        context={
                            "section": section_id,
                            "source": "REPORT.md",
                            "parser": self.name,
                        },
                    )
                )

        return violations

    def _parse_prompt_violations(self, content: str) -> List[ViolationRecord]:
        """
        Parse PROMPT.md violations from summary tables.

        Format:
            | **Metric Name** | 42 | Description |
        """
        violations = []

        # Match table rows: | **Metric** | Count | Description |
        table_rows = re.findall(r"\|\s+\*\*([^*]+)\*\*\s+\|\s+(\d+)\s+\|\s+([^|]+)\s+\|", content)

        for metric, count_str, description in table_rows:
            count = int(count_str)
            if count == 0:
                continue

            # Determine severity based on count and description
            is_critical = "KRITISCH" in description.upper()
            severity = "HIGH" if is_critical or count > 100 else "MEDIUM"

            violations.append(
                ViolationRecord(
                    source=ViolationSource.WATCHMAN,
                    rule_id=f"PROMPT:{metric.strip().replace(' ', '_')}",
                    file_path="vibe_core/",  # Codebase-wide metric
                    line=None,
                    message=f"{count} instances: {description.strip()}",
                    severity=severity,
                    has_remedy=True,
                    context={
                        "metric": metric.strip(),
                        "count": count,
                        "source": "REPORT.md",
                        "parser": self.name,
                    },
                )
            )

        return violations

    def _parse_file_location(self, file_path: str) -> tuple:
        """
        Parse file path and line number from location string.

        Examples:
            "vibe_core/foo.py:42-50" -> ("vibe_core/foo.py", 42)
            "vibe_core/foo.py" -> ("vibe_core/foo.py", None)
        """
        if ":" in file_path:
            parts = file_path.split(":")
            path = parts[0]
            line_part = parts[1].split("-")[0] if "-" in parts[1] else parts[1]
            try:
                line = int(line_part)
            except ValueError:
                line = None
            return path, line
        return file_path, None
