"""
Watchman JSON Parser - Extracts violations from watchman inspection reports.

Parses watchman_report.json files generated by the Watchman AST inspector.
"""

import json
from pathlib import Path
from typing import Any, Dict, List

from vibe_core.ouroboros.ingestion import ViolationRecord, ViolationSource
from vibe_core.ouroboros.parsers.base import BaseViolationParser


class WatchmanJsonParser(BaseViolationParser):
    """
    Parser for watchman_report.json files.

    These are the JSON outputs from Watchman AST inspections.
    """

    name = "watchman_json"
    patterns = ["**/watchman_report.json", "**/*_violations.json", "**/*_inspection.json"]

    def can_parse(self, path: Path) -> bool:
        """Check if file is a valid Watchman JSON report."""
        if not path.exists():
            return False
        if path.suffix.lower() != ".json":
            return False

        # Try to parse and check for expected structure
        try:
            data = json.loads(path.read_text())
            # Watchman reports have "violations" key or are a list
            return "violations" in data or isinstance(data, list)
        except (json.JSONDecodeError, OSError):
            return False

    def parse(self, path: Path) -> List[ViolationRecord]:
        """Parse violations from Watchman JSON output."""
        violations = []

        if not path.exists():
            return violations

        try:
            data = json.loads(path.read_text())
        except json.JSONDecodeError:
            return violations

        # Handle dict with "violations" key
        if isinstance(data, dict):
            raw_violations = data.get("violations", [])
        else:
            raw_violations = data

        for v in raw_violations:
            violations.append(self._convert_violation(v))

        return violations

    def _convert_violation(self, v: Dict[str, Any]) -> ViolationRecord:
        """Convert raw JSON violation to ViolationRecord."""
        return ViolationRecord(
            source=ViolationSource.WATCHMAN,
            rule_id=v.get("rule_id", v.get("code", "UNKNOWN")),
            file_path=v.get("file_path", v.get("filename", "unknown")),
            line=v.get("line_number", v.get("line")),
            message=v.get("message", ""),
            severity=v.get("severity", "MEDIUM"),
            has_remedy=v.get("has_remedy", False),
            context={
                "source": "watchman_report.json",
                "parser": self.name,
                "raw": v,  # Preserve original data
            },
        )
