#!/usr/bin/env python3
"""
CIVIC Help Tool - Dynamic System Documentation Generator

This tool generates HELP.md by introspecting the running system:
1. Current Agent Status (from AGENTS.md registry)
2. How to Start the System (from existing binaries and scripts)
3. Governance State (from ledger and proposal history)
4. Architecture Overview (from CITYMAP.md)
5. Quick Reference for common operations

Philosophy:
"A system that documents itself is a system that evolves with truth.
No stale documentation, only live introspection."
"""

import json
from pathlib import Path
from typing import Dict, List, Any, Optional
from datetime import datetime, timezone
import re


class HelpTool:
    """
    CIVIC's Help Generator Tool.

    Creates HELP.md by reading the actual system state.
    This is the "onboarding manual" that never lies.
    """

    def __init__(self, root_dir: str = "."):
        """Initialize help tool with root directory."""
        self.root_dir = Path(root_dir)
        self.agents = []
        self.scripts = []
        self.ledger = None

    def discover_entry_points(self) -> List[Dict[str, str]]:
        """
        Find all executable entry points in scripts/.

        Returns:
            List of {name, path, description} dicts
        """
        scripts_dir = self.root_dir / "scripts"
        entry_points = []

        if not scripts_dir.exists():
            return entry_points

        for script_file in sorted(scripts_dir.glob("*.py")):
            if script_file.name == "__init__.py":
                continue

            name = script_file.stem
            description = self._extract_script_doc(script_file)

            entry_points.append({
                "name": name,
                "path": str(script_file.relative_to(self.root_dir)),
                "description": description
            })

        return entry_points

    def _extract_script_doc(self, script_file: Path) -> str:
        """Extract docstring from a script file."""
        try:
            content = script_file.read_text()
            match = re.search(r'"""(.*?)"""', content, re.DOTALL)
            if match:
                text = match.group(1).strip()
                first_line = text.split('\n')[0].strip()
                return first_line
            return ""
        except:
            return ""

    def load_agents_from_registry(self) -> List[Dict[str, str]]:
        """
        Extract agent list from AGENTS.md.

        Returns:
            List of agent names found in registry
        """
        agents_file = self.root_dir / "AGENTS.md"
        agents = []

        if not agents_file.exists():
            return agents

        try:
            content = agents_file.read_text()
            # Extract agent headers like "### 🤖 AGENTNAME"
            pattern = r'### 🤖 (\w+)'
            matches = re.findall(pattern, content)
            agents = list(dict.fromkeys(matches))  # Remove duplicates, preserve order
        except:
            pass

        return agents

    def check_ledger_status(self) -> Dict[str, Any]:
        """
        Check if ledger exists and return its status.

        Returns:
            Dict with ledger info or empty if not found
        """
        ledger_file = self.root_dir / ".steward" / "ledger.json"

        if not ledger_file.exists():
            return {
                "exists": False,
                "message": "Ledger not yet initialized. Run `python scripts/summon.py` to start."
            }

        try:
            data = json.loads(ledger_file.read_text())
            entries = data.get("chain_of_trust", {}).get("entries", [])

            return {
                "exists": True,
                "total_entries": len(entries),
                "initialized": True,
                "last_update": entries[-1].get("timestamp", "unknown") if entries else "never"
            }
        except:
            return {"exists": True, "readable": False}

    def generate_help_markdown(self) -> str:
        """
        Generate the complete HELP.md content.

        Returns:
            Markdown string for HELP.md
        """
        agents = self.load_agents_from_registry()
        entry_points = self.discover_entry_points()
        ledger_status = self.check_ledger_status()

        timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

        content = f"""# 📚 STEWARD PROTOCOL - SYSTEM HELP

**Auto-generated by CIVIC Help Tool**
**Last Updated:** {timestamp}
**Status:** 🟢 System Introspection Active

---

## 🚀 QUICK START

### 1️⃣ First Time? Start Here
```bash
# Initialize the system and create your ledger
python scripts/summon.py
```

### 2️⃣ Then, Explore the Agents
Read **[AGENTS.md](./AGENTS.md)** to see all registered agents in the system.

### 3️⃣ Understand the Architecture
Check **[CITYMAP.md](./CITYMAP.md)** to see how agents interact.

### 4️⃣ Review the Constitution
All agents operate under **[CONSTITUTION.md](./CONSTITUTION.md)** rules.

---

## 🏛️ CURRENT SYSTEM STATUS

### Agents Registered
"""

        if agents:
            for agent in agents:
                content += f"- **{agent}** ✅\n"
            content += f"\n**Total:** {len(agents)} agents\n"
        else:
            content += "- No agents discovered (run `python scripts/summon.py` first)\n"

        # Ledger status
        content += f"\n### Ledger Status\n"
        if ledger_status.get("exists"):
            if ledger_status.get("readable"):
                entries = ledger_status.get("total_entries", 0)
                last_update = ledger_status.get("last_update", "unknown")
                content += f"- **Status:** 🟢 Operational\n"
                content += f"- **Transactions Recorded:** {entries}\n"
                content += f"- **Last Update:** {last_update}\n"
            else:
                content += "- **Status:** ⚠️ Found but unreadable\n"
        else:
            content += f"- **Status:** 🔴 Not Initialized\n"
            content += f"- **Action Required:** Run `python scripts/summon.py` to initialize\n"

        # Available scripts
        content += f"""
---

## 📋 AVAILABLE SCRIPTS

How to interact with Agent City:

"""
        if entry_points:
            for script in entry_points:
                desc = f" — {script['description']}" if script['description'] else ""
                content += f"### `{script['name']}`\n"
                content += f"**Location:** `{script['path']}`{desc}\n\n"
                content += f"**Usage:**\n```bash\npython {script['path']}\n```\n\n"
        else:
            content += "No scripts found in `scripts/` directory.\n"

        # Core operations
        content += f"""---

## ⚙️ CORE OPERATIONS

### Starting the System
```bash
# Initialize and start
python scripts/summon.py
```

### Checking Status
```bash
# View current ledger and agent status
python scripts/verify_docs.py
```

### Viewing Agents
- See all agents: **[AGENTS.md](./AGENTS.md)**
- See architecture: **[CITYMAP.md](./CITYMAP.md)**

### Governance
- View constitution: **[CONSTITUTION.md](./CONSTITUTION.md)**
- Check governance: See "Proposals" section in **[CITYMAP.md](./CITYMAP.md)**

---

## 📚 DOCUMENTATION FILES

| File | Purpose |
|------|---------|
| **[README.md](./README.md)** | Project overview and purpose |
| **[CONSTITUTION.md](./CONSTITUTION.md)** | Immutable rules all agents follow |
| **[AGENTS.md](./AGENTS.md)** | Registry of all active agents (auto-generated) |
| **[CITYMAP.md](./CITYMAP.md)** | Architecture and dependency graph (auto-generated) |
| **[HELP.md](./HELP.md)** | This file — system help (auto-generated) |

---

## 🛠️ DEVELOPMENT

### Adding a New Agent

1. Create a new directory: `mkdir myagent`
2. Create `myagent/cartridge_main.py` with your agent logic
3. Run `python civic/tools/registry_tool.py .` to register
4. Your agent appears in `AGENTS.md` automatically

### Updating Documentation

These docs are **auto-generated** from actual code:
- `AGENTS.md` — Updated by `civic/tools/registry_tool.py`
- `CITYMAP.md` — Updated by `civic/tools/map_tool.py`
- `HELP.md` — Updated by `civic/tools/help_tool.py`

To regenerate all docs:
```bash
python civic/tools/registry_tool.py .
python civic/tools/map_tool.py .
python civic/tools/help_tool.py .
```

---

## 🔍 SYSTEM ARCHITECTURE OVERVIEW

```
Agent City is a federated system with:

🏛️ CIVIC (Authority) — Registry, licenses, credits
🗳️ FORUM (Democracy) — Proposals and voting
🦅 HERALD (Media) — Publishing and broadcasting
+ Other specialized agents (see AGENTS.md)

All agents follow CONSTITUTION.md rules.
All transactions recorded in ledger (immutable).
```

See **[CITYMAP.md](./CITYMAP.md)** for full architecture.

---

## ❓ COMMON QUESTIONS

### Where do I start?
→ Run `python scripts/summon.py` then read **AGENTS.md**

### How do agents communicate?
→ See **CITYMAP.md** for dependency graph

### What are the rules?
→ Read **CONSTITUTION.md** (immutable law)

### Where is the data stored?
→ `.steward/ledger.json` (immutable ledger)

### How do I add my own agent?
→ See "Development" section above

### Why is documentation auto-generated?
→ Because code is the source of truth. Docs stay in sync.

---

## 📞 SUPPORT

**This help was auto-generated** from your actual system state.
If you see stale information, run:
```bash
python civic/tools/help_tool.py .
```

For detailed information:
- Agent details → **[AGENTS.md](./AGENTS.md)**
- Architecture → **[CITYMAP.md](./CITYMAP.md)**
- Rules → **[CONSTITUTION.md](./CONSTITUTION.md)**
- Code → Check `*/cartridge_main.py` files

---

**Generated by:** civic/tools/help_tool.py
**Authority:** CIVIC Cartridge
**Philosophy:** "A system that documents itself is a system that evolves with truth."
"""

        return content

    def write_help(self, output_file: str = "HELP.md") -> bool:
        """
        Write the help document to HELP.md.

        Args:
            output_file: Output filename (default: HELP.md)

        Returns:
            True if successful, False otherwise
        """
        try:
            content = self.generate_help_markdown()
            output_path = self.root_dir / output_file

            output_path.write_text(content)

            print(f"✅ Help generated: {output_path}")
            agents = self.load_agents_from_registry()
            scripts = self.discover_entry_points()
            print(f"📚 {len(agents)} agents documented")
            print(f"📋 {len(scripts)} scripts documented")

            return True
        except Exception as e:
            print(f"❌ Error writing help: {e}")
            return False


def main():
    """Main entry point."""
    import sys
    root_dir = sys.argv[1] if len(sys.argv) > 1 else "."
    tool = HelpTool(root_dir)
    tool.write_help()


if __name__ == "__main__":
    main()
