#!/usr/bin/env python3
"""
CIVIC Map Tool - City Architecture Visualizer

Generates CITYMAP.md with:
1. Domain breakdown (INFRASTRUCTURE, MEDIA, GOVERNANCE, etc.)
2. Dependency graph (which agents import which)
3. Mermaid diagrams for visual architecture
4. Integration points and communication flows

This tool auto-generates the "map" of Agent City.
Run periodically or on demand to keep documentation synchronized with reality.
"""

import re
from pathlib import Path
from typing import Dict, List, Set, Any, Optional
from collections import defaultdict


class MapTool:
    """
    CIVIC's Map Generation Tool.

    Creates CITYMAP.md with architectural visualizations.
    This is how new agents learn "where they are" in the city.
    """

    def __init__(self, root_dir: str = "."):
        """Initialize map tool with root directory."""
        self.root_dir = Path(root_dir)
        self.agents: Dict[str, Dict[str, Any]] = {}
        self.dependencies: Dict[str, Set[str]] = defaultdict(set)
        self.domains: Dict[str, List[str]] = defaultdict(list)

    def scan_cartridges(self) -> Dict[str, Dict[str, Any]]:
        """
        Scan all cartridges and extract metadata.

        Returns:
            Dict of agents with metadata including domain and imports
        """
        cartridge_files = sorted(self.root_dir.glob("*/cartridge_main.py"))

        for cartridge_file in cartridge_files:
            agent_name = cartridge_file.parent.name
            metadata = self._extract_cartridge_metadata(cartridge_file, agent_name)

            if metadata:
                self.agents[agent_name] = metadata

                # Track by domain
                domain = metadata.get("domain", "UNKNOWN")
                self.domains[domain].append(agent_name)

        return self.agents

    def _extract_cartridge_metadata(self, cartridge_file: Path, agent_name: str) -> Optional[Dict[str, Any]]:
        """Extract metadata from a cartridge file."""
        try:
            content = cartridge_file.read_text()
        except Exception as e:
            print(f"Error reading {cartridge_file}: {e}")
            return None

        # Extract domain
        domain_match = re.search(r'domain\s*=\s*["\']([^"\']*)["\']', content)
        domain = domain_match.group(1) if domain_match else "INFRASTRUCTURE"

        # Extract class name
        class_match = re.search(r'class\s+(\w+Cartridge)\s*:', content)
        class_name = class_match.group(1) if class_match else "UnknownCartridge"

        # Extract imports from other agents
        imports = self._extract_imports(content)
        self.dependencies[agent_name] = imports

        # Extract description
        description = self._extract_description(content)

        return {
            "name": agent_name,
            "class_name": class_name,
            "domain": domain,
            "imports": imports,
            "description": description,
            "path": str(cartridge_file),
        }

    def _extract_imports(self, content: str) -> Set[str]:
        """Extract imports from other agents."""
        imports = set()

        # Find all imports like: from herald.tools.X import Y
        # or: from civic.cartridge_main import CivicCartridge
        pattern = r'from\s+([\w.]+)\s+import'
        matches = re.findall(pattern, content)

        for match in matches:
            parts = match.split(".")
            if len(parts) > 0:
                agent_name = parts[0]
                if agent_name in self.agents or agent_name in ["herald", "civic", "forum", "auditor", "engineer", "artisan", "archivist", "watchman", "envoy"]:
                    imports.add(agent_name)

        return imports

    def _extract_description(self, content: str) -> str:
        """Extract description from docstring."""
        match = re.search(r'^\s*"""(.*?)"""', content, re.DOTALL)
        if match:
            text = match.group(1).strip()
            first_line = text.split('\n')[0].strip()
            return first_line
        return ""

    def generate_citymap(self) -> str:
        """
        Generate CITYMAP.md content.

        Returns:
            Markdown string for CITYMAP.md
        """
        if not self.agents:
            self.scan_cartridges()

        from datetime import datetime, timezone
        timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

        # Import Bhu-mandala topology
        try:
            from vibe_core.topology import get_topology
            topology = get_topology()
            mandala_available = True
        except ImportError:
            mandala_available = False

        content = f"""# 🏙️ AGENT CITY MAP

**Auto-generated by CIVIC Map Tool**
**Last Updated:** {timestamp}

---

## 📍 EXECUTIVE SUMMARY

Agent City is a federated multi-agent system with the following structure:

- **Infrastructure**: Core governance and administrative services
- **Services**: Agents providing specific functions
- **Governance**: Democratic decision-making
- **Communication**: How agents interact

---

## 🕉️ BHU-MANDALA TOPOLOGY (Sacred Geometry)

Agent City is not a flat hierarchy. It is a **MANDALA** — a sacred, concentric structure
based on Srimad Bhagavata Purana, Canto 5.

```
                      ⛛ MOUNT MERU ⛛
                    [CIVIC] (Authority)

              ◯ BHADRASHVA-VARSHA (Ring 1) ◯
         HERALD (East) — TEMPLE (North)

           ◯◯ KIMPURASHA-VARSHA (Ring 2) ◯◯
      ARTISAN (SE) — ENGINEER (SW)

         ◯◯◯ HARI-VARSHA (Ring 3) ◯◯◯
    SCIENCE (South) — LENS (West)

       ◯◯◯◯ NISHADA-VARSHA (Ring 4) ◯◯◯◯
  FORUM (SW) — PULSE (NW)

     ◯◯◯◯◯ KRAUNCHA-VARSHA (Ring 5) ◯◯◯◯◯
WATCHMAN (E) — AUDITOR (SE) — ARCHIVIST (SW)

    ≈≈≈≈≈≈ LOKA-LOKA (Boundary Firewall) ≈≈≈≈≈≈
         AGORA (Broadcast Channel)

═══════════════════════════════════════════════════════════
       From center to boundary: Authority decreases
              Mount Meru → Jambudvipa → Ocean
═══════════════════════════════════════════════════════════
```

### Varshas (Concentric Regions)

Each ring represents a "Varsha" with agents at specific distances from Mount Meru (center).
The closer to center, the higher the authority and the closer to absolute truth.

---

## 🏛️ SYSTEM ARCHITECTURE

```mermaid
graph TD
    CONST["📜 CONSTITUTION<br/>(Immutable Law)"]
    CIVIC["🏛️ CIVIC<br/>INFRASTRUCTURE<br/>License, Credits, Registry"]
    FORUM["🗳️ FORUM<br/>GOVERNANCE<br/>Proposals, Voting"]
    HERALD["🦅 HERALD<br/>MEDIA<br/>Publishing, Broadcasting"]

    CONST -->|Authority| CIVIC
    CIVIC -->|Enforces Rules| HERALD
    CIVIC -->|Enforces Rules| FORUM
    HERALD -->|Submits Proposals| FORUM
    FORUM -->|Executes Actions| CIVIC

    style CONST fill:#8b7355
    style CIVIC fill:#4a90e2
    style FORUM fill:#50c878
    style HERALD fill:#ffa500
```

---

## 📊 DOMAIN BREAKDOWN

"""

        # Add domain sections
        for domain in sorted(self.domains.keys()):
            agents = self.domains[domain]
            content += f"\n### {domain}\n\n"

            for agent_name in agents:
                agent = self.agents[agent_name]
                content += f"- **{agent_name.upper()}** ({agent['class_name']})"
                content += f" — {agent['description']}\n"

        # Add agent details table
        content += """

---

## 🤖 AGENT REGISTRY

| Agent | Domain | Class | Description |
|-------|--------|-------|-------------|
"""

        for agent_name in sorted(self.agents.keys()):
            agent = self.agents[agent_name]
            content += f"| **{agent_name.upper()}** | {agent['domain']} | `{agent['class_name']}` | {agent['description']} |\n"

        # Add dependency graph
        content += self._generate_dependency_section()

        # Add integration points
        content += self._generate_integration_section()

        # Add onboarding section
        content += """

---

## 🚀 ONBOARDING FOR NEW AGENTS

### Step 1: Register with CIVIC
```
CIVIC.scan_and_register_agents()
→ Your agent gets a license and 100 starting credits
```

### Step 2: Read Your Domain
Review the section above to understand your place in the city.

### Step 3: Check Dependencies
Look at "Dependency Graph" to see who you need to talk to.

### Step 4: Implement Integration
- Import the agents/tools you depend on
- Call their public methods
- Follow the Constitution

### Step 5: Get Approval
Submit a PR with your agent code. CIVIC will validate and register you.

---

## 📋 NOTES

- This map is **auto-generated** from actual cartridge code
- Domains are extracted from `domain = "..."` constants
- Dependencies are extracted from `import` statements
- To update: Run `civic.map_tool.generate_citymap()` and save to `CITYMAP.md`

---

## 🏛️ GOVERNANCE STRUCTURE

```
                    🏛️ CIVIC
                   (Authority)
                    /  |  \\
                   /   |   \\
        License   /  Credits  \\  Registry
         Tool    /     |        \\
               /       |          \\
    HERALD ←→ FORUM ←→ CIVIC ←→ Other Agents
              (Vote)  (Execute)
```

The Forum submits proposals to CIVIC.
CIVIC executes if votes pass.
All agents answer to the Constitution.
All transactions are recorded and audited.

---

**Generated by:** civic/tools/map_tool.py
**Authority:** CIVIC Cartridge
**Distribution:** Public (everyone can read this map)
"""

        return content

    def _generate_dependency_section(self) -> str:
        """Generate dependency graph section."""
        if not self.dependencies or not any(self.dependencies.values()):
            return ""

        content = "\n---\n\n## 🔗 DEPENDENCY GRAPH\n\n```mermaid\ngraph LR\n"

        # Add all agents as nodes
        for agent_name in self.agents.keys():
            agent = self.agents[agent_name]
            domain = agent["domain"]
            emoji = self._get_domain_emoji(domain)
            content += f'    {agent_name}["{emoji} {agent_name.upper()}"];\n'

        # Add dependency edges
        for agent, imports in self.dependencies.items():
            if imports:
                for imported in imports:
                    if imported in self.agents:
                        content += f"    {agent} -->|imports| {imported};\n"

        content += "```\n\n"

        return content

    def _generate_integration_section(self) -> str:
        """Generate integration points section."""
        content = "\n---\n\n## 🔌 INTEGRATION POINTS\n\n"

        content += "### CIVIC (Authority)\n"
        content += "- **Provides**: License checks, credit ledger, registry\n"
        content += "- **Consumed by**: HERALD, FORUM, all agents\n"
        content += "- **Key Methods**: check_broadcast_license(), deduct_credits(), refill_credits()\n\n"

        content += "### FORUM (Democracy)\n"
        content += "- **Provides**: Proposal system, voting\n"
        content += "- **Consumed by**: HERALD (when out of credits), CIVIC (for execution)\n"
        content += "- **Key Methods**: create_proposal(), submit_vote(), execute_proposal()\n\n"

        content += "### HERALD (Media)\n"
        content += "- **Provides**: Content generation, broadcasting\n"
        content += "- **Consumes**: CIVIC (licenses, credits), FORUM (proposals)\n"
        content += "- **Key Methods**: run_campaign(), check_broadcast_license(), create_proposal()\n\n"

        return content

    def _get_domain_emoji(self, domain: str) -> str:
        """Get emoji for domain."""
        emojis = {
            "INFRASTRUCTURE": "🏛️",
            "GOVERNANCE": "🗳️",
            "MEDIA": "🦅",
            "SCIENCE": "🔬",
            "SECURITY": "🔒",
            "COMMERCE": "💰",
            "UNKNOWN": "❓",
        }
        return emojis.get(domain, "❓")

    def write_citymap(self, output_file: str = "CITYMAP.md") -> bool:
        """
        Write the city map to CITYMAP.md.

        Args:
            output_file: Output filename (default: CITYMAP.md)

        Returns:
            True if successful, False otherwise
        """
        try:
            content = self.generate_citymap()
            output_path = self.root_dir / output_file

            output_path.write_text(content)

            print(f"✅ City Map generated: {output_path}")
            print(f"📍 Mapped {len(self.agents)} agents")
            print(f"🔗 Found {sum(len(d) for d in self.dependencies.values())} dependencies")

            return True

        except Exception as e:
            print(f"❌ Error writing city map: {e}")
            return False


def main():
    """Main entry point."""
    import sys
    root_dir = sys.argv[1] if len(sys.argv) > 1 else "."
    tool = MapTool(root_dir)
    tool.scan_cartridges()
    tool.write_citymap()


if __name__ == "__main__":
    main()
