"""
Base Sense - Abstract base class for MANAS perception modules.

OPUS-099: VEDA-4 Pattern for Cortex Auto-Discovery
OPUS-167: Fractal Architecture - Senses Generate Intents

The 5 Jnanendriyas (Perception Organs) in Samkhya:
- SHROTRA (Hearing)  → SamvadaListener
- TVAK (Touch)       → PrakritiSense
- CHAKSHU (Sight)    → SutraSense
- RASANA (Taste)     → DharmaSense
- GHRANA (Smell)     → JnanaHandler

This base class enables auto-discovery of senses via SenseLoader.
No more manual import lists. Add a new sense → SenseLoader finds it.

STRICT MODE: If a sense fails to load, the system CRASHES.
We want to know immediately, not discover later that MANAS is blind.

OPUS-167 KEY CHANGE: Senses now generate their own intents.
This restores the fractal architecture where each layer is autonomous.
"""

from abc import ABC, abstractmethod
from pathlib import Path
from typing import TYPE_CHECKING, Any, Dict, List, Optional

if TYPE_CHECKING:
    from vibe_core.plugins.opus_assistant.manas.intent_generator import Intent


class BaseSense(ABC):
    """
    Abstract base class for MANAS perception modules (Jnanendriyas).

    All senses must inherit from this class to be discovered by SenseLoader.

    Required:
        - name: Unique identifier for the sense
        - perceive(): Main perception method (returns sense-specific data)
        - generate_intents(): Generate intents based on perception (OPUS-167)

    Optional:
        - is_enabled: Whether sense is active (default: True)

    Usage:
        class MySense(BaseSense):
            name = "my_sense"

            def __init__(self, workspace: Path, config: Optional[Dict] = None):
                super().__init__(workspace, config)

            def perceive(self, context: Optional[Dict] = None):
                # Sense-specific perception logic
                return SomePerceptionResult(...)

            def generate_intents(self, context: Optional[Dict] = None) -> List[Intent]:
                # OPUS-167: Sense generates its own intents
                perception = self.perceive(context)
                intents = []
                if perception.needs_action:
                    intents.append(Intent(...))
                return intents
    """

    # === MUST BE OVERRIDDEN ===
    name: str = ""  # Unique sense identifier (e.g., "prakriti_sense")

    def __init__(
        self,
        workspace: Optional[Path] = None,
        config: Optional[Dict[str, Any]] = None,
    ):
        """
        Initialize sense.

        Args:
            workspace: Workspace root (default: cwd)
            config: Configuration dict (from config/manas.yaml)
        """
        self._workspace = workspace or Path.cwd()
        self._config = config or {}

    @property
    def workspace(self) -> Path:
        """Get workspace root."""
        return self._workspace

    @property
    def config(self) -> Dict[str, Any]:
        """Get sense configuration."""
        return self._config

    @property
    def is_enabled(self) -> bool:
        """
        Check if sense is enabled.

        Override to implement custom enable/disable logic.
        Default: True (enabled by default)
        """
        return self._config.get("enabled", True)

    @abstractmethod
    def perceive(self, context: Optional[Dict[str, Any]] = None) -> Any:
        """
        Main perception method.

        This is the primary interface for the sense. Each sense
        implements its own perception logic and returns sense-specific data.

        Args:
            context: Optional context dict for perception

        Returns:
            Sense-specific perception result (e.g., GunaSummary, DharmaSummary)
        """
        pass

    def generate_intents(self, context: Optional[Dict[str, Any]] = None) -> List["Intent"]:
        """
        Generate intents based on perception.

        OPUS-167: Fractal Architecture Restoration

        Each sense is responsible for generating its own intents based on
        what it perceives. This removes intent generation from the kernel
        and restores the fractal "As Above, So Below" pattern.

        Default implementation: Returns empty list (no intents).
        Senses should override this to generate meaningful intents.

        Args:
            context: Optional context dict for intent generation

        Returns:
            List of intents generated by this sense
        """
        return []

    def __repr__(self) -> str:
        status = "enabled" if self.is_enabled else "disabled"
        return f"<{self.__class__.__name__}:{self.name} status={status}>"
