"""
THE ARTISAN - Media & Tech Ops Agent.
Part of the Steward Protocol Federation.

Role: Handyman / Blacksmith
Mission: Polish, Format, and Brand assets generated by HERALD.
"""

import logging
from artisan.tools.media_tool import MediaTool

# Setup logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger("ARTISAN_AGENT")


class ArtisanCartridge:
    """
    The Artisan Agent Cartridge.
    Specialized in media processing and technical operations.
    """

    def __init__(self):
        """Initialize the Artisan."""
        self.media_tool = MediaTool()
        logger.info("🔨 THE ARTISAN is online.")

    def process_media(self, file_path: str) -> str:
        """
        Process a media file (Crop, Brand, Optimize).
        
        Args:
            file_path: Path to raw media file
            
        Returns:
            str: Path to processed file (or original if failed)
        """
        logger.info(f"🔨 Artisan received job: Process {file_path}")
        
        processed_path = self.media_tool.process_image(file_path)
        
        if processed_path:
            logger.info(f"✅ Artisan finished job: {processed_path}")
            return processed_path
        else:
            logger.warning("⚠️  Artisan could not process file, returning original.")
            return file_path
