#!/usr/bin/env python3
"""
📦 VIBE OS RELEASE BUILDER
==========================

Creates a user-ready release package containing:
- The vibe binary (Thin Kernel)
- The Standard Library (all holons)
- Default configuration
- Install script

Usage:
    python scripts/build_release.py

Output:
    releases/VibeOS_v1.0/
    ├── vibe                    # The binary
    ├── library/                # All holons (.vibe files)
    ├── config/                 # Default configuration
    ├── install.sh              # Unix installer
    ├── install.bat             # Windows installer
    └── README.md               # Quick start guide
"""

import shutil
import zipfile
from datetime import datetime
from pathlib import Path

VERSION = "1.1.0"
RELEASE_NAME = f"VibeOS_v{VERSION}"


def main():
    print("📦 VIBE OS RELEASE BUILDER")
    print("=" * 50)
    print(f"Version: {VERSION}")
    print()

    # Paths
    project_root = Path(__file__).parent.parent
    dist_dir = project_root / "dist"
    library_dir = project_root / "library"
    releases_dir = project_root / "releases"
    release_dir = releases_dir / RELEASE_NAME

    # Check prerequisites
    binary_path = dist_dir / "vibe"
    library_zip = dist_dir / "vibe_standard_library_v1.0.zip"

    missing = []
    if not binary_path.exists():
        missing.append(f"Binary not found: {binary_path}")
    if not library_zip.exists() and not library_dir.exists():
        missing.append(f"Library not found: {library_zip} or {library_dir}/")

    if missing:
        print("❌ Prerequisites missing:")
        for m in missing:
            print(f"   - {m}")
        print()
        print("Run these first:")
        print("  python scripts/build_binary.py")
        print("  python scripts/release_library.py")
        return 1

    # Create release directory
    if release_dir.exists():
        shutil.rmtree(release_dir)
    release_dir.mkdir(parents=True)

    print(f"📁 Creating: {release_dir}")

    # 1. Copy binary (Merge bundle into release root)
    print("  → Copying binary...")
    if binary_path.is_dir():
        # macOS app bundle or --onedir output: Copy CONTENTS to release_dir
        # We use dirs_exist_ok=True to allow merging if dir exists
        shutil.copytree(binary_path, release_dir, dirs_exist_ok=True)

        # Ensure main executable is runnable
        main_exe = release_dir / "vibe"
        if main_exe.exists():
            main_exe.chmod(0o755)
    else:
        # Single file binary (--onefile output)
        shutil.copy2(binary_path, release_dir / "vibe")
        (release_dir / "vibe").chmod(0o755)

    # 2. Copy library
    print("  → Copying library...")
    release_library = release_dir / "library"
    release_library.mkdir()

    if library_zip.exists():
        # Extract from zip
        with zipfile.ZipFile(library_zip, "r") as zf:
            zf.extractall(release_library)
    else:
        # Copy from directory
        for vibe_file in library_dir.glob("*.vibe"):
            shutil.copy2(vibe_file, release_library / vibe_file.name)

    # 3. Create config directory
    print("  → Creating default config...")
    config_dir = release_dir / "config"
    config_dir.mkdir()

    # Default phoenix.yaml
    (config_dir / "phoenix.yaml").write_text("""# Vibe OS Configuration
# Generated by Release Builder

paths:
  library: "./library"
  data: "~/.vibe/data"

runtime:
  log_level: INFO
  enable_telemetry: false

# Provider configuration (set your API keys here)
providers:
  default: null  # Set to 'anthropic', 'google', or 'openai'
  # anthropic:
  #   api_key: "your-key-here"
""")

    # 4. Create install scripts
    print("  → Creating installers...")

    # Unix installer
    (release_dir / "install.sh").write_text("""#!/bin/bash
# Vibe OS Installer for Unix/macOS

set -e

echo "🌀 Installing Vibe OS..."

# Create config directory
VIBE_HOME="${HOME}/.vibe"
mkdir -p "${VIBE_HOME}"

# Copy library
echo "  → Installing holons..."
cp -r library/* "${VIBE_HOME}/"

# Copy config if not exists
if [ ! -f "${VIBE_HOME}/phoenix.yaml" ]; then
    echo "  → Creating default config..."
    cp config/phoenix.yaml "${VIBE_HOME}/"
fi

# Make binary available
echo "  → Installing binary..."
INSTALL_DIR="/usr/local/bin"
if [ -w "${INSTALL_DIR}" ]; then
    cp vibe "${INSTALL_DIR}/"
else
    echo "  ⚠️  Need sudo to install to ${INSTALL_DIR}"
    sudo cp vibe "${INSTALL_DIR}/"
fi

echo ""
echo "✅ Vibe OS installed successfully!"
echo ""
echo "Try: vibe --help"
echo ""
""")
    (release_dir / "install.sh").chmod(0o755)

    # Windows installer
    (release_dir / "install.bat").write_text("""@echo off
REM Vibe OS Installer for Windows

echo Installing Vibe OS...

REM Create config directory
set VIBE_HOME=%USERPROFILE%\\.vibe
if not exist "%VIBE_HOME%" mkdir "%VIBE_HOME%"

REM Copy library
echo   Installing holons...
xcopy /E /Y library\\* "%VIBE_HOME%\\"

REM Copy config
if not exist "%VIBE_HOME%\\phoenix.yaml" (
    echo   Creating default config...
    copy config\\phoenix.yaml "%VIBE_HOME%\\"
)

REM Copy binary to user path
echo   Installing binary...
copy vibe.exe "%USERPROFILE%\\AppData\\Local\\Microsoft\\WindowsApps\\"

echo.
echo Vibe OS installed successfully!
echo.
echo Try: vibe --help
echo.
pause
""")

    # 5. Create README
    print("  → Creating README...")
    (release_dir / "README.md").write_text(f"""# Vibe OS v{VERSION}

**The Agent Operating System**

## Quick Start

### Unix/macOS
```bash
./install.sh
vibe --help
```

### Windows
```cmd
install.bat
vibe --help
```

## Manual Installation

1. Copy `library/*.vibe` to `~/.vibe/`
2. Copy `config/phoenix.yaml` to `~/.vibe/`
3. Add `vibe` binary to your PATH

## Contents

- `vibe` - The Thin Kernel binary
- `library/` - Standard Library holons ({len(list(release_library.glob("*.vibe")))} agents)
- `config/` - Default configuration
- `install.sh` / `install.bat` - Installers

## Learn More

https://github.com/kimeisele/steward-protocol

---
Built: {datetime.now().strftime("%Y-%m-%d %H:%M")}
""")

    # 6. Create distributable zip
    print("  → Creating distribution zip...")
    zip_path = releases_dir / f"{RELEASE_NAME}.zip"
    with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as zf:
        for file in release_dir.rglob("*"):
            if file.is_file():
                arcname = file.relative_to(releases_dir)
                zf.write(file, arcname)

    # Summary
    print()
    print("=" * 50)
    print("✅ RELEASE BUILT SUCCESSFULLY")
    print("=" * 50)
    print()
    print(f"📁 Folder: {release_dir}")
    print(f"📦 Zip:    {zip_path}")
    print()
    print("Contents:")
    for item in sorted(release_dir.rglob("*")):
        if item.is_file():
            rel = item.relative_to(release_dir)
            size = item.stat().st_size
            print(f"  {rel} ({size:,} bytes)")
    print()
    print(f"Total zip size: {zip_path.stat().st_size:,} bytes")
    print()
    print("🎉 Ready to distribute!")

    return 0


if __name__ == "__main__":
    exit(main())
