#!/usr/bin/env python3
"""
Verify UI Generation
====================
Checks if SETTINGS.md, ENVOY.md, and EPHEMERAL.md are correctly generated by the kernel.
"""

import sys
from pathlib import Path

# Add project root to path
sys.path.insert(0, str(Path(__file__).parent.parent))

from vibe_core.kernel_impl import RealVibeKernel
from vibe_core.plugin_loader import PluginLoader


def verify_ui_generation():
    print("🔍 Verifying UI Generation...")

    root_dir = Path(__file__).parent.parent
    ui_files = ["SETTINGS.md", "ENVOY.md", "EPHEMERAL.md"]

    # 1. Delete existing files
    print("🗑️  Deleting existing UI files...")
    for filename in ui_files:
        path = root_dir / filename
        if path.exists():
            path.unlink()
            print(f"   Deleted {filename}")

    # 2. Boot Kernel
    print("🚀 Booting Kernel...")
    kernel = RealVibeKernel()

    # Load plugins (Interface plugin is critical here)
    loader = PluginLoader()
    plugins = loader.discover()
    kernel._plugins = plugins
    for plugin in plugins:
        if hasattr(plugin, "on_boot"):
            plugin.on_boot(kernel)

    # 3. Trigger Tick (which triggers UI render)
    print("⏱️  Ticking Kernel...")
    kernel._status = "RUNNING"  # Force running status
    kernel.tick()

    # Manually trigger on_tick_post because tick() might return early if queue empty
    # (as discovered in tests)
    for plugin in kernel._plugins:
        if plugin.plugin_id == "interface":
            print("   Triggering InterfacePlugin.on_tick_post...")
            plugin.on_tick_post(kernel)

    # 4. Verify Files Recreated
    print("✅ Verifying files...")
    all_exist = True
    for filename in ui_files:
        path = root_dir / filename
        if path.exists():
            size = path.stat().st_size
            print(f"   ✅ {filename} generated ({size} bytes)")
        else:
            print(f"   ❌ {filename} NOT generated")
            all_exist = False

    if all_exist:
        print("\n🎉 UI Generation Verified: All files created successfully.")
        sys.exit(0)
    else:
        print("\n❌ UI Generation Failed: Some files missing.")
        sys.exit(1)


if __name__ == "__main__":
    verify_ui_generation()
