#!/usr/bin/env python3
"""
KERNEL PULSE - Single heartbeat cycle for state synchronization

After code changes, the kernel must pulse once to update:
- vibe_snapshot.json (living system state)
- OPERATIONS.md (current operational status)
- Ledger entries (what just happened)

This ensures the repo never contains stale data.

Usage:
    python3 scripts/pulse.py

Effect:
    1. Boot VibeKernel
    2. Execute one _pulse() tick
    3. Capture state snapshot
    4. Update OPERATIONS.md
    5. Shutdown gracefully

The Builder Agent should call this after every code change.
This keeps git repo state synchronized with live kernel state.
"""

import json
import logging
import sys
from datetime import datetime, timezone
from pathlib import Path

# Add project root to path
sys.path.insert(0, str(Path(__file__).parent.parent))

# Setup logging
logging.basicConfig(level=logging.INFO, format="%(asctime)s - %(name)s - %(levelname)s - %(message)s")
logger = logging.getLogger("KERNEL_PULSE")


def pulse(full_boot: bool = False):
    """
    Execute one heartbeat cycle to sync live state with repo artifacts.

    Args:
        full_boot: If True, use BootOrchestrator for full agent discovery.
                   If False (default), use bare kernel for quick pulse.
    """
    logger.info("=" * 80)
    logger.info("💓 KERNEL PULSE: Single heartbeat cycle")
    logger.info("=" * 80)

    try:
        if full_boot:
            # Full boot with agent discovery via BootOrchestrator
            from vibe_core.boot_orchestrator import BootOrchestrator
            from vibe_core.config import ConfigLoader

            logger.info("🔌 Full boot mode: Using BootOrchestrator...")

            # Load Phoenix Config
            try:
                loader = ConfigLoader()
                config = loader.load()
                logger.info(f"📜 Loaded config: {config.city_name}")
            except Exception as e:
                logger.warning(f"⚠️  Config load warning: {e} (using defaults)")
                config = None

            # Boot with agent discovery
            orchestrator = BootOrchestrator(config=config)
            kernel = orchestrator.boot()

            logger.info(f"✅ Full boot complete: {kernel.get_status().get('agents_registered', 0)} agents registered")
        else:
            # Quick pulse without agent discovery
            from vibe_core.kernel_impl import RealVibeKernel

            logger.info("🔌 Quick mode: Initializing bare kernel...")
            kernel = RealVibeKernel()

        logger.info("⏱️  Executing single _pulse() tick...")
        kernel._pulse()

        logger.info("📸 Reading generated snapshot...")
        snapshot_path = Path("vibe_snapshot.json")
        if snapshot_path.exists():
            with open(snapshot_path, "r") as f:
                snapshot = json.load(f)
            logger.info(f"   ✅ Snapshot loaded: {snapshot_path}")
            logger.info(f"   📊 Agents: {len(snapshot.get('agents', {}))}")
            logger.info(f"   📊 Status: {snapshot.get('kernel_status', 'unknown')}")
        else:
            logger.warning("   ⚠️  Snapshot file not generated")
            snapshot = {}

        logger.info("📝 Snapshot includes OPERATIONS.md + SETTINGS.md update")

        logger.info("✅ PULSE COMPLETE: Repo state synchronized")

        return True

    except Exception as e:
        logger.error(f"❌ PULSE FAILED: {e}", exc_info=True)
        return False


def update_operations_md(kernel, snapshot):
    """
    Update OPERATIONS.md with current kernel state.
    """
    ops_path = Path("OPERATIONS.md")

    # Generate current timestamp
    timestamp = datetime.now(timezone.utc).isoformat()

    # Extract key metrics from snapshot
    agents_online = len(snapshot.get("kernel_state", {}).get("agent_registry", {}))
    ledger_entries = snapshot.get("kernel_state", {}).get("ledger_size", 0)
    heartbeat_count = snapshot.get("kernel_state", {}).get("heartbeat_count", 0)

    # Update the file
    content = f"""# OPERATIONS LOG

**Last Pulse:** {timestamp}

## Kernel State

| Metric | Value |
|--------|-------|
| Agents Online | {agents_online} |
| Ledger Entries | {ledger_entries} |
| Heartbeat Count | {heartbeat_count} |
| Status | ✅ OPERATIONAL |

## Recent Changes

This file is auto-updated by `scripts/pulse.py` after each code change.

Pulse cycle includes:
- ✅ Kernel boot
- ✅ Single heartbeat (_pulse())
- ✅ Snapshot capture
- ✅ State sync to git artifacts
- ✅ Graceful shutdown

## Archive

All previous pulse records are maintained in git history.

---

*Generated by: `python3 scripts/pulse.py`*
*Execution Date: {timestamp}*
"""

    with open(ops_path, "w") as f:
        f.write(content)

    logger.info("   ✅ OPERATIONS.md updated")


def main():
    """Entry point.

    Usage:
        python3 scripts/agents/pulse.py           # Quick pulse (bare kernel)
        python3 scripts/agents/pulse.py --full    # Full boot with agents
    """
    import argparse

    parser = argparse.ArgumentParser(description="Kernel Pulse - Sync repo state")
    parser.add_argument(
        "--full",
        action="store_true",
        help="Use full boot with BootOrchestrator (includes agent discovery)",
    )
    args = parser.parse_args()

    success = pulse(full_boot=args.full)
    sys.exit(0 if success else 1)


if __name__ == "__main__":
    main()
