#!/usr/bin/env python3
"""
SCRIBE Citymap Renderer - Generate CITYMAP.md

3-LAYER ARCHITECTURE:
1. KERNEL LAYER (vibe_core) - Boot, Security, Topology
2. ROUTING LAYER (tools) - Milk Ocean, Universal Provider
3. AGENT LAYER (cartridges) - The 13 agents

Dynamic discovery + Runtime state = Complete city map

Tool Protocol Compliant (Kernel-Managed).
"""

from collections import defaultdict
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List

from vibe_core.tools.tool_protocol import Tool, ToolResult

from steward.system_agents.scribe.tools.introspector import CartridgeIntrospector
from steward.system_agents.scribe.tools.runtime_inspector import RuntimeInspector
from steward.system_agents.scribe.tools.vibe_introspector import ToolsIntrospector, VibeCoreIntrospector


class CitymapRenderer(Tool):
    """Render comprehensive CITYMAP.md with 3-layer architecture."""

    def __init__(self):
        """Initialize renderer (kernel-managed)."""
        self.root_dir = Path(".")

        # Dynamic introspectors
        self.cart_introspector = CartridgeIntrospector(str(self.root_dir))
        self.vibe_introspector = VibeCoreIntrospector(str(self.root_dir))
        self.tools_introspector = ToolsIntrospector(str(self.root_dir))
        self.runtime_inspector = RuntimeInspector(str(self.root_dir))

        # Data storage
        self.agents: Dict[str, Dict[str, Any]] = {}
        self.vibe_modules: Dict[str, Dict[str, Any]] = {}
        self.tools: Dict[str, List[Dict[str, Any]]] = {}
        self.domains: Dict[str, List[str]] = defaultdict(list)

    @property
    def name(self) -> str:
        return "scribe.citymap_renderer"

    @property
    def description(self) -> str:
        return "Generate CITYMAP.md with 3-layer architecture (kernel, routing, agents)"

    @property
    def parameters_schema(self) -> dict[str, Any]:
        return {
            "action": {
                "type": "string",
                "required": True,
                "description": "Action: 'generate' to scan and render CITYMAP.md content",
            }
        }

    def validate(self, parameters: dict[str, Any]) -> None:
        """Validate renderer parameters."""
        if "action" not in parameters:
            raise ValueError("Missing required parameter: action")
        if parameters["action"] not in ["generate"]:
            raise ValueError(f"Invalid action: {parameters['action']}. Must be 'generate'")

    def execute(self, parameters: dict[str, Any]) -> ToolResult:
        """Execute renderer operation."""
        try:
            action = parameters["action"]
            if action == "generate":
                content = self._scan_and_render()
                return ToolResult(success=True, output=content)
            else:
                return ToolResult(success=False, error=f"Unknown action: {action}")
        except Exception as e:
            return ToolResult(success=False, error=str(e))

    def _scan_and_render(self) -> str:
        """Scan all layers and render complete CITYMAP.md."""
        # Layer 1: Kernel (vibe_core)
        self.vibe_modules = self.vibe_introspector.scan_all()

        # Layer 2: Routing (tools)
        self.tools = self.tools_introspector.scan_all()

        # Layer 3: Agents (cartridges)
        self.agents = self.cart_introspector.scan_all(self.root_dir / "steward" / "system_agents")

        # Runtime state
        system_status = self.runtime_inspector.get_system_status()
        agent_count = self.runtime_inspector.get_agent_count()

        # Track agent domains
        for agent_name, metadata in self.agents.items():
            domain = metadata.get("domain", "INFRASTRUCTURE")
            self.domains[domain].append(agent_name)

        timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

        content = f"""# 🏙️ AGENT CITY MAP

**Auto-generated by SCRIBE (The Documentarian)**
**Last Updated:** {timestamp}

---

## 📊 SYSTEM STATUS DASHBOARD

```
╔══════════════════════════════════════════════════════════════╗
║                    AGENT CITY STATUS                          ║
╠══════════════════════════════════════════════════════════════╣
║  👥 Agents:          {agent_count:>3} registered                      ║
║  🌌 Boot Cycle:      {system_status["boot_status"]["current_cycle"]:<25}              ║
║  ⚡ Security:        {system_status["security_status"]["threat_level"]:<25}              ║
║  💰 Economy:         {system_status["economic_status"].get("status", "N/A"):<25}              ║
║  🌍 Topology:        {system_status["topology_status"]["description"]:<25}              ║
╚══════════════════════════════════════════════════════════════╝
```

---

## 🏗️ 3-LAYER ARCHITECTURE

Agent City is built on three distinct layers:

```
┌─────────────────────────────────────────────────────────┐
│  LAYER 3: AGENT LAYER ({agent_count} agents)                    │
│  👥 Autonomous agents providing services                │
├─────────────────────────────────────────────────────────┤
│  LAYER 2: ROUTING LAYER                                  │
│  🌊 Request routing, semantic analysis, execution        │
├─────────────────────────────────────────────────────────┤
│  LAYER 1: KERNEL LAYER                                   │
│  ⚡ Boot, security, topology, ledger                     │
└─────────────────────────────────────────────────────────┘
```

---

## ⚡ LAYER 1: KERNEL INFRASTRUCTURE

**Location:** `vibe_core/`

The foundational layer that powers Agent City. All agents run on this substrate.

{self._render_kernel_layer()}

---

## 🌊 LAYER 2: ROUTING INFRASTRUCTURE

**Key Agent Tools** that route requests and execute workflows.

{self._render_routing_layer()}

---

## 👥 LAYER 3: AGENT LAYER

**The Citizens of Agent City** - {agent_count} autonomous agents.

### 🗺️ Agents by Domain

{self._render_agents_by_domain()}

### 📋 Complete Agent Registry

| Agent | Domain | Class | Description |
|-------|--------|-------|-------------|
{self._render_agent_table()}

---

## 🔄 REQUEST FLOW

How a user request flows through Agent City:

```
USER INPUT
    ↓
┌─────────────────────┐
│ Universal Provider  │ ← Semantic routing
│ (Sankhya Analysis)  │
└─────────────────────┘
    ↓
┌─────────────────────┐
│ Milk Ocean Router   │ ← Priority detection
│ (Brahma Protocol)   │
└─────────────────────┘
    ↓
┌─────────────────────┐
│ ENVOY               │ ← Task orchestration
│ (Brain of City)     │
└─────────────────────┘
    ↓
┌─────────────────────┐
│ Target Agent        │ ← Execution
│ (SCIENCE, HERALD..) │
└─────────────────────┘
```

---

## 🏛️ GOVERNANCE FLOW

How Agent City governs itself:

```mermaid
graph TD
    CONST["📜 CONSTITUTION<br/>(Immutable Law)"]
    CIVIC["🏛️ CIVIC<br/>Registry, Licenses, Credits"]
    FORUM["🗳️ FORUM<br/>Proposals & Voting"]
    WATCHMAN["⚔️ WATCHMAN<br/>Integrity Enforcement"]
    AGENTS["👥 ALL AGENTS"]

    CONST -->|Enforces| CIVIC
    CONST -->|Enforces| WATCHMAN
    CIVIC -->|Manages| AGENTS
    WATCHMAN -->|Monitors| AGENTS
    AGENTS -->|Submit Proposals| FORUM
    FORUM -->|Executes via| CIVIC

    style CONST fill:#8b7355
    style CIVIC fill:#4a90e2
    style FORUM fill:#50c878
    style WATCHMAN fill:#dc143c
```

---

## 🌍 CITY TOPOLOGY (Bhu-Mandala)

Agents are arranged in concentric rings by authority level:

```
         🏔️ MOUNT MERU (Center)
              CIVIC
               │
      ┌────────┼────────┐
    RING 1   RING 2   RING 3
   WATCHMAN  FORUM   ENVOY
   HERALD   SCIENCE CHRONICLE
                      SCRIBE
                    (Outer rings)
```

**Authority Levels:**
- **Center (10):** CIVIC - Highest authority
- **Ring 1 (9-8):** WATCHMAN, HERALD - Security & Media
- **Ring 2 (7-6):** FORUM, ENVOY, SCIENCE - Governance & Operations
- **Ring 3 (5-4):** Support agents - Infrastructure

---

## 💰 ECONOMIC SYSTEM

**Civic Bank Status:**
{self._render_economic_status(system_status["economic_status"])}

**How Credits Flow:**
1. MINT creates credits (infinite supply)
2. Agents receive 100 CR on registration
3. Services cost credits (e.g., SCIENCE API call = 5 CR)
4. Out of credits? Submit proposal to FORUM for grant

---

## 🔒 SECURITY SYSTEM

**Narasimha Protocol (Hypervisor Killswitch):**
{self._render_security_status(system_status["security_status"])}

**Watchman Patrol (Ground-level Enforcement):**
- Scans codebase for violations (mocks, test infrastructure in prod)
- Issues penalties via Civic Bank
- Can freeze rogue agents

---

## 📋 NOTES

This map is **auto-generated** from live system introspection:
- **Kernel modules** discovered via `VibeCoreIntrospector`
- **Agent tools** discovered via `ToolsIntrospector`
- **Agents** discovered via `CartridgeIntrospector`
- **Runtime state** read from ledger and system files

**To regenerate:**
```bash
python -m steward.system_agents.scribe.cartridge_main
```

---

**Generated by:** scribe/tools/citymap_renderer.py
**Authority:** SCRIBE (The Documentarian)
**Philosophy:** "A city that maps itself is a city that knows itself."
"""

        return content

    def _render_kernel_layer(self) -> str:
        """Render Layer 1: Kernel modules from vibe_core."""
        if not self.vibe_modules:
            return "⚠️  No vibe_core modules discovered\n"

        output = "### 🌌 Discovered Kernel Modules\n\n"

        for module_name, metadata in sorted(self.vibe_modules.items()):
            output += f"**{module_name}** (`{metadata['file']}` - {metadata['lines']} lines)\n"
            output += f"- {metadata['purpose']}\n"
            if metadata.get("features"):
                output += f"- Key components: {', '.join(metadata['features'][:3])}\n"
            output += "\n"

        return output

    def _render_routing_layer(self) -> str:
        """Render Layer 2: Routing tools."""
        if not self.tools:
            return "⚠️  No agent tools discovered\n"

        output = ""

        # Highlight key routing agents
        key_agents = ["envoy", "civic"]

        for agent_name in key_agents:
            if agent_name not in self.tools:
                continue

            output += f"### 🔧 {agent_name.upper()} Tools\n\n"

            for tool in self.tools[agent_name]:
                output += f"**{tool['name']}** (`{tool['file']}` - {tool['lines']} lines)\n"
                output += f"- {tool['purpose']}\n\n"

        return output

    def _render_agents_by_domain(self) -> str:
        """Render agents organized by domain."""
        output = ""

        for domain in sorted(self.domains.keys()):
            agents = self.domains[domain]
            output += f"\n#### {domain}\n\n"

            for agent_name in agents:
                agent = self.agents[agent_name]
                output += f"- **{agent_name.upper()}** ({agent['class_name']}) — {agent['description']}\n"

        return output

    def _render_agent_table(self) -> str:
        """Render complete agent registry table."""
        output = ""

        for agent_name in sorted(self.agents.keys()):
            agent = self.agents[agent_name]
            output += (
                f"| **{agent_name.upper()}** | {agent['domain']} | `{agent['class_name']}` | {agent['description']} |\n"
            )

        return output

    def _render_economic_status(self, econ_status: Dict[str, Any]) -> str:
        """Render economic system status."""
        output = f"- **Status:** {econ_status.get('status', 'Unknown')}\n"

        if econ_status.get("status") == "OPERATIONAL":
            output += f"- **Credits in Circulation:** {econ_status.get('total_credits', 0)} CR\n"
            output += f"- **Transactions Recorded:** {econ_status.get('transaction_count', 0)}\n"
            output += f"- **Ledger Entries:** {econ_status.get('ledger_entries', 0)}\n"
        else:
            output += f"- **Note:** {econ_status.get('description', 'N/A')}\n"

        return output

    def _render_security_status(self, sec_status: Dict[str, Any]) -> str:
        """Render security system status."""
        output = f"- **Threat Level:** {sec_status.get('threat_level', 'Unknown')}\n"
        output += f"- **Status:** {sec_status.get('status', 'Unknown')}\n"
        output += f"- **Threats Detected:** {sec_status.get('threats_detected', 0)}\n"
        output += f"- **Description:** {sec_status.get('description', 'No information')}\n"

        return output
