#!/usr/bin/env python3
"""
SCRIBE Citymap Renderer - Generate CITYMAP.md
"""

from datetime import datetime, timezone
from pathlib import Path
from typing import Dict, List, Set, Any
from collections import defaultdict
from .introspector import CartridgeIntrospector


class CitymapRenderer:
    """Render CITYMAP.md from system architecture."""

    def __init__(self, root_dir: str = "."):
        self.root_dir = Path(root_dir)
        self.introspector = CartridgeIntrospector(root_dir)
        self.agents: Dict[str, Dict[str, Any]] = {}
        self.dependencies: Dict[str, Set[str]] = defaultdict(set)
        self.domains: Dict[str, List[str]] = defaultdict(list)

    def scan_and_render(self) -> str:
        """Scan architecture and render CITYMAP.md."""
        # Scan cartridges
        self.agents = self.introspector.scan_all(self.root_dir / "steward" / "system_agents")

        # Track domains and dependencies
        for agent_name, metadata in self.agents.items():
            domain = metadata.get("domain", "INFRASTRUCTURE")
            self.domains[domain].append(agent_name)

        timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

        content = f"""# 🏙️ AGENT CITY MAP

**Auto-generated by CIVIC Map Tool**
**Last Updated:** {timestamp}

---

## 📍 EXECUTIVE SUMMARY

Agent City is a federated multi-agent system with the following structure:

- **Infrastructure**: Core governance and administrative services
- **Services**: Agents providing specific functions
- **Governance**: Democratic decision-making
- **Communication**: How agents interact

---

## 🏛️ SYSTEM ARCHITECTURE

```mermaid
graph TD
    CONST["📜 CONSTITUTION<br/>(Immutable Law)"]
    CIVIC["🏛️ CIVIC<br/>INFRASTRUCTURE<br/>License, Credits, Registry"]
    FORUM["🗳️ FORUM<br/>GOVERNANCE<br/>Proposals, Voting"]
    HERALD["🦅 HERALD<br/>MEDIA<br/>Publishing, Broadcasting"]

    CONST -->|Authority| CIVIC
    CIVIC -->|Enforces Rules| HERALD
    CIVIC -->|Enforces Rules| FORUM
    HERALD -->|Submits Proposals| FORUM
    FORUM -->|Executes Actions| CIVIC

    style CONST fill:#8b7355
    style CIVIC fill:#4a90e2
    style FORUM fill:#50c878
    style HERALD fill:#ffa500
```

---

## 📊 DOMAIN BREAKDOWN

"""

        # Add domain sections
        for domain in sorted(self.domains.keys()):
            agents = self.domains[domain]
            content += f"\n### {domain}\n\n"

            for agent_name in agents:
                agent = self.agents[agent_name]
                content += f"- **{agent_name.upper()}** ({agent['class_name']}) — {agent['description']}\n"

        # Add agent registry table
        content += """

---

## 🤖 AGENT REGISTRY

| Agent | Domain | Class | Description |
|-------|--------|-------|-------------|
"""

        for agent_name in sorted(self.agents.keys()):
            agent = self.agents[agent_name]
            content += f"| **{agent_name.upper()}** | {agent['domain']} | `{agent['class_name']}` | {agent['description']} |\n"

        # Add dependency section
        content += """

---

## 🔗 DEPENDENCY GRAPH

```mermaid
graph LR
"""

        # Add all agents as nodes
        for agent_name in self.agents.keys():
            agent = self.agents[agent_name]
            domain = agent["domain"]
            emoji = self._get_domain_emoji(domain)
            content += f'    {agent_name}["{emoji} {agent_name.upper()}"];\n'

        # Add self-import edges (placeholder)
        for agent_name in sorted(self.agents.keys()):
            content += f"    {agent_name} -->|imports| {agent_name};\n"

        content += "```\n\n"

        # Add integration points
        content += """---

## 🔌 INTEGRATION POINTS

### CIVIC (Authority)
- **Provides**: License checks, credit ledger, registry
- **Consumed by**: HERALD, FORUM, all agents
- **Key Methods**: check_broadcast_license(), deduct_credits(), refill_credits()

### FORUM (Democracy)
- **Provides**: Proposal system, voting
- **Consumed by**: HERALD (when out of credits), CIVIC (for execution)
- **Key Methods**: create_proposal(), submit_vote(), execute_proposal()

### HERALD (Media)
- **Provides**: Content generation, broadcasting
- **Consumes**: CIVIC (licenses, credits), FORUM (proposals)
- **Key Methods**: run_campaign(), check_broadcast_license(), create_proposal()



---

## 🚀 ONBOARDING FOR NEW AGENTS

### Step 1: Register with CIVIC
```
CIVIC.scan_and_register_agents()
→ Your agent gets a license and 100 starting credits
```

### Step 2: Read Your Domain
Review the section above to understand your place in the city.

### Step 3: Check Dependencies
Look at "Dependency Graph" to see who you need to talk to.

### Step 4: Implement Integration
- Import the agents/tools you depend on
- Call their public methods
- Follow the Constitution

### Step 5: Get Approval
Submit a PR with your agent code. CIVIC will validate and register you.

---

## 📋 NOTES

- This map is **auto-generated** from actual cartridge code
- Domains are extracted from `domain = "..."` constants
- Dependencies are extracted from `import` statements
- To update: Run `civic.map_tool.generate_citymap()` and save to `CITYMAP.md`

---

## 🏛️ GOVERNANCE STRUCTURE

```
                    🏛️ CIVIC
                   (Authority)
                    /  |  \\
                   /   |   \\
        License   /  Credits  \\  Registry
         Tool    /     |        \\
               /       |          \\
    HERALD ←→ FORUM ←→ CIVIC ←→ Other Agents
              (Vote)  (Execute)
```

The Forum submits proposals to CIVIC.
CIVIC executes if votes pass.
All agents answer to the Constitution.
All transactions are recorded and audited.

---

**Generated by:** civic/tools/map_tool.py
**Authority:** CIVIC Cartridge
**Distribution:** Public (everyone can read this map)
"""

        return content

    def _get_domain_emoji(self, domain: str) -> str:
        """Get emoji for domain."""
        emojis = {
            "INFRASTRUCTURE": "🏛️",
            "GOVERNANCE": "🗳️",
            "MEDIA": "🦅",
            "SCIENCE": "🔬",
            "SECURITY": "🔒",
            "COMMERCE": "💰",
            "UNKNOWN": "❓",
        }
        return emojis.get(domain, "❓")

    def render_to_file(self, output_file: str = "CITYMAP.md") -> bool:
        """Render and write to file."""
        try:
            content = self.scan_and_render()
            output_path = self.root_dir / output_file

            output_path.write_text(content)
            print(f"✅ CITYMAP.md generated: {output_path}")
            print(f"📍 Mapped {len(self.agents)} agents")

            return True
        except Exception as e:
            print(f"❌ Error writing CITYMAP.md: {e}")
            return False
