#!/usr/bin/env python3
"""
SCRIBE Help Renderer - Generate HELP.md
"""

import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Dict, List, Any
from .introspector import CartridgeIntrospector, ScriptIntrospector, ConfigIntrospector


class HelpRenderer:
    """Render HELP.md from system state."""

    def __init__(self, root_dir: str = "."):
        self.root_dir = Path(root_dir)
        self.cart_introspector = CartridgeIntrospector(root_dir)
        self.script_introspector = ScriptIntrospector(root_dir)
        self.config_introspector = ConfigIntrospector(root_dir)

    def scan_and_render(self) -> str:
        """Scan system and render HELP.md."""
        agents = self._load_agents_from_registry()
        entry_points = self.script_introspector.discover_entry_points()
        ledger_status = self._check_ledger_status()

        timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

        content = f"""# 📚 STEWARD PROTOCOL - SYSTEM HELP

**Auto-generated by CIVIC Help Tool**
**Last Updated:** {timestamp}
**Status:** 🟢 System Introspection Active

---

## 🚀 QUICK START

### 1️⃣ First Time? Start Here
```bash
# Initialize the system and create your ledger
python scripts/summon.py
```

### 2️⃣ Then, Explore the Agents
Read **[AGENTS.md](./AGENTS.md)** to see all registered agents in the system.

### 3️⃣ Understand the Architecture
Check **[CITYMAP.md](./CITYMAP.md)** to see how agents interact.

### 4️⃣ Deep Dive into Infrastructure
See **[INFRASTRUCTURE.md](./INFRASTRUCTURE.md)** for the complete system plumbing (boot, security, routing, economy, etc.)

### 5️⃣ Review the Constitution
All agents operate under **[CONSTITUTION.md](./CONSTITUTION.md)** rules.

---

## 🏛️ CURRENT SYSTEM STATUS

### Agents Registered
"""

        if agents:
            for agent in agents:
                content += f"- **{agent}** ✅\n"
            content += f"\n**Total:** {len(agents)} agents\n"
        else:
            content += "- No agents discovered (run `python scripts/summon.py` first)\n"

        # Ledger status
        content += f"\n### Ledger Status\n"
        if ledger_status.get("exists"):
            if ledger_status.get("readable"):
                entries = ledger_status.get("total_entries", 0)
                last_update = ledger_status.get("last_update", "unknown")
                content += f"- **Status:** 🟢 Operational\n"
                content += f"- **Transactions Recorded:** {entries}\n"
                content += f"- **Last Update:** {last_update}\n"
            else:
                content += "- **Status:** ⚠️ Found but unreadable\n"
        else:
            content += f"- **Status:** 🔴 Not Initialized\n"
            content += f"- **Action Required:** Run `python scripts/summon.py` to initialize\n"

        # Available scripts
        content += f"""
---

## 📋 AVAILABLE SCRIPTS

How to interact with Agent City:

"""
        if entry_points:
            for script in entry_points:
                desc = f" — {script['description']}" if script['description'] else ""
                content += f"### `{script['name']}`\n"
                content += f"**Location:** `{script['path']}`{desc}\n\n"
                content += f"**Usage:**\n```bash\npython {script['path']}\n```\n\n"
        else:
            content += "No scripts found in `scripts/` directory.\n"

        # Core operations
        content += f"""---

## ⚙️ CORE OPERATIONS

### Starting the System
```bash
# Initialize and start
python scripts/summon.py
```

### Checking Status
```bash
# View current ledger and agent status
python scripts/verify_docs.py
```

### Viewing Agents
- See all agents: **[AGENTS.md](./AGENTS.md)**
- See architecture: **[CITYMAP.md](./CITYMAP.md)**
- See infrastructure: **[INFRASTRUCTURE.md](./INFRASTRUCTURE.md)**

### Governance
- View constitution: **[CONSTITUTION.md](./CONSTITUTION.md)**
- Check governance: See "Proposals" section in **[CITYMAP.md](./CITYMAP.md)**

---

## 📚 DOCUMENTATION FILES

| File | Purpose |
|------|---------|
| **[README.md](./README.md)** | Project overview and purpose |
| **[CONSTITUTION.md](./CONSTITUTION.md)** | Immutable rules all agents follow |
| **[AGENTS.md](./AGENTS.md)** | Registry of all active agents (auto-generated) |
| **[CITYMAP.md](./CITYMAP.md)** | Architecture and dependency graph (auto-generated) |
| **[INFRASTRUCTURE.md](./INFRASTRUCTURE.md)** | Complete infrastructure map: boot, security, routing, economy (auto-generated) |
| **[HELP.md](./HELP.md)** | This file — system help (auto-generated) |

---

## 🛠️ DEVELOPMENT

### Adding a New Agent

1. Create a new directory: `mkdir myagent`
2. Create `myagent/cartridge_main.py` with your agent logic
3. Run `python civic/tools/registry_tool.py .` to register
4. Your agent appears in `AGENTS.md` automatically

### Updating Documentation

These docs are **auto-generated** from actual code:
- `AGENTS.md` — Updated by SCRIBE (agents_renderer.py)
- `CITYMAP.md` — Updated by SCRIBE (citymap_renderer.py)
- `INFRASTRUCTURE.md` — Updated by SCRIBE (infrastructure_renderer.py)
- `HELP.md` — Updated by SCRIBE (help_renderer.py)
- `README.md` — Updated by SCRIBE (readme_renderer.py)

To regenerate all docs:
```bash
python -m steward.system_agents.scribe.cartridge_main
```

---

## 🔍 SYSTEM ARCHITECTURE OVERVIEW

```
Agent City is a federated system with:

🏛️ CIVIC (Authority) — Registry, licenses, credits
🗳️ FORUM (Democracy) — Proposals and voting
🦅 HERALD (Media) — Publishing and broadcasting
+ Other specialized agents (see AGENTS.md)

All agents follow CONSTITUTION.md rules.
All transactions recorded in ledger (immutable).
```

See **[CITYMAP.md](./CITYMAP.md)** for full architecture.

---

## ❓ COMMON QUESTIONS

### Where do I start?
→ Run `python scripts/summon.py` then read **AGENTS.md**

### How do agents communicate?
→ See **CITYMAP.md** for dependency graph

### What are the rules?
→ Read **CONSTITUTION.md** (immutable law)

### Where is the data stored?
→ `.steward/ledger.json` (immutable ledger)

### How do I add my own agent?
→ See "Development" section above

### Why is documentation auto-generated?
→ Because code is the source of truth. Docs stay in sync.

---

## 📞 SUPPORT

**This help was auto-generated** from your actual system state.
If you see stale information, run:
```bash
python -m steward.system_agents.scribe.cartridge_main
```

For detailed information:
- Agent details → **[AGENTS.md](./AGENTS.md)**
- Architecture → **[CITYMAP.md](./CITYMAP.md)**
- Infrastructure → **[INFRASTRUCTURE.md](./INFRASTRUCTURE.md)**
- Rules → **[CONSTITUTION.md](./CONSTITUTION.md)**
- Code → Check `*/cartridge_main.py` files

---

**Generated by:** scribe/tools/help_renderer.py
**Authority:** SCRIBE (The Documentarian)
**Philosophy:** "A system that documents itself is a system that evolves with truth."
"""

        return content

    def _load_agents_from_registry(self) -> List[str]:
        """Extract agent names from AGENTS.md."""
        return self.config_introspector.load_agents_from_registry()

    def _check_ledger_status(self) -> Dict[str, Any]:
        """Check if ledger exists."""
        ledger_file = self.root_dir / ".steward" / "ledger.json"

        if not ledger_file.exists():
            return {
                "exists": False,
                "message": "Ledger not yet initialized. Run `python scripts/summon.py` to start."
            }

        try:
            data = json.loads(ledger_file.read_text())
            entries = data.get("chain_of_trust", {}).get("entries", [])

            return {
                "exists": True,
                "total_entries": len(entries),
                "initialized": True,
                "last_update": entries[-1].get("timestamp", "unknown") if entries else "never"
            }
        except:
            return {"exists": True, "readable": False}

    def render_to_file(self, output_file: str = "HELP.md") -> bool:
        """Render and write to file."""
        try:
            content = self.scan_and_render()
            output_path = self.root_dir / output_file

            output_path.write_text(content)
            print(f"✅ HELP.md generated: {output_path}")

            return True
        except Exception as e:
            print(f"❌ Error writing HELP.md: {e}")
            return False
