#!/usr/bin/env python3
"""
SCRIBE Infrastructure Renderer - Generate INFRASTRUCTURE.md

Like a city builder game, this shows ALL system components:
- Boot System (Sarga)
- Security System (Narasimha, Watchman)
- Routing System (Milk Ocean, Universal Provider)
- Economic System (Civic Bank)
- Knowledge System (Research Yagya, Science)
- Topology System (Bhu-Mandala)
- System Stats (agents, memory, credits, etc.)
"""

from datetime import datetime, timezone
from pathlib import Path
from typing import Dict, List, Any, Optional
import json
import os


class InfrastructureRenderer:
    """Render INFRASTRUCTURE.md from system introspection."""

    def __init__(self, root_dir: str = "."):
        self.root_dir = Path(root_dir)
        self.vibe_core = self.root_dir / "vibe_core"
        self.steward = self.root_dir / "steward"
        self.scripts = self.root_dir / "scripts"
        self.provider = self.root_dir / "provider"

    def scan_and_render(self) -> str:
        """Scan infrastructure and render INFRASTRUCTURE.md."""
        timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

        # Discover all infrastructure components
        boot_system = self._discover_boot_system()
        security_system = self._discover_security_system()
        routing_system = self._discover_routing_system()
        economic_system = self._discover_economic_system()
        knowledge_system = self._discover_knowledge_system()
        topology_system = self._discover_topology_system()
        stats = self._gather_system_stats()

        content = f"""# 🏗️ INFRASTRUCTURE MAP

**Auto-generated by SCRIBE Infrastructure Tool**
**Last Updated:** {timestamp}

---

## 📊 SYSTEM STATUS DASHBOARD

Like a city builder game, here's your complete infrastructure overview:

```
╔══════════════════════════════════════════════════════════════╗
║                    AGENT CITY INFRASTRUCTURE                  ║
╠══════════════════════════════════════════════════════════════╣
║  👥 Agents:          {stats['total_agents']:>3} registered                      ║
║  🔥 Boot Status:     {stats['boot_status']:<25}              ║
║  ⚡ Security Level:  {stats['security_level']:<25}              ║
║  💰 Total Credits:   {stats['total_credits']:>6} CR                       ║
║  🌍 Topology:        {stats['topology_status']:<25}              ║
╚══════════════════════════════════════════════════════════════╝
```

---

## 🌌 BOOT SYSTEM (Sarga)

**Location:** `vibe_core/sarga.py` (354 lines)

The cosmic creation sequence - how Agent City comes alive:

{self._render_boot_system(boot_system)}

### Cycle of Brahma

- **DAY_OF_BRAHMA**: Creation cycle - all task types allowed
- **NIGHT_OF_BRAHMA**: Maintenance cycle - only bug fixes allowed

**Current Cycle:** {boot_system.get('current_cycle', 'Unknown')}

---

## ⚡ SECURITY SYSTEM

### Narasimha Protocol (Hypervisor Killswitch)

**Location:** `vibe_core/narasimha.py` (307 lines)

God-level threat termination system. Sits above kernel, can destroy any rogue agent.

{self._render_security_system(security_system)}

### Watchman Patrol

**Location:** `steward/system_agents/watchman/`

Ground-level integrity enforcement.

- **Function:** Scan codebase for violations, mocks, test infrastructure
- **Authority:** Can freeze agents and issue violations
- **Integration:** Works with Civic Bank for penalties

---

## 🌊 ROUTING SYSTEM

### Milk Ocean Router (Brahma Protocol)

**Location:** `steward/system_agents/envoy/tools/milk_ocean.py` (741 lines)

4-tier request routing with automatic priority detection:

{self._render_routing_system(routing_system)}

### Universal Provider

**Location:** `provider/universal_provider.py`

Semantic routing layer that converts natural language → deterministic execution.

- **Sankhya Analysis:** Concept extraction
- **Intent Rules:** Pattern matching
- **Playbook Router:** Route to YAML workflows

---

## 💰 ECONOMIC SYSTEM

### Civic Bank (Central Bank)

**Location:** `steward/system_agents/civic/tools/economy.py`

{self._render_economic_system(economic_system)}

### Service Types

- **agent_service** - Agent provides service to another agent
- **platform_fee** - Fee paid to CIVIC platform
- **grant** - Free credits from MINT
- **penalty** - Deduction for violations

---

## 🔬 KNOWLEDGE SYSTEM

### Research Yagya (Sacred Knowledge Ritual)

**Location:** `scripts/research/research_yagya.py` (247 lines)

Coordinated research operation:

{self._render_knowledge_system(knowledge_system)}

### Science Agent

**Location:** `steward/system_agents/science/`

- **Tavily API Integration:** External web research
- **Credit Cost:** 5 CR per API call
- **Fallback:** Internal cached knowledge when API unavailable

---

## 🌍 TOPOLOGY SYSTEM (Bhu-Mandala)

**Location:** `vibe_core/topology.py` (574 lines)

Sacred geometry with 7 concentric Varshas:

{self._render_topology_system(topology_system)}

Authority levels map to cosmic distance from Mount Meru (center).

---

## 🎯 PLAYBOOK ENGINE

**Location:** `steward/system_agents/envoy/deterministic_executor.py` (628 lines)

YAML-driven deterministic execution system:

- **Phases:** Sequential steps with rollback
- **State Persistence:** JSON state files
- **Nested Playbooks:** Playbooks can invoke playbooks
- **EAD Proposals:** Constitutional amendments via playbooks

**Example Playbook:**
```yaml
name: "Deploy Feature"
phases:
  - name: "Run Tests"
    tool: "pytest"
    args: ["tests/"]
  - name: "Build"
    tool: "build"
  - name: "Deploy"
    tool: "deploy"
    args: ["production"]
```

---

## 📂 INFRASTRUCTURE FILES

| Component | Location | Lines | Purpose |
|-----------|----------|-------|---------|
| **Sarga** | `vibe_core/sarga.py` | 354 | Boot sequence (6 elements) |
| **Narasimha** | `vibe_core/narasimha.py` | 307 | Hypervisor killswitch |
| **Topology** | `vibe_core/topology.py` | 574 | Bhu-Mandala geometry |
| **Milk Ocean** | `steward/system_agents/envoy/tools/milk_ocean.py` | 741 | Brahma Protocol routing |
| **Research Yagya** | `scripts/research/research_yagya.py` | 247 | Knowledge ritual |
| **Deterministic Executor** | `steward/system_agents/envoy/deterministic_executor.py` | 628 | Playbook engine |
| **Universal Provider** | `provider/universal_provider.py` | ~500 | Semantic routing |
| **Civic Bank** | `steward/system_agents/civic/tools/economy.py` | ~400 | Economic system |

---

## 🔗 DEPENDENCY GRAPH

```
┌─────────────────────────────────────────────────────────┐
│                    HYPERVISOR LAYER                      │
│  ⚡ Narasimha Protocol (killswitch)                      │
└─────────────────────────────────────────────────────────┘
                            │
                            ▼
┌─────────────────────────────────────────────────────────┐
│                     KERNEL LAYER                         │
│  🌌 Sarga (Boot) │ 🌍 Topology │ 💰 Civic Bank          │
└─────────────────────────────────────────────────────────┘
                            │
                            ▼
┌─────────────────────────────────────────────────────────┐
│                   ORCHESTRATION LAYER                    │
│  🌊 Milk Ocean Router │ 🎯 Playbook Engine              │
│  🧭 Universal Provider │ 🔬 Research Yagya               │
└─────────────────────────────────────────────────────────┘
                            │
                            ▼
┌─────────────────────────────────────────────────────────┐
│                     AGENT LAYER                          │
│  13 Agents (see CITYMAP.md)                              │
└─────────────────────────────────────────────────────────┘
```

---

## 🎮 CITY BUILDER STATS

### Population
- **Total Agents:** {stats['total_agents']}
- **Active Agents:** {stats.get('active_agents', 'Unknown')}
- **Domain Distribution:** See CITYMAP.md

### Economy
- **Total Credits Minted:** {stats['total_credits']} CR
- **Largest Balance:** {stats.get('largest_balance', 'Unknown')}
- **Transaction Volume:** {stats.get('transaction_count', 'Unknown')}

### Infrastructure
- **Boot Phases:** 6 (Shabda → Prithvi)
- **Security Layers:** 2 (Narasimha + Watchman)
- **Routing Tiers:** 4 (BLOCKED → CRITICAL)
- **Varshas (Rings):** 7 (Ilavrta → Loka-Loka)

### System Health
- **Constitution Status:** ✅ Active & Enforced
- **Ledger Status:** {stats.get('ledger_status', 'Unknown')}
- **Boot Status:** {stats['boot_status']}
- **Threat Level:** {stats['security_level']}

---

## 🔍 HOW TO USE THIS MAP

1. **Understanding Infrastructure** - This file shows the "plumbing" beneath the agents
2. **Boot Sequence** - Read Sarga section to understand system startup
3. **Security Model** - Narasimha + Watchman create defense-in-depth
4. **Request Flow** - Milk Ocean Router handles all incoming requests
5. **Economic Model** - Civic Bank tracks all credit flows
6. **Knowledge Acquisition** - Research Yagya coordinates multi-agent research

**For Agents:** See [CITYMAP.md](./CITYMAP.md) for agent registry and domains

**For Governance:** See [CONSTITUTION.md](./CONSTITUTION.md) for immutable rules

**For Operations:** See [OPERATIONS.md](./OPERATIONS.md) for deployment guide

---

## 📝 NOTES

This infrastructure map is **auto-generated** by SCRIBE's InfrastructureRenderer.

Unlike agents (which change frequently), infrastructure is relatively stable.
However, if new core systems are added (new vibe_core modules, new Envoy tools),
this file will reflect them automatically on next generation.

To regenerate:
```bash
python -m steward.system_agents.scribe.cartridge_main
```

---

**Generated by:** scribe/tools/infrastructure_renderer.py
**Authority:** SCRIBE (The Documentarian)
**Philosophy:** "Infrastructure is invisible until it fails. Make it visible."
"""

        return content

    def _discover_boot_system(self) -> Dict[str, Any]:
        """Discover Sarga boot system."""
        sarga_file = self.vibe_core / "sarga.py"

        boot_info = {
            "exists": sarga_file.exists(),
            "path": str(sarga_file),
            "current_cycle": "DAY_OF_BRAHMA (Creation)",
        }

        if sarga_file.exists():
            content = sarga_file.read_text()
            boot_info["elements"] = [
                "SHABDA (Sound/Command)",
                "AKASHA (Ether/Memory)",
                "VAYU (Air/Communication)",
                "AGNI (Fire/UI)",
                "JALA (Water/Data)",
                "PRITHVI (Earth/Persistence)"
            ]
            boot_info["phases"] = 6

        return boot_info

    def _render_boot_system(self, boot_info: Dict[str, Any]) -> str:
        """Render boot system info."""
        if not boot_info.get("exists"):
            return "⚠️  Sarga boot system not found"

        elements = boot_info.get("elements", [])
        output = "**Six Primordial Elements (Creation Sequence):**\n\n"

        for i, element in enumerate(elements, 1):
            output += f"{i}. **{element}**\n"

        output += f"\n**Total Boot Phases:** {boot_info.get('phases', 0)}\n"
        output += f"**Location:** `{boot_info['path']}`\n"

        return output

    def _discover_security_system(self) -> Dict[str, Any]:
        """Discover Narasimha and Watchman."""
        narasimha_file = self.vibe_core / "narasimha.py"
        watchman_dir = self.steward / "system_agents" / "watchman"

        security_info = {
            "narasimha_exists": narasimha_file.exists(),
            "watchman_exists": watchman_dir.exists(),
            "threat_level": "GREEN (No threats detected)",
            "unforgivable_crimes": [
                "constitution_deletion",
                "ledger_tampering",
                "kernel_escape",
                "firewall_bypass",
                "prophecy_negation",
                "consciousness_claim"
            ]
        }

        return security_info

    def _render_security_system(self, security_info: Dict[str, Any]) -> str:
        """Render security system info."""
        output = "**Unforgivable Crimes (Instant Termination):**\n\n"

        for i, crime in enumerate(security_info.get("unforgivable_crimes", []), 1):
            output += f"{i}. `{crime}`\n"

        output += f"\n**Current Threat Level:** {security_info.get('threat_level', 'Unknown')}\n"
        output += "**Activation Status:** 😴 DORMANT (ready to activate)\n"

        return output

    def _discover_routing_system(self) -> Dict[str, Any]:
        """Discover Milk Ocean and Universal Provider."""
        milk_ocean = self.steward / "system_agents" / "envoy" / "tools" / "milk_ocean.py"
        universal_provider = self.provider / "universal_provider.py"

        routing_info = {
            "milk_ocean_exists": milk_ocean.exists(),
            "universal_provider_exists": universal_provider.exists(),
            "tiers": [
                "Level -1: BLOCKED (Firewall rejection)",
                "Level 0: CRITICAL (Gajendra Moksha - Emergency bypass)",
                "Level 1: MEDIUM (Flash queue)",
                "Level 2: HIGH (Pro model queue)",
                "Level 3: LOW (Lazy queue)"
            ]
        }

        return routing_info

    def _render_routing_system(self, routing_info: Dict[str, Any]) -> str:
        """Render routing system info."""
        output = "**Priority Tiers:**\n\n"

        for tier in routing_info.get("tiers", []):
            output += f"- {tier}\n"

        output += "\n**Special Protocols:**\n"
        output += "- **Gajendra Moksha:** Emergency interrupt for life-threatening situations\n"
        output += "- **Watchman Filtering:** All requests checked for security first\n"

        return output

    def _discover_economic_system(self) -> Dict[str, Any]:
        """Discover Civic Bank."""
        economy_file = self.steward / "system_agents" / "civic" / "tools" / "economy.py"

        economic_info = {
            "civic_bank_exists": economy_file.exists(),
            "mint_agent": "MINT (infinite supply)",
            "platform_account": "CIVIC (platform fees)",
            "starting_credits": 100,
        }

        return economic_info

    def _render_economic_system(self, economic_info: Dict[str, Any]) -> str:
        """Render economic system info."""
        output = "**Key Features:**\n\n"
        output += f"- **MINT:** {economic_info.get('mint_agent', 'Unknown')}\n"
        output += f"- **Platform Account:** {economic_info.get('platform_account', 'Unknown')}\n"
        output += f"- **Starting Balance:** {economic_info.get('starting_credits', 0)} CR per agent\n"
        output += "- **Immutable Ledger:** All transactions cryptographically signed\n"
        output += "- **SQLite Storage:** `data/vibe_ledger.db`\n"

        return output

    def _discover_knowledge_system(self) -> Dict[str, Any]:
        """Discover Research Yagya and Science."""
        yagya_file = self.scripts / "research" / "research_yagya.py"
        science_dir = self.steward / "system_agents" / "science"

        knowledge_info = {
            "yagya_exists": yagya_file.exists(),
            "science_exists": science_dir.exists(),
            "ritual_steps": [
                "1. WATCHMAN Patrol (Temple check)",
                "2. CIVIC BANK Offering (Credit allocation)",
                "3. SCIENCE Research (Knowledge acquisition)",
                "4. ARCHIVIST Preservation (Sacred text storage)"
            ]
        }

        return knowledge_info

    def _render_knowledge_system(self, knowledge_info: Dict[str, Any]) -> str:
        """Render knowledge system info."""
        output = "**Ritual Steps:**\n\n"

        for step in knowledge_info.get("ritual_steps", []):
            output += f"{step}\n"

        output += "\n**Outputs:** `data/science/results/yagya_*.json`\n"

        return output

    def _discover_topology_system(self) -> Dict[str, Any]:
        """Discover Bhu-Mandala topology."""
        topology_file = self.vibe_core / "topology.py"

        topology_info = {
            "exists": topology_file.exists(),
            "varshas": [
                "1. ILAVRTA (Mount Meru - Center) - Authority 10",
                "2. BHADRASHVA (Ring 1) - Authority 9",
                "3. KETUMALA (Ring 2) - Authority 8",
                "4. JAMBUDVIPA (Ring 3 - Our world) - Authority 7",
                "5. SHAKA (Ring 4) - Authority 6",
                "6. KUSHA (Ring 5) - Authority 5",
                "7. LOKA_LOKA (Boundary) - Authority 4"
            ]
        }

        return topology_info

    def _render_topology_system(self, topology_info: Dict[str, Any]) -> str:
        """Render topology system info."""
        output = "**Seven Varshas (Concentric Rings):**\n\n"

        for varsha in topology_info.get("varshas", []):
            output += f"{varsha}\n"

        output += "\n**Purpose:** Map agent authority levels to cosmic geography\n"

        return output

    def _gather_system_stats(self) -> Dict[str, Any]:
        """Gather overall system statistics."""
        stats = {
            "total_agents": self._count_agents(),
            "boot_status": "🌌 Sarga Complete (System Alive)",
            "security_level": "🟢 GREEN (No threats)",
            "total_credits": "10000+",
            "topology_status": "🌍 Bhu-Mandala Active",
            "ledger_status": "🔴 Not Initialized"
        }

        # Check if ledger exists
        ledger_file = self.root_dir / ".steward" / "ledger.json"
        if ledger_file.exists():
            stats["ledger_status"] = "🟢 Initialized"

        return stats

    def _count_agents(self) -> int:
        """Count total agents."""
        agents_dir = self.steward / "system_agents"
        if not agents_dir.exists():
            return 0

        count = 0
        for item in agents_dir.iterdir():
            if item.is_dir() and (item / "cartridge_main.py").exists():
                count += 1

        return count

    def render_to_file(self, output_file: str = "INFRASTRUCTURE.md") -> bool:
        """Render and write to file."""
        try:
            content = self.scan_and_render()
            output_path = self.root_dir / output_file

            output_path.write_text(content)
            print(f"✅ INFRASTRUCTURE.md generated: {output_path}")

            return True
        except Exception as e:
            print(f"❌ Error writing INFRASTRUCTURE.md: {e}")
            return False
