#!/usr/bin/env python3
"""
SCRIBE README Renderer - Generate README.md from introspection

ZERO HARDCODED LINE NUMBERS! All data from:
- pyproject.toml
- git stats
- agent count (link to AGENTS.md, NO full table)
- CONSTITUTION.md
- AST parsing for code references

Tool Protocol Compliant (Kernel-Managed).
"""

from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Optional

from jinja2 import Environment, FileSystemLoader, Template

# Import from shared base (eliminates DRY violation)
from steward.system_agents.scribe.tools.base import (
    Tool,
    ToolResult,
    get_kernel_status,
)

from .project_introspector import ProjectIntrospector


class ReadmeRenderer(Tool):
    """Render README.md from project introspection.

    Supports both:
    - Kernel-managed mode (via Tool Protocol)
    - Standalone mode (via render() method)
    """

    def __init__(self, root_dir: str = "."):
        """Initialize renderer.

        Args:
            root_dir: Project root directory (for standalone mode)
        """
        self.root_dir = Path(root_dir)
        self.introspector = ProjectIntrospector(str(self.root_dir))

    @property
    def name(self) -> str:
        return "scribe.readme_renderer"

    @property
    def description(self) -> str:
        return "Generate README.md from project introspection (pyproject.toml, git stats, agent count)"

    @property
    def parameters_schema(self) -> dict[str, Any]:
        return {
            "action": {
                "type": "string",
                "required": True,
                "description": "Action: 'generate' to scan and render README.md content",
            }
        }

    def validate(self, parameters: dict[str, Any]) -> None:
        """Validate renderer parameters."""
        if "action" not in parameters:
            raise ValueError("Missing required parameter: action")
        if parameters["action"] not in ["generate"]:
            raise ValueError(f"Invalid action: {parameters['action']}. Must be 'generate'")

    def execute(self, parameters: dict[str, Any]) -> ToolResult:
        """Execute renderer operation."""
        try:
            action = parameters["action"]
            if action == "generate":
                content = self._render()
                return ToolResult(success=True, output=content)
            else:
                return ToolResult(success=False, error=f"Unknown action: {action}")
        except Exception as e:
            return ToolResult(success=False, error=str(e))

    def _find_governance_gate_lines(self) -> Optional[str]:
        """Find governance gate code location.

        Returns:
            String like "vibe_core/kernel_impl.py" (NO line numbers - those break locally)
        """
        kernel_file = self.root_dir / "vibe_core" / "kernel_impl.py"
        if not kernel_file.exists():
            return None

        # Just return the file path - line numbers (#L123) only work on GitHub, not locally
        return "vibe_core/kernel_impl.py"

    def _get_template_dir(self) -> Path:
        """Get the templates directory path."""
        # Templates are in sibling directory to tools/
        return Path(__file__).parent.parent / "templates"

    def _render(self) -> str:
        """Generate README.md content from introspection."""
        # Get all metadata
        metadata = self.introspector.get_all_metadata()

        # Find governance gate line numbers dynamically
        governance_gate_ref = self._find_governance_gate_lines()
        if governance_gate_ref:
            governance_link = f"[Governance Gate Code]({governance_gate_ref})"
        else:
            governance_link = "[Governance Gate Code](vibe_core/kernel_impl.py)"

        # Load template from external file (maintainable, no inline strings)
        template_dir = self._get_template_dir()
        template_file = template_dir / "readme.jinja2"

        if template_file.exists():
            # Use external template (preferred)
            env = Environment(loader=FileSystemLoader(str(template_dir)))
            template = env.get_template("readme.jinja2")
        else:
            # Fallback to minimal inline template
            template = Template("# {{ project.name }}\n\n*Auto-generated by SCRIBE.*\n")

        # Get unified header variables
        timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
        kernel_status = get_kernel_status(str(self.root_dir))

        content = template.render(
            # Unified header variables
            timestamp=timestamp,
            generator="SCRIBE",
            kernel_status=kernel_status,
            # README-specific variables
            project=metadata["project"],
            git=metadata["git"],
            agent_count=metadata["agent_count"],
            governance_link=governance_link,
        )

        return content

    # Standalone mode method (for generate_docs.py)
    def render(self) -> str:
        """Standalone method to generate README.md content.

        Returns:
            Generated README.md content
        """
        return self._render()
